apiVersion: v1
kind: Namespace
metadata:
  name: stalwart
  labels:
    app.kubernetes.io/name: stalwart
    {{- include "custom.labels" . | nindent 4 }}
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
