stalwart:
  controllers:
    main:
      type: deployment
      replicas: 1
      strategy: Recreate
      containers:
        main:
          image:
            repository: ghcr.io/stalwartlabs/stalwart
            tag: v0.15.5@sha256:dcf575db2d53d9ef86d6ced8abe4ba491984659a0f8862cc6079ee7b41c3c568
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
          targetPort: 8080
        smtp:
          port: 25
          targetPort: 25
        smtps:
          port: 465
          targetPort: 465
        imap:
          port: 143
          targetPort: 143
        imaps:
          port: 993
          targetPort: 993
  route:
    main:
      kind: HTTPRoute
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway
          namespace: traefik
      hostnames:
        - stalwart.alexlebens.net
      rules:
        - backendRefs:
            - name: stalwart
              port: 80
          matches:
            - path:
                type: PathPrefix
                value: /
  persistence:
    config:
      forceRename: stalwart-config
      storageClass: ceph-block
      accessMode: ReadWriteOnce
      size: 10Gi
      advancedMounts:
        main:
          main:
            - path: /opt/stalwart
              readOnly: false
postgres-18-cluster:
  mode: recovery
  recovery:
    method: objectStore
    objectStore:
      index: 1
  backup:
    objectStore:
      - name: garage-local
        index: 1
        destinationBucket: postgres-backups
        externalSecretCredentialPath: /garage/home-infra/postgres-backups
        isWALArchiver: true
    scheduledBackups:
      - name: live-backup
        suspend: false
        immediate: true
        schedule: "0 5 16 * * *"
        backupName: garage-local
volsync-target-config:
  pvcTarget: stalwart-config
  local:
    enabled: true
    schedule: 28 11 * * *
  remote:
    enabled: true
    schedule: 28 12 * * *
  external:
    enabled: true
    schedule: 28 13 * * *
