apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: bazarr
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: bazarr
    {{- include "custom.labels" . | nindent 4 }}
spec:
  name: "Bazarr"
  launchUrl: https://bazarr.alexlebens.net
  description: "A companion application to Sonarr and Radarr. It manages and downloads subtitles based on your requirements."
  callbackUrls:
    - https://bazarr.alexlebens.net/oauth2/callback
  pkceEnabled: true
  skipConsent: true
  allowedUserGroups:
    - name: admin
      namespace: pocket-id-operator
  clientID: 68BD867B-B86E-4FC6-BBB3-9B5BB5687950
  clientSecretRef:
    name: bazarr-oauth-proxy
    key: OAUTH2_PROXY_CLIENT_SECRET
  logo:
    logoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/png/bazarr.png
    darkLogoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/png/bazarr.png
