apiVersion: v2
name: external-dns
version: 1.0.0
description: External DNS
keywords:
  - external-dns
  - dns
home: https://docs.alexlebens.dev/Applications/external-dns/
sources:
  - https://github.com/kubernetes-sigs/external-dns
  - https://explore.ggcr.dev/?repo=registry.k8s.io%2Fexternal-dns%2Fexternal-dns
  - https://github.com/kashalls/external-dns-unifi-webhook
  - https://github.com/kubernetes-sigs/external-dns/tree/master/charts/external-dns
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/common-helpers
maintainers:
  - name: alexlebens
dependencies:
  - name: external-dns
    alias: external-dns-unifi
    repository: https://kubernetes-sigs.github.io/external-dns/
    version: 1.21.1
  - name: external-dns
    alias: external-dns-pdns-cluster
    repository: https://kubernetes-sigs.github.io/external-dns/
    version: 1.21.1
  - name: external-dns
    alias: external-dns-pdns-ps08rp
    repository: https://kubernetes-sigs.github.io/external-dns/
    version: 1.21.1
  - name: external-dns
    alias: external-dns-pdns-ps09rp
    repository: https://kubernetes-sigs.github.io/external-dns/
    version: 1.21.1
  - name: common-helpers
    repository: oci://harbor.alexlebens.net/helm-charts
    version: 0.4.1
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/kubernetes.png
# renovate: datasource=github-releases depName=kubernetes-sigs/external-dns
appVersion: v0.22.0
