apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: slskd-config-secret
  namespace: slskd
  labels:
    app.kubernetes.io/name: slskd-config-secret
    app.kubernetes.io/instance: slskd
    app.kubernetes.io/part-of: slskd
spec:
  provider: openbao
  parameters:
    vaultAddress: "http://openbao-internal.openbao:8200"
    roleName: slskd
    objects: |
      - objectName: slskd-config-secret
        fileName: slskd.yml
        secretPath: secret/cl01tl/slskd/config
        secretKey: slskd.yml
