plex:
  controllers:
    main:
      type: deployment
      replicas: 1
      strategy: Recreate
      pod:
        securityContext:
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - jellyfin
                topologyKey: kubernetes.io/hostname
      containers:
        main:
          image:
            repository: ghcr.io/linuxserver/plex
            tag: 1.43.1.10576-06378bdcd-ls300@sha256:09fe33e5efd991681ea3cbd3e3cb262cd1ae26d4a0145a4141ead284d8f21de6
          env:
            - name: TZ
              value: America/Chicago
            - name: VERSION
              value: docker
          resources:
            limits:
              gpu.intel.com/i915: 1
            requests:
              gpu.intel.com/i915: 1
              cpu: 100m
              memory: 250Mi
  service:
    main:
      controller: main
      type: LoadBalancer
      ports:
        http:
          port: 32400
          targetPort: 32400
  route:
    main:
      kind: HTTPRoute
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway
          namespace: traefik
      hostnames:
        - plex.alexlebens.net
      rules:
        - backendRefs:
            - name: plex
              port: 32400
          matches:
            - path:
                type: PathPrefix
                value: /
  persistence:
    config:
      forceRename: plex-config
      storageClass: ceph-block
      accessMode: ReadWriteOnce
      size: 100Gi
      advancedMounts:
        main:
          main:
            - path: /config
              readOnly: false
    transcode:
      type: emptyDir
      advancedMounts:
        main:
          main:
            - path: /transcode
              readOnly: false
    media:
      existingClaim: plex-nfs-storage
      advancedMounts:
        main:
          main:
            - path: /mnt/store
              readOnly: true
