apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: site-saralebens-cloudflared
  labels:
    app.kubernetes.io/instance: site-saralebens
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/version: 2026.5.2
    helm.sh/chart: cloudflared-3.3.3
  namespace: site-saralebens
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - site-saralebens
  selector:
    matchLabels:
      app.kubernetes.io/instance: site-saralebens
      app.kubernetes.io/name: cloudflared
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
      scrapeTimeout: 10s
