harbor:
  expose:
    type: route
    tls:
      enabled: false
    route:
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway
          namespace: traefik
      hosts:
        - harbor.alexlebens.net
  externalURL: https://harbor.alexlebens.net
  persistence:
    enabled: true
    persistentVolumeClaim:
      registry:
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 100Gi
  existingSecretAdminPassword: harbor-secret
  existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
  ipFamily:
    ipv6:
      enabled: false
  updateStrategy:
    type: Recreate
  existingSecretSecretKey: harbor-secret
  enableMigrateHelmHook: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  cache:
    enabled: true
  portal:
    image:
      repository: ghcr.io/goharbor/harbor-portal
      tag: v2.15.0@sha256:541d5fa95bf77240d46a438f86245cdfd6afa6dd7fdd0cf4dd4c905af6a980b1
    replicas: 2
  core:
    image:
      repository: ghcr.io/goharbor/harbor-core
      tag: v2.15.0@sha256:32a13f6693a278261e9c9cb7eb606c5e2aa021308ae44fdc73225755048500a8
    replicas: 2
    existingSecret: harbor-secret
    secretName: harbor-secret
    existingXsrfSecret: harbor-secret
  jobservice:
    image:
      repository: ghcr.io/goharbor/harbor-jobservice
      tag: v2.15.0@sha256:a22c7cccba4673b26ffb96f5c37971d85d879dd837bc82448e01c0170b68cf28
    replicas: 2
    jobLoggers:
      - stdout
    existingSecret: harbor-secret
  registry:
    registry:
      image:
        repository: goharbor/registry-photon
        tag: v2.15.0@sha256:beb49fd16cf0906c04a2bf51a22f7210289e7cc2ae43a733e2a0364380aceae6
    controller:
      image:
        repository: ghcr.io/goharbor/harbor-registryctl
        tag: v2.15.0@sha256:463172f71d3a1e8d4f9e3b4e687a447f41fbc3126316d8c150dba04a903bbc47
    existingSecret: harbor-secret
    relativeurls: true
    credentials:
      existingSecret: harbor-secret
    upload_purging:
      age: 72h
  trivy:
    enabled: true
    image:
      repository: ghcr.io/goharbor/trivy-adapter-photon
      tag: v2.15.0@sha256:6fd6de9cfbbb04cb1d94722cfa01cf71b8994d3f9e7891d3b03a89a7536480ba
  database:
    type: external
    external:
      host: harbor-postgresql-18-cluster-rw
      port: "5432"
      username: app
      coreDatabase: app
      existingSecret: harbor-postgresql-18-cluster-app
  redis:
    type: external
    external:
      addr: harbor-valkey.harbor:6379
  exporter:
    image:
      repository: ghcr.io/goharbor/harbor-exporter
      tag: v2.15.0@sha256:ad065e4e1a0ee900a0bb1a03d57028ed4b51dc04933f5c1cb5c4aee301a72ddb
    replicas: 2
postgres-18-cluster:
  mode: recovery
  recovery:
    method: objectStore
    objectStore:
      index: 2
  backup:
    objectStore:
      - name: garage-local
        index: 2
        destinationBucket: postgres-backups
        externalSecretCredentialPath: /garage/home-infra/postgres-backups
        isWALArchiver: true
    scheduledBackups:
      - name: live-backup
        suspend: false
        immediate: true
        schedule: "0 35 14 * * *"
        backupName: garage-local
valkey:
  valkey:
    resources:
      requests:
        memory: 30Mi
