apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-encryption
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pocket-id-encryption
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: key
      remoteRef:
        key: /cl01tl/pocket-id/key
        property: key

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-s3
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pocket-id-s3
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: access-key
      remoteRef:
        key: /garage/home-infra/pocket-id-assets
        property: ACCESS_KEY_ID
    - secretKey: secret-key
      remoteRef:
        key: /garage/home-infra/pocket-id-assets
        property: ACCESS_SECRET_KEY

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-alexlebens-user-info
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pocket-id-alexlebens-user-info
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: username
      remoteRef:
        key: /cl01tl/pocket-id/users/alexlebens
        property: username
    - secretKey: firstName
      remoteRef:
        key: /cl01tl/pocket-id/users/alexlebens
        property: firstName
    - secretKey: lastName
      remoteRef:
        key: /cl01tl/pocket-id/users/alexlebens
        property: lastName
    - secretKey: email
      remoteRef:
        key: /cl01tl/pocket-id/users/alexlebens
        property: email
    - secretKey: displayName
      remoteRef:
        key: /cl01tl/pocket-id/users/alexlebens
        property: displayName

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-andrewlebens-user-info
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pocket-id-andrewlebens-user-info
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: username
      remoteRef:
        key: /cl01tl/pocket-id/users/andrewlebens
        property: username
    - secretKey: firstName
      remoteRef:
        key: /cl01tl/pocket-id/users/andrewlebens
        property: firstName
    - secretKey: lastName
      remoteRef:
        key: /cl01tl/pocket-id/users/andrewlebens
        property: lastName
    - secretKey: email
      remoteRef:
        key: /cl01tl/pocket-id/users/andrewlebens
        property: email
    - secretKey: displayName
      remoteRef:
        key: /cl01tl/pocket-id/users/andrewlebens
        property: displayName
