apiVersion: v2
name: loki
version: 1.0.0
description: Loki
keywords:
  - loki
  - logs
home: https://docs.alexlebens.dev/applications/loki/
sources:
  - https://github.com/grafana/loki
  - https://github.com/grafana/alloy
  - https://github.com/grafana-community/helm-charts/tree/main/charts/loki
  - https://github.com/grafana/alloy/tree/main/operations/helm/charts/alloy
maintainers:
  - name: alexlebens
dependencies:
  - name: loki
    version: 13.7.2
    repository: oci://ghcr.io/grafana-community/helm-charts
  - name: alloy
    version: 1.8.1
    repository: https://grafana.github.io/helm-charts
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/loki.png
# renovate: datasource=github-releases depName=grafana/loki
appVersion: 3.7.2
