apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparkyfitness-oidc-authentik
  namespace: sparkyfitness
  labels:
    app.kubernetes.io/name: sparkyfitness-oidc-authentik
    app.kubernetes.io/instance: sparkyfitness
    app.kubernetes.io/part-of: sparkyfitness
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: client_id
      remoteRef:
        key: /cl01tl/authentik/oidc/sparkyfitness
        property: client
    - secretKey: client_secret
      remoteRef:
        key: /cl01tl/authentik/oidc/sparkyfitness
        property: secret
