apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparkyfitness-oidc-secret
  namespace: sparkyfitness
  labels:
    app.kubernetes.io/name: sparkyfitness-oidc-secret
    app.kubernetes.io/instance: sparkyfitness
    app.kubernetes.io/part-of: sparkyfitness
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: client_id
      remoteRef:
        key: /authentik/oidc/sparkyfitness
        property: client
    - secretKey: client_secret
      remoteRef:
        key: /authentik/oidc/sparkyfitness
        property: secret
