apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sparkyfitness-server-backup-backup-source-local
  namespace: sparkyfitness
  labels:
    helm.sh/chart: volsync-target-backup-1.1.1
    app.kubernetes.io/instance: sparkyfitness
    app.kubernetes.io/part-of: sparkyfitness
    app.kubernetes.io/version: "1.1.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sparkyfitness-server-backup-backup-source-local
spec:
  groups:
    - name: volsync.alerts
      rules:
        - alert: VolSyncBackupPodFailed
          expr: |
            (kube_pod_container_status_last_terminated_exitcode > 0)
            * on(pod, namespace) group_left(owner_name)
            kube_pod_owner{owner_kind="Job", owner_name=~"volsync-.*"}
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "VolSync Backup Pod failed in {{ $labels.namespace }}"
            description: |
              A pod for the VolSync backup of PVC 'sparkyfitness-server-backup' failed with exit code {{ $value }}.
              Job: {{ $labels.owner_name }}
              Namespace: {{ $labels.namespace }}
