element-web:
  replicaCount: 1
  image:
    repository: ghcr.io/element-hq/element-web
    tag: v1.12.22@sha256:c93f51c0445ce48be5c2d66a61470ba51a78315c7c60a4fc0e791595b96f3a96
  defaultServer:
    url: https://matrix.alexlebens.dev
    name: alexlebens.dev
    identity_url: https://alexlebens.dev
  config:
    disable_3pid_login: true
    brand: "Alex Lebens"
    branding:
      welcome_background_url: https://web-assets.alexlebens.dev/background/background.jpg
      auth_header_logo_url: https://web-assets.alexlebens.dev/logo/logo-round.svg
    sso_redirect_options:
      immediate: true
    default_theme: dark
    default_country_code: US
  resources:
    requests:
      cpu: 1m
      memory: 10Mi
