element-web:
  replicaCount: 1
  image:
    repository: ghcr.io/element-hq/element-web
    tag: v1.12.19@sha256:0dc96e8cce840b53f2da19067d10ab64c45a9ab4dbfebc2cdc6b84922728f1f7
  defaultServer:
    url: https://matrix.alexlebens.dev
    name: alexlebens.dev
    identity_url: https://alexlebens.dev
  config:
    disable_3pid_login: true
    brand: "Alex Lebens"
    branding:
      welcome_background_url: https://web-assets-3bfcb5585cbd63dc365d32a3.nyc3.cdn.digitaloceanspaces.com/alexlebens-net/background.jpg
      auth_header_logo_url: https://web-assets-3bfcb5585cbd63dc365d32a3.nyc3.cdn.digitaloceanspaces.com/alexlebens-net/logo-new-round.png
    sso_redirect_options:
      immediate: true
    default_theme: dark
    default_country_code: US
  resources:
    requests:
      cpu: 1m
      memory: 10Mi
