apiVersion: v2
name: memos
version: 1.0.0
description: Memos
keywords:
  - memos
  - notes
home: https://docs.alexlebens.dev/Applications/cl01tl/memos/
sources:
  - https://github.com/usememos/memos
  - https://hub.docker.com/r/neosmemo/memos
  - https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/pocket-id-client
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/cloudflared
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/postgres-cluster
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/garage-bucket
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/common-helpers
maintainers:
  - name: alexlebens
dependencies:
  - name: app-template
    alias: memos
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 5.2.1
  - name: pocket-id-client
    repository: oci://harbor.alexlebens.dev/helm-charts
    version: 0.2.5
  - name: cloudflared
    repository: oci://harbor.alexlebens.dev/helm-charts
    version: 4.5.5
  - name: postgres-cluster
    alias: postgres-18-cluster
    repository: oci://harbor.alexlebens.dev/helm-charts
    version: 8.4.3
  - name: garage-bucket
    alias: garage-bucket-memos-assets
    repository: oci://harbor.alexlebens.dev/helm-charts
    version: 0.4.4
  - name: common-helpers
    repository: oci://harbor.alexlebens.dev/helm-charts
    version: 0.6.0
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/memos.png
# renovate: datasource=docker depName=neosmemo/memos
appVersion: 0.31.0
