apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-nfs-storage
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: qbittorrent-nfs-storage
    {{- include "custom.labels" . | nindent 4 }}
spec:
  volumeName: qbittorrent-nfs-storage
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
