apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: qbittorrent
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: qbittorrent
    {{- include "custom.labels" . | nindent 4 }}
spec:
  name: "qBittorrent"
  launchUrl: https://qbittorrent.alexlebens.net
  description: "An open-source BitTorrent client."
  callbackUrls:
    - https://qbittorrent.alexlebens.net/oauth2/callback
  pkceEnabled: true
  skipConsent: true
  allowedUserGroups:
    - name: admin
      namespace: pocket-id-operator
  clientID: 2C3D83D2-C0CF-4301-B16B-F96D09C030BA
  clientSecretRef:
    name: qbittorrent-oauth-proxy
    key: OAUTH2_PROXY_CLIENT_SECRET
  logo:
    logoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/qbittorrent.webp
    darkLogoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/qbittorrent.webp

---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: qui
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: qui
    {{- include "custom.labels" . | nindent 4 }}
spec:
  name: "qUI"
  launchUrl: https://qui.alexlebens.net
  description: "A modern web-ui for qBittorrent."
  callbackUrls:
    - https://qui.alexlebens.net/api/auth/oidc/callback
  pkceEnabled: false
  skipConsent: true
  allowedUserGroups:
    - name: admin
      namespace: pocket-id-operator
  clientID: 26F8DA12-1DE7-4BA3-ACC6-B704ABF0B388
  clientSecretRef:
    name: qui-oidc-secret
    key: clientSecret
  logo:
    logoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/qui.webp
    darkLogoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/qui.webp
