apiVersion: v2
name: frigate
version: 1.0.0
description: Frigate NVR
keywords:
  - frigate
  - video
  - cameras
home: https://docs.alexlebens.dev/Applications/frigate/
sources:
  - https://frigate.video/
  - https://github.com/blakeblackshear/frigate
  - https://github.com/blakeblackshear/frigate/pkgs/container/frigate
  - https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/common-helpers
maintainers:
  - name: alexlebens
dependencies:
  - name: app-template
    alias: frigate
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 5.1.0
  - name: common-helpers
    repository: oci://harbor.alexlebens.net/helm-charts
    version: 0.4.1
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/frigate.png
# renovate: datasource=github-releases depName=blakeblackshear/frigate
appVersion: 0.17.2
