apiVersion: v2
name: frigate
version: 1.0.0
description: Frigate NVR
keywords:
  - frigate
  - video
  - cameras
home: https://docs.alexlebens.dev/applications/frigate/
sources:
  - https://frigate.video/
  - https://github.com/blakeblackshear/frigate
  - https://github.com/blakeblackshear/frigate/pkgs/container/frigate
  - https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
maintainers:
  - name: alexlebens
dependencies:
  - name: app-template
    alias: frigate
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 5.0.1
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/frigate.png
# renovate: datasource=github-releases depName=blakeblackshear/frigate
appVersion: 0.17.1
