{
 "title": "Garage",
 "tags": [
  "platform",
  "storage",
  "s3"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Local",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_healthy{job=\"garage-main\"}"
    }
   ]
  },
  {
   "title": "Cluster Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_available{job=\"garage-main\"}"
    }
   ]
  },
  {
   "title": "Compression (local)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "block_compression_level{job=\"garage-main\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data (local)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "garage_local_disk_total{job=\"garage-main\", volume=\"data\"}",
     "legendFormat": "Data"
    },
    {
     "expr": "garage_local_disk_avail{job=\"garage-main\", volume=\"data\"}",
     "legendFormat": "Data Available"
    }
   ]
  },
  {
   "title": "Metadata (local)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "garage_local_disk_total{job=\"garage-main\", volume=\"metadata\"}",
     "legendFormat": "Metadata"
    },
    {
     "expr": "garage_local_disk_avail{job=\"garage-main\", volume=\"metadata\"}",
     "legendFormat": "Metadata Available"
    }
   ]
  },
  {
   "title": "Block I/O (local)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "block_bytes_read{job=\"garage-main\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "block_bytes_written{job=\"garage-main\"}",
     "legendFormat": "Written"
    }
   ]
  },
  {
   "title": "Remote",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_healthy{job=\"garage\"}"
    }
   ]
  },
  {
   "title": "Cluster Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_available{job=\"garage\"}"
    }
   ]
  },
  {
   "title": "Compression (remote)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "block_compression_level{job=\"garage\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local Disk (remote)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "garage_local_disk_total{job=\"garage\", volume=\"data\"}",
     "legendFormat": "Data"
    },
    {
     "expr": "garage_local_disk_total{job=\"garage\", volume=\"metadata\"}",
     "legendFormat": "Metadata"
    },
    {
     "expr": "garage_local_disk_avail{job=\"garage\", volume=\"data\"}",
     "legendFormat": "Data Available"
    },
    {
     "expr": "garage_local_disk_avail{job=\"garage\", volume=\"metadata\"}",
     "legendFormat": "Metadata Available"
    }
   ]
  },
  {
   "title": "Block I/O (remote)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "block_bytes_read{job=\"garage\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "block_bytes_written{job=\"garage\"}",
     "legendFormat": "Written"
    }
   ]
  }
 ]
}