apiVersion: v2
name: unpoller
version: 1.0.0
description: Unpoller
keywords:
  - unpoller
  - ubiquiti
  - metrics
home: https://docs.alexlebens.dev/Applications/unpoller/
sources:
  - https://github.com/unpoller/unpoller
  - https://github.com/unpoller/unpoller/pkgs/container/unpoller
  - https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template/values.yaml
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/common-helpers
maintainers:
  - name: alexlebens
dependencies:
  - name: app-template
    alias: unpoller
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 5.1.0
  - name: common-helpers
    repository: oci://harbor.alexlebens.dev/helm-charts
    version: 0.4.1
icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/ubiquiti-unifi.png
# renovate: datasource=github-releases depName=unpoller/unpoller
appVersion: v5.2.0
