unpoller:
  controllers:
    main:
      type: deployment
      strategy: Recreate
      containers:
        main:
          image:
            repository: ghcr.io/unpoller/unpoller
            tag: v5.0.1@sha256:153de67099595e54ce1f5eb6e36f7308ce658c36626ed3546a920fc306a2d154
          env:
            - name: UP_UNIFI_CONTROLLER_0_SAVE_ALARMS
              value: "true"
            - name: UP_UNIFI_CONTROLLER_0_SAVE_ANOMALIES
              value: "false"
            - name: UP_UNIFI_CONTROLLER_0_SAVE_DPI
              value: "false"
            - name: UP_UNIFI_CONTROLLER_0_SAVE_EVENTS
              value: "false"
            - name: UP_UNIFI_CONTROLLER_0_SAVE_IDS
              value: "true"
            - name: UP_UNIFI_CONTROLLER_0_SAVE_SITES
              value: "true"
            - name: UP_UNIFI_CONTROLLER_0_URL
              value: https://unifi.alexlebens.net/
            - name: UP_UNIFI_CONTROLLER_0_VERIFY_SSL
              value: "false"
            - name: UP_INFLUXDB_DISABLE
              value: "true"
            - name: UP_PROMETHEUS_HTTP_LISTEN
              value: 0.0.0.0:9130
            - name: UP_PROMETHEUS_NAMESPACE
              value: unpoller
            - name: UP_POLLER_DEBUG
              value: "false"
            - name: UP_POLLER_QUIET
              value: "false"
          envFrom:
            - secretRef:
                name: unpoller-unifi-credentials
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /metrics
                  port: 9130
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /metrics
                  port: 9130
  service:
    main:
      ports:
        metrics:
          port: 9130
  serviceMonitor:
    main:
      selector:
        matchLabels:
          app.kubernetes.io/name: unpoller
          app.kubernetes.io/instance: unpoller
      serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
      endpoints:
        - port: metrics
          interval: 5m
