apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-oauth-proxy
  namespace: kube-prometheus-stack
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: OAUTH2_PROXY_CLIENT_ID
      remoteRef:
        key: /cl01tl/pocket-id/oidc/alertmanager
        property: clientId
    - secretKey: OAUTH2_PROXY_CLIENT_SECRET
      remoteRef:
        key: /cl01tl/pocket-id/oidc/alertmanager
        property: clientSecret
    - secretKey: OAUTH2_PROXY_COOKIE_SECRET
      remoteRef:
        key: /cl01tl/pocket-id/oidc/alertmanager
        property: cookie
    - secretKey: OAUTH2_PROXY_OIDC_ISSUER_URL
      remoteRef:
        key: /cl01tl/pocket-id/config
        property: issuer-url
