apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: prometheus
  namespace: kube-prometheus-stack
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/part-of: kube-prometheus-stack
spec:
  name: "Prometheus"
  launchUrl: https://prometheus.alexlebens.net
  description: "A systems and service monitoring system using standard metrics formats."
  callbackUrls:
    - https://prometheus.alexlebens.net/oauth2/callback
  pkceEnabled: true
  skipConsent: true
  allowedUserGroups:
    - name: platform-admin
      namespace: pocket-id-operator
  clientID: 82DD7A6F-288E-4684-BA11-17A727930943
  clientSecretRef:
    name: prometheus-oauth-proxy
    key: OAUTH2_PROXY_CLIENT_SECRET
  logo:
    logoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/prometheus.webp
