apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-ps08rp-http-401-insecure
  namespace: kube-prometheus-stack
  labels:
    app.kubernetes.io/name: blackbox-ps08rp-http-401-insecure
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/part-of: kube-prometheus-stack
spec:
  prober:
    url: ps08rp.alexlebens.dev:9115
  module: http_401_insecure
  targets:
    staticConfig:
      static:
        - https://cl01tl.alexlebens.dev:6443
        - https://cl01tl-api.alexlebens.dev:6443
        - https://cl01tl-endpoint.alexlebens.dev:10250
