apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-ps10rp-http-2xx
  namespace: kube-prometheus-stack
  labels:
    app.kubernetes.io/name: blackbox-ps10rp-http-2xx
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/part-of: kube-prometheus-stack
spec:
  prober:
    url: blackbox-exporter-ps10rp.boreal-beaufort.ts.net:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - https://www.lebens-home.net
        - https://gitea.lebens-home.net
        - http://printer.lebens-home.net
