apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-prometheus-stack-prometheus-blackbox-exporter
  labels:
    helm.sh/chart: prometheus-blackbox-exporter-11.15.1
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/version: "v0.28.0"
    app.kubernetes.io/managed-by: Helm
spec:
  groups:
    - name: prometheus-blackbox-exporter
      rules:
        - alert: EndpointDown
          annotations:
            description: Failed to probe {{ $labels.instance }} for more than 30 seconds.
            summary: Endpoint {{ $labels.instance }} is down
          expr: max by (instance, target) (probe_success) == 0
          for: 60s
          labels:
            severity: critical
        - alert: EndpointHighLatency
          annotations:
            description: Endpoint {{ $labels.instance }} is taking longer than 5 seconds to respond.
            summary: Endpoint {{ $labels.instance }} is slow
          expr: max by (instance, target) (probe_duration_seconds) > 5
          for: 2m
          labels:
            severity: warning
        - alert: SSLCertificateExpiringSoon
          annotations:
            description: The SSL certificate for {{ $labels.instance }} will expire in less than 7 days.
            summary: SSL Certificate for {{ $labels.instance }} expires soon
          expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 7
          for: 1h
          labels:
            severity: warning
