apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: external-alloy-http
  namespace: kube-prometheus-stack
  labels:
    app.kubernetes.io/name: external-alloy-http
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/part-of: kube-prometheus-stack
spec:
  staticConfigs:
    - labels:
        job: external-alloy
      targets:
        - ps08rp.alexlebens.dev:12345
        - ps09rp.alexlebens.dev:12345
  metricsPath: /metrics
  scheme: HTTP
