apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-prometheus-am-confg
  namespace: kube-prometheus-stack
  labels:
    app: kube-prometheus-stack-prometheus-am-confg
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/version: "88.3.0"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-88.3.0
    release: "kube-prometheus-stack"
    heritage: "Helm"
data:
  additional-alertmanager-configs.yaml: "LSBhcGlWZXJzaW9uOiB2MgogIHBhdGhfcHJlZml4OiAvCiAgc2NoZW1lOiBodHRwCiAgc3RhdGljX2NvbmZpZ3M6CiAgLSB0YXJnZXRzOgogICAgLSBrdWJlLXByb21ldGhldXMtc3RhY2stYWxlcnRtYW5hZ2VyLmt1YmUtcHJvbWV0aGV1cy1zdGFjay5zdmM6OTA5Mw=="
