apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: server-host-records
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: server-host-records
    {{- include "custom.labels" . | nindent 4 }}
spec:
  endpoints:
    # Unifi Gateway
    - dnsName: nw01un{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: A
      targets:
        - 192.168.1.1

    # Synology Web
    - dnsName: ps02sn{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: A
      targets:
        - 10.232.1.61

    # Synology Storage
    - dnsName: ps02sn-bond{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: A
      targets:
        - 10.232.1.64

    # Raspberry Pi DNS Node
    - dnsName: ps08rp{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: A
      targets:
        - 10.232.1.51

    # Raspberry Pi DNS Node
    - dnsName: ps09rp{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: A
      targets:
        - 10.232.1.52

    # HD Homerun
    - dnsName: dv01hr{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: A
      targets:
        - 10.232.1.72

    # Pi KVM
    - dnsName: dv02kv{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: A
      targets:
        - 10.232.1.71

    # Desktop
    - dnsName: pd05wd{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: A
      targets:
        - 10.230.0.115

    # Laptop
    - dnsName: pl02mc{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: A
      targets:
        - 10.230.0.105

---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: server-host-common-names
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: server-host-common-names
    {{- include "custom.labels" . | nindent 4 }}
spec:
  endpoints:
    # Unifi Gateway
    - dnsName: unifi{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: CNAME
      targets:
        - nw01un{{ include "custom.domain" . }}

    # Synology Web
    - dnsName: synology{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: CNAME
      targets:
        - ps02sn{{ include "custom.domain" . }}

    # Synology Storage
    - dnsName: synology-bond{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: CNAME
      targets:
        - ps02sn-bond{{ include "custom.domain" . }}

    # HD Homerun
    - dnsName: hdhr{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: CNAME
      targets:
        - dv01hr{{ include "custom.domain" . }}

    # PiKVM
    - dnsName: pikvm{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: CNAME
      targets:
        - dv02kv{{ include "custom.domain" . }}

---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: dns-common-names
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: dns-common-names
    {{- include "custom.labels" . | nindent 4 }}
spec:
  endpoints:
    # DNS Server 1
    - dnsName: dns1{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: CNAME
      targets:
        - blocky{{ include "custom.domain" . }}

    # DNS Server 2
    - dnsName: dns2{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: CNAME
      targets:
        - ps08rp{{ include "custom.domain" . }}

    # DNS Server 3
    - dnsName: dns3{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: CNAME
      targets:
        - ps09rp{{ include "custom.domain" . }}

---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: iot-device-records
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: iot-device-records
    {{- include "custom.labels" . | nindent 4 }}
spec:
  endpoints:
    # Airgradient
    - dnsName: it01ag{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: A
      targets:
        - 10.232.1.83

    # Phillips Hue
    - dnsName: it02ph{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: A
      targets:
        - 10.232.1.85

    # TubesZB ZigBee
    - dnsName: it03tb{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: A
      targets:
        - 10.232.1.81

    # TubesZB Z-Wave
    - dnsName: it04tb{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: A
      targets:
        - 10.232.1.82

    # Shelly Plug
    - dnsName: it05sp{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: A
      targets:
        - 10.230.0.100

    # Tapo C200
    - dnsName: it06cm{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: A
      targets:
        - 10.230.0.16

---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: iot-device-common-names
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: iot-device-common-names
    {{- include "custom.labels" . | nindent 4 }}
spec:
  endpoints:
    # Airgradient
    - dnsName: airgradient{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: CNAME
      targets:
        - it01ag{{ include "custom.domain" . }}

---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cluster-service-records
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cluster-service-records
    {{- include "custom.labels" . | nindent 4 }}
spec:
  endpoints:
    # Kubernetes Cluster Nodes
    - dnsName: cl01tl{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: A
      targets:
        - 10.232.1.11
        - 10.232.1.12
        - 10.232.1.13

    # Kubernetes API Server
    - dnsName: cl01tl-api{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: A
      targets:
        - 10.232.1.11
        - 10.232.1.12
        - 10.232.1.13

    # Kubernetes Endpoints
    - dnsName: cl01tl-endpoint{{ include "custom.domain" . }}
      recordTTL: 180
      recordType: A
      targets:
        - 10.232.1.21
        - 10.232.1.22
        - 10.232.1.23
