apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-unifi-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: external-dns-unifi-secret
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: api-key
      remoteRef:
        key: /unifi/users/cl01tl
        property: api-key
