apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "events-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "events-{{ .Release.Name }}"
    {{- include "custom.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "events-{{ .Release.Name }}"
subjects:
  - kind: ServiceAccount
    name: kubelet-serving-cert-approver
    namespace: {{ .Release.Name }}
