apiVersion: v1
kind: ConfigMap
metadata:
  name: memos-general-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: memos-general-config
    {{- include "custom.labels" . | nindent 4 }}
data:
  memos-instance-setting-general.json: |
    {
      "disallowPasswordSignIn": true
    }
  memos-instance-setting-notification.json: |
    {
      "key": "NOTIFICATION",
      "notificationSetting": {
        "smtp": {
          "host": "postfix.postfix.svc.cluster.local",
          "port": 587,
          "user": "",
          "password": "",
          "fromAddress": "memos@alexlebens.dev",
          "enable": true
        }
      }
    }
