apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-a-oidc-secret
  namespace: garage-a
  labels:
    app.kubernetes.io/name: garage-a-oidc-secret
    helm.sh/chart: pocket-id-client-0.4.1
    app.kubernetes.io/instance: garage-a
    app.kubernetes.io/part-of: garage-a
    app.kubernetes.io/managed-by: Helm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: clientId
      remoteRef:
        key: /cl01tl/pocket-id/oidc/garage-a
        property: clientId
    - secretKey: clientSecret
      remoteRef:
        key: /cl01tl/pocket-id/oidc/garage-a
        property: clientSecret
