apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: garage-ui
  namespace: garage-a
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Object Storage (A)"
    gethomepage.dev/description: "Garage"
    gethomepage.dev/group: "Storage"
    gethomepage.dev/icon: "sh-garage.webp"
    gethomepage.dev/siteMonitor: "http://garage-ui.garage-a:80"
    gethomepage.dev/statusStyle: "dot"
    gethomepage.dev/weight: "100"
  labels:
    app.kubernetes.io/name: garage-ui
    app.kubernetes.io/instance: garage-a
    app.kubernetes.io/part-of: garage-a
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: traefik
  hostnames:
    - "a-ui.s3.alexlebens.dev"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: garage-ui
          port: 80
          weight: 1
