apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: garage-a
  namespace: garage-a
  labels:
    app.kubernetes.io/name: garage-a
    helm.sh/chart: pocket-id-client-0.4.1
    app.kubernetes.io/instance: garage-a
    app.kubernetes.io/part-of: garage-a
    app.kubernetes.io/managed-by: Helm
spec:
  name: "Garage Cluster (A)"
  launchUrl: https://a-ui.s3.alexlebens.dev
  description: "An S3-compatible object storage service running on ps02sn."
  callbackUrls:
    - https://a-ui.s3.alexlebens.dev/auth/oidc/callback
    - https://a-ui.s3.alexlebens.dev/api/v1/auth/oidc/callback
  pkceEnabled: false
  skipConsent: true
  allowedUserGroups:
    - name: platform-admin
      namespace: pocket-id-operator
  clientID: 8C33EB93-937D-4E94-AE16-9B7B9659C4D9
  clientSecretRef:
    name: garage-a-oidc-secret
    key: clientSecret
  logo:
    logoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/garage.webp
