grafana-operator:
  image:
    registry: ghcr.io
    repository: grafana/grafana-operator
    # renovate: datasource=docker depName=ghcr.io/grafana/grafana-operator
    tag: v5.24.0@sha256:e72d11ac579a000fe0ddcc0c3341a5103a1c93a28fbc394dc7c7009ed071d1a7
  replicas: 2
  resources:
    requests:
      cpu: 1m
      memory: 50Mi
  serviceMonitor:
    enabled: true
postgres-18-cluster:
  mode: recovery
  recovery:
    objectStore:
      index: 2
  backup:
    objectStore:
      index: 2
      endpointURL: http://garage-cluster-a.garage-operator.svc.cluster.local:3900
    scheduledBackups:
      suspend: false
      schedule: "0 30 14 * * *"
valkey-unified-alerting:
  valkey:
    nameOverride: valkey-unified-alerting
valkey-remote-cache:
  valkey:
    nameOverride: valkey-remote-cache
