apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-testing-meilisearch-key
  namespace: jellyfin-testing
  labels:
    app.kubernetes.io/name: jellyfin-testing-meilisearch-key
    app.kubernetes.io/instance: jellyfin-testing
    app.kubernetes.io/part-of: jellyfin-testing
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: /cl01tl/jellyfin/meilisearch
        property: master-key
