kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-testing-config
  labels:
    app.kubernetes.io/instance: jellyfin-testing
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jellyfin-testing
    helm.sh/chart: jellyfin-testing-5.0.1
  namespace: jellyfin-testing
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
  storageClassName: "local-path"
