apiVersion: v1
kind: ServiceAccount
metadata:
  name: jellyfin-testing
  labels:
    helm.sh/chart: jellyfin-testing-3.2.0
    app.kubernetes.io/name: jellyfin-testing
    app.kubernetes.io/instance: jellyfin-testing
    app.kubernetes.io/version: "10.11.8"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
