ntfy:
  controllers:
    main:
      type: deployment
      strategy: Recreate
      containers:
        main:
          image:
            repository: binwiederhier/ntfy
            tag: v2.27.0@sha256:f2419f405127afa868f10985c1a41449e673477cee1eb19994339a5ae8b592e7
          args: ["serve"]
          env:
            - name: TZ
              value: America/Chicago
            - name: NTFY_BASE_URL
              value: https://ntfy.alexlebens.dev
            - name: NTFY_LISTEN_HTTP
              value: :80
            - name: NTFY_CACHE_DURATION
              value: 36h
            - name: NTFY_BEHIND_PROXY
              value: true
            - name: NTFY_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ntfy-postgresql-18-cluster-app
                  key: uri
            - name: NTFY_ATTACHMENT_CACHE_DIR
              valueFrom:
                secretKeyRef:
                  name: ntfy-config
                  key: attachment-cache-dir
            - name: NTFY_ATTACHMENT_TOTAL_SIZE_LIMIT
              value: 10G
            - name: NTFY_ATTACHMENT_FILE_SIZE_LIMIT
              value: 150M
            - name: NTFY_ATTACHMENT_EXPIRY_DURATION
              value: 72h
            - name: NTFY_ENABLE_SIGNUP
              value: false
            - name: NTFY_ENABLE_LOGIN
              value: true
            - name: NTFY_ENABLE_RESERVATIONS
              value: false
            - name: NTFY_AUTH_DEFAULT_ACCESS
              value: deny-all
            - name: NTFY_METRICS_LISTEN_HTTP
              value: :9090
            - name: NTFY_LOG_LEVEL
              value: info
          resources:
            requests:
              cpu: 10m
              memory: 40Mi
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /v1/health
                  port: 80
                initialDelaySeconds: 60
                periodSeconds: 60
                successThreshold: 1
                timeoutSeconds: 30
  service:
    main:
      ports:
        http:
          port: 80
        metrics:
          port: 9090
  serviceMonitor:
    main:
      selector:
        matchLabels:
          app.kubernetes.io/name: ntfy
          app.kubernetes.io/instance: ntfy
      serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
      endpoints:
        - port: metrics
  route:
    main:
      kind: HTTPRoute
      parentRefs:
        - name: traefik-gateway
          namespace: traefik
      hostnames:
        - ntfy.alexlebens.net
      rules:
        - backendRefs:
            - name: ntfy
              port: 80
  configMaps:
    templates:
      enabled: true
      forceRename: ntfy-templates
      data:
        harbor.yml: |
          title: "Harbor: {{ `{{ .type }}` }}"
          message: "Triggered by: {{ `{{ .operator }}` }}\nRepository: {{ `{{ .event_data.repository.repo_full_name }}` }}"
  persistence:
    templates:
      type: configMap
      name: ntfy-templates
      advancedMounts:
        main:
          main:
            - path: /etc/ntfy/templates
              readOnly: true
cloudflared:
  probe:
    enabled: true
    targetUrl: https://ntfy.alexlebens.dev
postgres-18-cluster:
  mode: recovery
  recovery:
    objectStore:
      index: 1
  backup:
    objectStore:
      index: 1
      endpointURL: http://garage-cluster-a.garage-operator.svc.cluster.local:3900
    scheduledBackups:
      suspend: false
      schedule: "0 15 14 * * *"
garage-bucket-ntfy-assets:
  bucketName: ntfy-assets
  backups:
    primary:
      enabled: true
      cronJob:
        suspend: true
        schedule: 0 0 * * *
      destination:
        bucketName: ntfy-assets
