apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-profile
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: site-profile
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: site-profile
    helm.sh/chart: site-profile-5.0.1
  namespace: site-profile
spec:
  revisionHistoryLimit: 3
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/name: site-profile
      app.kubernetes.io/instance: site-profile
  template:
    metadata:
      labels:
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: site-profile
        app.kubernetes.io/name: site-profile
    spec:
      enableServiceLinks: false
      serviceAccountName: site-profile
      automountServiceAccountToken: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - image: harbor.alexlebens.net/images/site-profile:3.22.0@sha256:09b0b8635385eb4a18457e0b5fc6e2396d456bf964e54dd073d3524fa29afbf0
          name: main
          resources:
            requests:
              cpu: 10m
              memory: 60Mi
