apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-profile
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: site-profile
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: site-profile
    helm.sh/chart: site-profile-4.6.2
  namespace: site-profile
spec:
  revisionHistoryLimit: 3
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/name: site-profile
      app.kubernetes.io/instance: site-profile
  template:
    metadata:
      labels:
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: site-profile
        app.kubernetes.io/name: site-profile
    spec:
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - image: harbor.alexlebens.net/images/site-profile:3.18.2@sha256:8deb9624b2564fabd1f5cc6822306fd198b245858317be2d9ab4ca044ae3ded5
          name: main
          resources:
            requests:
              cpu: 10m
              memory: 60Mi
