apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: site-profile-cloudflared
  labels:
    app.kubernetes.io/instance: site-profile
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/version: 2026.6.1
    helm.sh/chart: cloudflared-3.4.1
  namespace: site-profile
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - site-profile
  selector:
    matchLabels:
      app.kubernetes.io/instance: site-profile
      app.kubernetes.io/name: cloudflared
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
      scrapeTimeout: 10s
