apiVersion: v1
kind: ConfigMap
metadata:
  name: librechat-config
  labels:
    app.kubernetes.io/instance: librechat
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: librechat
    helm.sh/chart: librechat-5.1.0
  namespace: librechat
data:
  librechat.yaml: |
    version: 1.2.1
    cache: true
    fileStrategy: "s3"

    webSearch:
      searchProvider: "searxng"
      searxngInstanceUrl: "http://searxng-api.searxng.svc.cluster.local:8080"
      searxngSearchOptions:
        engines: "google,bing,brave,startpage,qwant"
        language: "en"
      allowedAddresses:
        - "searxng-api.searxng.svc.cluster.local:8080"
        - "searxng-api.searxng.svc.cluster.local"
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"

    mcpSettings:
      allowedAddresses:
        - "n8n-main.n8n.svc.cluster.local:5678"
        - "trek.alexlebens.dev:443"

    endpoints:
      custom:
        - name: "LiteLLM"
          apiKey: "${LITELLM_MASTER_KEY}"
          baseURL: "http://librechat-litellm:4000/v1"
          models:
            default: ["gemini-3.5-flash-lite", "gemini-3.7-flash", "gemini-3.8-flash"]
            fetch: true
          titleConvo: true
          titleModel: "gemini-3.5-flash-lite"
          modelDisplayLabel: "LiteLLM"

        - name: "Ollama"
          apiKey: "${OLLAMA_API_KEY}"
          baseURL: "https://ollama-pd05wd.boreal-beaufort.ts.net/v1"
          models:
            default: ["qwen3:14b", "gemma4:e4b", "gemma4:12b"]
            fetch: true
          titleConvo: true
          titleModel: "current_model"
          modelDisplayLabel: "Ollama"

    mcpServers:
      paperless:
        type: sse
        url: "http://n8n-main.n8n.svc.cluster.local:5678/mcp/paperless"
        timeout: 60000

      trek:
        type: "stdio"
        command: "npx"
        args:
          - "-y"
          - "mcp-remote"
          - "https://trek.alexlebens.dev/mcp"
          - "3334"
          - "--static-oauth-client-info"
          - '{"client_id": "${TREK_MCP_CLIENT_ID}", "client_secret": "${TREK_MCP_CLIENT_SECRET}", "redirect_uris": ["http://localhost:3334/oauth/callback"]}'

      karakeep:
        type: stdio
        command: "npx"
        args:
          - "-y"
          - "@karakeep/mcp"
        env:
          KARAKEEP_API_ADDR: "http://karakeep.karakeep.svc.cluster.local:3000"
          KARAKEEP_API_KEY: "${KARAKEEP_API_KEY}"
