apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librechat-meilisearch-key
  namespace: librechat
  labels:
    app.kubernetes.io/name: librechat-meilisearch-key
    app.kubernetes.io/instance: librechat
    app.kubernetes.io/part-of: librechat
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: /cl01tl/librechat/meilisearch
        property: master-key
