apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: librechat-meilisearch
  namespace: librechat
  labels:
    helm.sh/chart: meilisearch-0.38.0
    app.kubernetes.io/name: meilisearch
    app.kubernetes.io/instance: librechat
    app.kubernetes.io/version: "v1.53.1"
    app.kubernetes.io/component: search-engine
    app.kubernetes.io/part-of: meilisearch
    app.kubernetes.io/managed-by: Helm
spec:
  jobLabel: librechat
  namespaceSelector:
    matchNames:
      - librechat
  selector:
    matchLabels:
      app.kubernetes.io/name: meilisearch
      app.kubernetes.io/instance: librechat
  endpoints:
    - port: http
      path: /metrics
      interval: 1m
      scrapeTimeout: 10s
      bearerTokenSecret:
        name: librechat-meilisearch-key
        key: MEILI_MASTER_KEY
