apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: postiz-temporal-web
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: postiz-temporal-web
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: traefik
  hostnames:
    - postiz-temporal-web.alexlebens.net
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - group: ''
          kind: Service
          name: postiz-temporal-web
          port: 8080
          weight: 100

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: postiz-temporal-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: postiz-temporal-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: traefik
  hostnames:
    - postiz-temporal-frontend.alexlebens.net
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - group: ''
          kind: Service
          name: postiz-temporal-frontend
          port: 7243
          weight: 100
