apiVersion: v2
name: eraser
version: 1.0.0
description: Eraser
keywords:
  - eraser
  - images
home: https://docs.alexlebens.dev/applications/eraser/
sources:
  - https://github.com/eraser-dev/eraser
  - https://github.com/eraser-dev/eraser/pkgs/container/eraser-manager
  - https://github.com/open-telemetry/opentelemetry-collector-releases/pkgs/container/opentelemetry-collector-releases%2Fopentelemetry-collector
  - https://github.com/eraser-dev/eraser/tree/main/charts/eraser
  - https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
maintainers:
  - name: alexlebens
dependencies:
  - name: eraser
    version: 1.4.1
    repository: https://eraser-dev.github.io/eraser/charts
  - name: app-template
    alias: eraser-metrics
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 4.6.2
icon: https://raw.githubusercontent.com/eraser-dev/eraser/refs/heads/main/images/eraser-logo-color-1c.png
# renovate: datasource=github-releases depName=eraser-dev/eraser
appVersion: v1.4.1
