apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kaneo-oidc-secret
  namespace: kaneo
  labels:
    app.kubernetes.io/name: kaneo-oidc-secret
    helm.sh/chart: pocket-id-client-0.4.1
    app.kubernetes.io/instance: kaneo
    app.kubernetes.io/part-of: kaneo
    app.kubernetes.io/managed-by: Helm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: clientId
      remoteRef:
        key: /cl01tl/pocket-id/oidc/kaneo
        property: clientId
    - secretKey: clientSecret
      remoteRef:
        key: /cl01tl/pocket-id/oidc/kaneo
        property: clientSecret
