apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kaneo-assets-external-rclone-ntfy
  namespace: kaneo
  labels:
    helm.sh/chart: rclone-kaneo-assets-external-0.12.5
    app.kubernetes.io/instance: kaneo
    app.kubernetes.io/part-of: kaneo
    app.kubernetes.io/version: "0.12.5"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kaneo-assets-external-rclone-ntfy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    template:
      mergePolicy: Merge
      engineVersion: v2
      data:
        ntfy-url: "{{ .url }}/{{ .topic }}"
        ntfy-token: "{{ .token }}"
  data:
    - secretKey: url
      remoteRef:
        key: /cl01tl/ntfy/config
        property: internal-endpoint
    - secretKey: topic
      remoteRef:
        key: /cl01tl/ntfy/topics
        property: rclone
    - secretKey: token
      remoteRef:
        key: /cl01tl/ntfy/users/cl01tl
        property: token
