apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kaneo-bucket-garage
  namespace: kaneo
  labels:
    app.kubernetes.io/name: kaneo-bucket-garage
    app.kubernetes.io/instance: kaneo
    app.kubernetes.io/part-of: kaneo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: S3_ACCESS_KEY_ID
      remoteRef:
        key: /garage/home-infra/kaneo-assets
        property: ACCESS_KEY_ID
    - secretKey: S3_SECRET_ACCESS_KEY
      remoteRef:
        key: /garage/home-infra/kaneo-assets
        property: ACCESS_SECRET_KEY
    - secretKey: S3_REGION
      remoteRef:
        key: /garage/home-infra/kaneo-assets
        property: ACCESS_REGION
