apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: kaneo-assets-key
  namespace: kaneo
  labels:
    app.kubernetes.io/name: kaneo-assets-key
    helm.sh/chart: garage-bucket-kaneo-assets-0.2.3
    app.kubernetes.io/instance: kaneo
    app.kubernetes.io/part-of: kaneo
    app.kubernetes.io/version: "v0.7.3"
    app.kubernetes.io/managed-by: Helm
spec:
  name: kaneo-assets-key
  clusterRef:
    name: garage-cluster-a
    namespace: garage-operator
  importKey:
    secretRef:
      name: kaneo-assets-secret
    accessKeyIdKey: AWS_ACCESS_KEY_ID
    secretAccessKeyKey: AWS_SECRET_ACCESS_KEY
  bucketPermissions:
    - bucketRef:
        name: kaneo-assets
      read: true
      write: true
      owner: true
