apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaneo
  labels:
    app.kubernetes.io/instance: kaneo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kaneo
    helm.sh/chart: kaneo-5.0.1
  namespace: kaneo
