apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kaneo-valkey
  labels:
    helm.sh/chart: valkey-0.11.0
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: kaneo
    app.kubernetes.io/version: "9.1.2"
    app.kubernetes.io/managed-by: Helm
spec:
  serviceName: kaneo-valkey-headless
  replicas: 3
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app.kubernetes.io/name: valkey
      app.kubernetes.io/instance: kaneo
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: valkey-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "ceph-block"
        resources:
          requests:
            storage: "1Gi"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: valkey
        app.kubernetes.io/instance: kaneo
      annotations:
        checksum/initconfig: "4219b4c49440088de6b6052d5860e8df"
    spec:
      automountServiceAccountToken: false
      serviceAccountName: kaneo-valkey
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: kaneo-valkey-init
          image: docker.io/valkey/valkey:9.1.2@sha256:a91d34ab33975b1054e26f1bd9995b268f7e0c507b5ded7f3d181a1a25521630
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          command: ["/scripts/init.sh"]
          env:
            - name: POD_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
          volumeMounts:
            - name: valkey-data
              mountPath: /data
            - name: scripts
              mountPath: /scripts
      containers:
        - name: kaneo-valkey
          image: docker.io/valkey/valkey:9.1.2@sha256:a91d34ab33975b1054e26f1bd9995b268f7e0c507b5ded7f3d181a1a25521630
          imagePullPolicy: IfNotPresent
          command: ["valkey-server"]
          args: ["/data/conf/valkey.conf"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          env:
            - name: POD_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
            - name: VALKEY_LOG_LEVEL
              value: "notice"
          ports:
            - name: tcp
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - valkey-cli
                - ping
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          startupProbe:
            exec:
              command:
                - valkey-cli
                - ping
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - name: valkey-data
              mountPath: /data
        - name: metrics
          image: ghcr.io/oliver006/redis_exporter:v1.90.0@sha256:a129504e65b87c54f79bc92f1afc403475e8ff646a3d7512de469904ceddf986
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: metrics
              containerPort: 9121
          startupProbe:
            tcpSocket:
              port: metrics
          livenessProbe:
            tcpSocket:
              port: metrics
          readinessProbe:
            httpGet:
              path: /
              port: metrics
          resources:
            requests:
              cpu: 1m
              memory: 10M
          env:
            - name: REDIS_ALIAS
              value: kaneo-valkey
      volumes:
        - name: scripts
          configMap:
            name: kaneo-valkey-init-scripts
            defaultMode: 0555
