apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pigallery2-mariadb-cluster-backup-secret-garage
  namespace: pigallery2
  labels:
    app.kubernetes.io/name: pigallery2-mariadb-cluster-backup-secret-garage
    app.kubernetes.io/instance: pigallery2
    app.kubernetes.io/part-of: pigallery2
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: access
      remoteRef:
        key: /garage/home-infra/mariadb-backups
        property: ACCESS_KEY_ID
    - secretKey: secret
      remoteRef:
        key: /garage/home-infra/mariadb-backups
        property: ACCESS_SECRET_KEY
