apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pigallery2-collections-nfs-storage
  namespace: pigallery2
  labels:
    app.kubernetes.io/name: pigallery2-collections-nfs-storage
    app.kubernetes.io/instance: pigallery2
    app.kubernetes.io/part-of: pigallery2
spec:
  volumeName: pigallery2-collections-nfs-storage
  storageClassName: nfs-client
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
