apiVersion: v1
kind: ServiceAccount
metadata:
  name: pigallery2
  labels:
    app.kubernetes.io/instance: pigallery2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pigallery2
    helm.sh/chart: pigallery2-5.2.1
  namespace: pigallery2
