apiVersion: v2
name: reactive-resume
version: 1.0.0
description: Reactive Resume
keywords:
  - reactive-resume
  - resume
home: https://docs.alexlebens.dev/Applications/reactive-resume/
sources:
  - https://github.com/amruthpillai/reactive-resume
  - https://hub.docker.com/r/amruthpillai/reactive-resume
  - https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/valkey
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/postgres-cluster
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/garage-bucket
maintainers:
  - name: alexlebens
dependencies:
  - name: app-template
    alias: reactive-resume
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 5.1.0
  - name: valkey
    alias: valkey
    version: 1.1.0
    repository: oci://harbor.alexlebens.net/helm-charts
  - name: postgres-cluster
    alias: postgres-18-cluster
    version: 8.4.2
    repository: oci://harbor.alexlebens.net/helm-charts
  - name: garage-bucket
    alias: garage-bucket-reactive-resume-assets
    repository: oci://harbor.alexlebens.net/helm-charts
    version: 0.3.12
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/reactive-resume.png
# renovate: datasource=github-releases depName=amruthpillai/reactive-resume
appVersion: v5.2.8
