kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: languagetool-data
  labels:
    app.kubernetes.io/instance: languagetool
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: languagetool
    helm.sh/chart: languagetool-4.6.2
  namespace: languagetool
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "ceph-block"
