apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dawarich-key
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: dawarich-key
    {{- include "dawarich.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: key
      remoteRef:
        key: /cl01tl/dawarich/key
        property: key

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dawarich-oidc-authentik
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: dawarich-oidc-authentik
    {{- include "dawarich.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: client
      remoteRef:
        key: /cl01tl/authentik/oidc/dawarich
        property: client
    - secretKey: secret
      remoteRef:
        key: /cl01tl/authentik/oidc/dawarich
        property: secret
