blog:
  global:
    fullnameOverride: blog
  controllers:
    main:
      type: deployment
      replicas: 3
      strategy: RollingUpdate
      containers:
        main:
          image:
            repository: harbor.alexlebens.net/images/blog
            tag: 3.26.0@sha256:2e9958fced1573a5d128b6695417672eb7f0c8301a1a1b284b0b0cd80197b25e
          resources:
            requests:
              cpu: 10m
              memory: 60Mi
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
          targetPort: 4321
