blog:
  global:
    fullnameOverride: blog
  controllers:
    main:
      type: deployment
      replicas: 3
      strategy: RollingUpdate
      containers:
        main:
          image:
            repository: harbor.alexlebens.net/images/blog
            tag: 3.42.1@sha256:35384fe254e1141cbe5f556c6edd2ce091fc7883fe96fcb5bce689599cabe797
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /
                  port: 4321
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /
                  port: 4321
  service:
    main:
      ports:
        http:
          port: 80
          targetPort: 4321
  route:
    main:
      kind: HTTPRoute
      parentRefs:
        - name: traefik-gateway
          namespace: traefik
      hostnames:
        - blog.alexlebens.dev
      rules:
        - backendRefs:
            - name: blog
              port: 80
cloudflared:
  probe:
    enabled: true
    targetUrl: https://www.alexlebens.dev
