blog:
  global:
    fullnameOverride: blog
  controllers:
    main:
      type: deployment
      replicas: 3
      strategy: RollingUpdate
      containers:
        main:
          image:
            repository: harbor.alexlebens.net/images/blog
            tag: 3.40.3@sha256:3c96f4b4964e58dbfb09172eb6a2ac17bb84dd37a2ab57321382a5917df60d28
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /
                  port: 4321
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /
                  port: 4321
  service:
    main:
      ports:
        http:
          port: 80
          targetPort: 4321
cloudflared:
  probe:
    enabled: true
    targetUrl: https://www.alexlebens.dev
