{
 "title": "Sonarr",
 "tags": [
  "application",
  "tv shows"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Instance",
    "query": {
     "query": "label_values(sonarr_system_status,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Show Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 16, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_queue_total{namespace=\"$namespace\"} OR on() vector(0)",
     "legendFormat": "Queued"
    },
    {
     "expr": "sum(sonarr_episode_missing_total{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "Missing"
    },
    {
     "expr": "sum(sonarr_history_total{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Series",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarr_series_monitored_total{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "Monitored"
    },
    {
     "expr": "sum(sonarr_series_total{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Seasons",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarr_season_monitored_total{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "Monitored"
    },
    {
     "expr": "sum(sonarr_season_total{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Episodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarr_episode_downloaded_total{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "sum(sonarr_episode_total{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Storage Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarr_series_filesize_bytes{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarr_rootfolder_freespace_bytes{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}