apiVersion: v1
kind: Pod
metadata:
  name: "tdarr-tdarr-exporter-test-connection"
  labels:
    helm.sh/chart: tdarr-exporter-1.2.0
    app.kubernetes.io/name: tdarr-exporter
    app.kubernetes.io/instance: tdarr
    app.kubernetes.io/version: "2.1.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: "docker.io/busybox:1.36.1"
      command: ['wget']
      args: ['tdarr-tdarr-exporter:9090/healthz']
  restartPolicy: Never
