apiVersion: v1
kind: ServiceAccount
metadata:
  name: tdarr
  labels:
    app.kubernetes.io/instance: tdarr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tdarr
    helm.sh/chart: tdarr-5.0.0
  namespace: tdarr
