apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tdarr
  labels:
    app.kubernetes.io/instance: tdarr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tdarr
    helm.sh/chart: tdarr-5.1.0
  namespace: tdarr
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - tdarr
  selector:
    matchLabels:
      app.kubernetes.io/instance: tdarr
      app.kubernetes.io/name: tdarr
  endpoints:
    - port: oauth-metrics
