site-documentation:
  global:
    fullnameOverride: site-documentation
  controllers:
    main:
      type: deployment
      replicas: 3
      strategy: RollingUpdate
      containers:
        main:
          image:
            repository: harbor.alexlebens.net/images/site-documentation
            tag: 0.27.1@sha256:a9e8659827375e7ee65ea8bc8550f4c0604316b48f39da7fa255fa9f3b5a17d6
          resources:
            requests:
              cpu: 10m
              memory: 40Mi
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
          targetPort: 4321
