site-documentation:
  global:
    fullnameOverride: site-documentation
  controllers:
    main:
      type: deployment
      replicas: 3
      strategy: RollingUpdate
      containers:
        main:
          image:
            repository: harbor.alexlebens.net/images/site-documentation
            tag: 0.35.0@sha256:736a44315817f8b787dbc628537090120c5a4012eebec3b98f7b961495ebf3e5
          resources:
            requests:
              cpu: 10m
              memory: 40Mi
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
          targetPort: 4321
