site-documentation:
  global:
    fullnameOverride: site-documentation
  controllers:
    main:
      type: deployment
      replicas: 3
      strategy: RollingUpdate
      containers:
        main:
          image:
            repository: harbor.alexlebens.net/images/site-documentation
            tag: 0.24.0@sha256:4de96b40683bdb4998219b38b728a46e821de7ccd28b2ff6cc69ff26a712e7af
          resources:
            requests:
              cpu: 10m
              memory: 40Mi
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
          targetPort: 4321
