apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: bgp-ip-pool
  namespace: kube-system
  labels:
    app.kubernetes.io/name: bgp-ip-pool
    app.kubernetes.io/instance: cilium
    app.kubernetes.io/part-of: cilium
spec:
  blocks:
    - start: "10.234.0.30"
      stop: "10.234.0.39"
