apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-lb-advertisement
  labels:
    app.kubernetes.io/name: bgp-lb-advertisement
    app.kubernetes.io/instance: cilium
    app.kubernetes.io/part-of: cilium
spec:
  advertisements:
    - advertisementType: Service
      service:
        addresses:
          - LoadBalancerIP
