apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: grafana
  namespace: grafana-operator
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana-operator
    app.kubernetes.io/part-of: grafana-operator
spec:
  name: "Grafana"
  launchUrl: https://grafana.alexlebens.dev
  description: "Operational dashboards for monitoring using Prometheus metrics and Loki logging."
  callbackUrls:
    - https://grafana.alexlebens.dev/login/generic_oauth
  pkceEnabled: false
  skipConsent: true
  allowedUserGroups:
    - name: platform-admin
      namespace: pocket-id-operator
    - name: admin
      namespace: pocket-id-operator
    - name: user
      namespace: pocket-id-operator
  clientID: 4A432F02-12D5-4F32-AF21-828ACDF51917
  clientSecretRef:
    name: grafana-operator-oidc-secret
    key: clientSecret
  logo:
    logoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/grafana.webp
    darkLogoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/grafana.webp
