apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-cl01tl-grafana-operator-http-2xx
  namespace: grafana-operator
  labels:
    app.kubernetes.io/name: blackbox-cl01tl-grafana-operator-http-2xx
    app.kubernetes.io/instance: grafana-operator
    app.kubernetes.io/part-of: grafana-operator
spec:
  prober:
    url: kube-prometheus-stack-prometheus-blackbox-exporter.kube-prometheus-stack.svc.cluster.local:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - http://grafana-main-service.grafana-operator:3000/api/health
