apiVersion: v1
kind: Service
metadata:
  name: grafana-operator-valkey-unified-alerting-read
  labels:
    helm.sh/chart: valkey-0.9.3
    app.kubernetes.io/name: valkey-unified-alerting
    app.kubernetes.io/instance: grafana-operator
    app.kubernetes.io/version: "9.0.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: read
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 6379
      targetPort: tcp
      protocol: TCP
  selector:
    app.kubernetes.io/name: valkey-unified-alerting
    app.kubernetes.io/instance: grafana-operator
