apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: mariadb-backups
  namespace: mariadb-operator
  labels:
    app.kubernetes.io/name: mariadb-backups
    helm.sh/chart: garage-bucket-mariadb-backups-0.3.9
    app.kubernetes.io/instance: mariadb-operator
    app.kubernetes.io/part-of: mariadb-operator
    app.kubernetes.io/version: "v0.7.5"
    app.kubernetes.io/managed-by: Helm
spec:
  clusterRef:
    name: garage-cluster-a
    namespace: garage-operator
  lifecycle:
    rules:
      - id: expire-incomplete-multipart
        status: Enabled
        abortIncompleteMultipartUploadDays: 7
