apiVersion: v2
name: omni-tools
version: 1.0.0
description: OmniTools
keywords:
  - omni-tools
home: https://docs.alexlebens.dev/applications/omni-tools/
sources:
  - https://github.com/iib0011/omni-tools
  - https://hub.docker.com/r/iib0011/omni-tools
  - https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
maintainers:
  - name: alexlebens
dependencies:
  - name: app-template
    alias: omni-tools
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 4.6.2
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/omnitools.png
# renovate: datasource=github-releases depName=iib0011/omni-tools
appVersion: 0.6.0
