omni-tools:
  controllers:
    main:
      type: deployment
      replicas: 1
      strategy: Recreate
      containers:
        main:
          image:
            repository: iib0011/omni-tools
            tag: 0.6.0@sha256:ceb5acc317daf387634f7f212cefe4722fd1243ad1cba74203f25254195b6c69
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
          targetPort: 80
  route:
    main:
      kind: HTTPRoute
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway
          namespace: traefik
      hostnames:
        - omni-tools.alexlebens.net
      rules:
        - backendRefs:
            - name: omni-tools
              port: 80
          matches:
            - path:
                type: PathPrefix
                value: /
