apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc-authentik
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-oidc-authentik
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/part-of: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: secret
      remoteRef:
        key: /cl01tl/authentik/oidc/argocd
        property: secret
    - secretKey: client
      remoteRef:
        key: /cl01tk/authentik/oidc/argocd
        property: client
