apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: argocd
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/part-of: argocd
spec:
  name: "Argo CD"
  launchUrl: https://argocd.alexlebens.dev
  description: "A declarative, GitOps continuous delivery tool for Kubernetes."
  callbackUrls:
    - https://argocd.alexlebens.dev/api/dex/callback
  pkceEnabled: true
  skipConsent: true
  allowedUserGroups:
    - name: platform-admin
      namespace: pocket-id-operator
  clientID: 3AFD9D4F-85F0-43B0-AAEC-CE6BE2044BE4
  clientSecretRef:
    name: argocd-oidc-secret
    key: clientSecret
  logo:
    logoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/argo-cd.webp
    darkLogoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/argo-cd.webp
