apiVersion: v1
kind: Pod
metadata:
  name: argocd-redis-ha-service-test
  namespace: "argocd"
  labels:
    app: redis-ha
    heritage: "Helm"
    release: "argocd"
    chart: redis-ha-4.38.0
  annotations:
    "helm.sh/hook": test-success
spec:
  nodeSelector: {}
  tolerations: []
  containers:
    - name: "argocd-service-test"
      image: redis:8.10.0-alpine@sha256:5cca2f8a01ef2264c52dac86f14ec6a5abe973a93331e1b62522cfc5e63e4691
      command:
        - sh
        - -c
        - redis-cli -h argocd-redis-ha-haproxy -p 6379 info server
      resources: {}
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
  restartPolicy: Never
