apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-mcp
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-mcp
    helm.sh/chart: argocd-mcp-5.2.1
  namespace: argocd
