apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-redis-ha
  namespace: "argocd"
  labels:
    app: redis-ha
    heritage: "Helm"
    release: "argocd"
    chart: redis-ha-4.34.11
spec:
  endpoints:
    - targetPort: 9121
  jobLabel: argocd-redis-ha
  namespaceSelector:
    matchNames:
      - "argocd"
  selector:
    matchLabels:
      app: redis-ha
      release: argocd
      exporter: enabled
