apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-4k-oauth-proxy
  namespace: sonarr-4k
  labels:
    app.kubernetes.io/name: sonarr-4k-oauth-proxy
    app.kubernetes.io/instance: sonarr-4k
    app.kubernetes.io/part-of: sonarr-4k
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: OAUTH2_PROXY_CLIENT_ID
      remoteRef:
        key: /cl01tl/authentik/oidc/sonarr-4k
        property: client
    - secretKey: OAUTH2_PROXY_CLIENT_SECRET
      remoteRef:
        key: /cl01tl/authentik/oidc/sonarr-4k
        property: secret
    - secretKey: OAUTH2_PROXY_COOKIE_SECRET
      remoteRef:
        key: /cl01tl/authentik/oidc/sonarr-4k
        property: cookie
    - secretKey: OAUTH2_PROXY_OIDC_ISSUER_URL
      remoteRef:
        key: /cl01tl/authentik/oidc/sonarr-4k
        property: issuer-url
