{
 "title": "Loki",
 "tags": [
  "system",
  "monitoring"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Summary of alerts status",
   "type": "alertlist",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Problems in the Loki Stack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of error/warning messages logged by Loki itself",
     "type": "timeseries",
     "description": "Total number of messages logged by Loki itself",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(log_messages_total{app=\"loki\",level=~\"error|warn\"}[1m])) by (level)",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Error/warning messages logged by Loki itself",
     "type": "logs",
     "gridPos": { "h": 5, "w": 15, "x": 9, "y": 13 },
     "targets": [
      {
       "expr": "{app=\"loki\"}"
      }
     ]
    },
    {
     "title": "Error/warning messages logged by Promtail",
     "type": "timeseries",
     "description": "Total number of messages logged by Promtail",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(log_messages_total{app_kubernetes_io_name=\"promtail\",level=~\"error|warn\"}[1m])) by (level)\n",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Error/warning messages logged by Promtail",
     "type": "logs",
     "gridPos": { "h": 5, "w": 15, "x": 9, "y": 18 },
     "targets": [
      {
       "expr": "{app=\"promtail\"}"
      }
     ]
    },
    {
     "title": "Loki (distributor) - failed batch appends sent to ingesters",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(loki_distributor_ingester_append_failures_total[1m])*60"
      }
     ]
    },
    {
     "title": "Promtail - dropped log entries",
     "type": "timeseries",
     "description": "Number of log entries dropped because failed to be sent to the Loki ingester after all retries.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(promtail_dropped_entries_total[1m])*60",
       "legendFormat": "pod={{kubernetes_pod_name}}, instance={{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logging activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of Streams in Loki",
     "type": "timeseries",
     "description": "The total number of streams created per tenant.\nThis should not increase after startup.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 511 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "loki_ingester_memory_streams", "legendFormat": "Streams" }
     ]
    },
    {
     "title": "Loki (distributor) - log entries received per second",
     "type": "timeseries",
     "description": "The total number of log entries received per tenant (not necessarily of lines, as an entry can have more than one line of text).",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 517 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(loki_distributor_lines_received_total[1m])"
      }
     ]
    },
    {
     "title": "Bytes received in ingester per second",
     "type": "timeseries",
     "description": "The total number of uncompressed bytes received per tenant.\n",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 523 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_bytes_received_total[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Loki memory usage (% of Kubernetes memory limit)",
     "type": "timeseries",
     "description": "Percentage of actual usage over configured limit",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 776 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * max by(pod,container) (container_memory_working_set_bytes{container!=\"\",container!=\"POD\",pod=~\"loki.*\"}) / on (pod,container) group_left  kube_pod_container_resource_limits_memory_bytes{pod=~\"loki.*\"}",
       "legendFormat": "Usage (pod={{pod}}, container={{container}}, name={{name}})"
      }
     ]
    },
    {
     "title": "Loki memory usage vs Kubernetes limit and request",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 782 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{container!=\"\",container!=\"POD\",pod=~\"loki.*\"}",
       "legendFormat": "Usage (pod={{pod}}, container={{container}})"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_memory_bytes{pod=~\"loki.*\"})",
       "legendFormat": "Limit"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_memory_bytes{pod=~\"loki.*\"})",
       "legendFormat": "Request"
      }
     ]
    },
    {
     "title": "Promtail memory usage (% of Kubernetes memory limit)",
     "type": "timeseries",
     "description": "Percentage of actual usage over configured limit",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 788 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100* max by(pod,container) (container_memory_working_set_bytes{container!=\"\",container!=\"POD\",pod=~\"promtail.*\"})\n/\non (pod,container) (kube_pod_container_resource_limits_memory_bytes{pod=~\"promtail.*\"})"
      }
     ]
    },
    {
     "title": "Promtail memory usage vs Kubernetes limit and request",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 794 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{container!=\"\",container!=\"POD\",pod=~\"promtail.*\"}",
       "legendFormat": "Usage (pod={{pod}}, container={{container}})"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_memory_bytes{pod=~\"promtail.*\"})",
       "legendFormat": "Limit"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_memory_bytes{pod=~\"promtail.*\"})",
       "legendFormat": "Request"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Loki CPU usage (% of Kubernetes CPU limit)",
     "type": "timeseries",
     "description": "percentage of configured limit",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 965 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100* rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\",pod=~\"loki.*\"}[1m])\n/\non (pod,container) kube_pod_container_resource_limits_cpu_cores{container=\"loki\"}"
      }
     ]
    },
    {
     "title": "Loki CPU usage vs Kubernetes limit and request",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 971 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\",pod=~\"loki.*\"}[1m])",
       "legendFormat": "CPU Usage (pod={{pod}}, container={{container}})"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_cpu_cores{pod=~\"loki.*\"})",
       "legendFormat": "CPU Limit"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_cpu_cores{pod=~\"loki.*\"})",
       "legendFormat": "CPU Request"
      }
     ]
    },
    {
     "title": "Promtail CPU usage (% of Kubernetes limit)",
     "type": "timeseries",
     "description": "percentage of configured limit",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 977 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * rate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\",pod=~\"promtail.*\"}[1m])\n/\non (pod,container) kube_pod_container_resource_limits_cpu_cores{pod=~\"promtail.*\"}"
      }
     ]
    },
    {
     "title": "Promtail CPU usage vs Kubernetes limit and request",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 983 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\",pod=~\"promtail.*\"}[1m])",
       "legendFormat": "CPU Usage (pod={{pod}}, container={{container}})"
      },
      {
       "expr": "min(kube_pod_container_resource_limits_cpu_cores{pod=~\"promtail.*\"})",
       "legendFormat": "CPU Limit"
      },
      {
       "expr": "min(kube_pod_container_resource_requests_cpu_cores{pod=~\"promtail.*\"})",
       "legendFormat": "CPU Request"
      }
     ]
    }
   ]
  }
 ]
}