apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-code-server-password
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant-code-server-password
    app.kubernetes.io/instance: home-assistant
    app.kubernetes.io/part-of: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: PASSWORD
      remoteRef:
        key: /cl01tl/home-assistant/code-server
        property: password
    - secretKey: SUDO_PASSWORD
      remoteRef:
        key: /cl01tl/home-assistant/code-server
        property: sudo-password
