apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-metric-token
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant-metric-token
    app.kubernetes.io/instance: home-assistant
    app.kubernetes.io/part-of: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: bearer-token
      remoteRef:
        key: /cl01tl/home-assistant/config
        property: bearer-token
