apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kaneo-key
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kaneo-key
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: auth-secret
      remoteRef:
        key: /cl01tl/kaneo/key
        property: auth-secret

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kaneo-oidc-authentik
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kaneo-oidc-authentik
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: CUSTOM_OAUTH_CLIENT_ID
      remoteRef:
        key: /cl01tl/authentik/oidc/kaneo
        property: client
    - secretKey: CUSTOM_OAUTH_CLIENT_SECRET
      remoteRef:
        key: /cl01tl/authentik/oidc/kaneo
        property: secret

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kaneo-bucket-garage
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kaneo-bucket-garage
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: S3_ACCESS_KEY_ID
      remoteRef:
        key: /garage/home-infra/kaneo-assets
        property: ACCESS_KEY_ID
    - secretKey: S3_SECRET_ACCESS_KEY
      remoteRef:
        key: /garage/home-infra/kaneo-assets
        property: ACCESS_SECRET_KEY
    - secretKey: S3_REGION
      remoteRef:
        key: /garage/home-infra/kaneo-assets
        property: ACCESS_REGION
