apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-exporter
  namespace: "harbor"
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/name: harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harbor
    app.kubernetes.io/version: "2.15.1"
    component: exporter
    app.kubernetes.io/component: exporter
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      release: harbor
      app: "harbor"
      component: exporter
  template:
    metadata:
      labels:
        heritage: Helm
        release: harbor
        chart: harbor
        app: "harbor"
        app.kubernetes.io/instance: harbor
        app.kubernetes.io/name: harbor
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: harbor
        app.kubernetes.io/version: "2.15.1"
        component: exporter
        app.kubernetes.io/component: exporter
      annotations:
        checksum/configmap: f38fc19ccd30fc97a674984f7214494d252af8e780845d39073c74d09fce0327
        checksum/secret: c743567cdf7927f07eb7eab00fa6b651632a77019e66307cacc3f71cbbb0a446
    spec:
      securityContext:
        runAsUser: 10000
        fsGroup: 10000
      automountServiceAccountToken: false
      containers:
        - name: exporter
          image: ghcr.io/goharbor/harbor-exporter:v2.15.1@sha256:372275b6b6abeb571fa7bd5de458e3d75f1a1636503b3c0abe02938f2b285d75
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: 8001
            initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
          args: ["-log-level", "info"]
          envFrom:
            - configMapRef:
                name: "harbor-exporter-env"
            - secretRef:
                name: "harbor-exporter"
          env:
            - name: HARBOR_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: harbor-postgresql-18-cluster-app
                  key: password
            - name: HARBOR_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: harbor-secret
                  key: HARBOR_ADMIN_PASSWORD
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8001
          volumeMounts:
      volumes:
        - name: config
          secret:
            secretName: "harbor-exporter"
