apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: harbor-registry
  namespace: harbor
  labels:
    app.kubernetes.io/name: harbor-registry
    helm.sh/chart: garage-bucket-harbor-registry-0.3.10
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/part-of: harbor
    app.kubernetes.io/version: "v0.7.5"
    app.kubernetes.io/managed-by: Helm
spec:
  clusterRef:
    name: garage-cluster-b
    namespace: garage-operator
  lifecycle:
    rules:
      - id: expire-incomplete-multipart
        status: Enabled
        abortIncompleteMultipartUploadDays: 7
