{
 "title": "Harbor",
 "tags": [
  "service",
  "containers"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "harbor_health" }
   ]
  },
  {
   "title": "Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Harbor Health",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "harbor_health" }
   ]
  },
  {
   "title": "Quota Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "harbor_project_quota_usage_byte",
     "legendFormat": "{{ project_name }}"
    }
   ]
  },
  {
   "title": "Artifact Pulled",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(harbor_artifact_pulled[5m])",
     "legendFormat": "{{ project_name }} "
    }
   ]
  },
  {
   "title": "Projects",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(harbor_project_total)" }
   ]
  },
  {
   "title": "Repos",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(harbor_project_repo_total)" }
   ]
  },
  {
   "title": "Public Projects",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(harbor_project_total{public=\"true\"})"
    }
   ]
  },
  {
   "title": "Public Repos",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(harbor_project_repo_total{public=\"true\"})"
    }
   ]
  },
  {
   "title": "Private Projects",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(harbor_project_total{public=\"false\"})"
    }
   ]
  },
  {
   "title": "Private Repos",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(harbor_project_repo_total{public=\"false\"})"
    }
   ]
  },
  {
   "title": "Core Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Core Request Inflight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(harbor_core_http_inflight_requests) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Core Request Operatoration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(harbor_core_http_request_total[5m])) by (operation)",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Max Request Time 0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(harbor_core_http_request_duration_seconds{quantile=\"0.99\"}) by (operation)",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "JobService Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Task Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(harbor_task_queue_latency) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Task Concurrency",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(harbor_task_concurrency) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Task Queue Pending Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "harbor_task_queue_size", "legendFormat": "{{ type }}" }
     ]
    },
    {
     "title": "Number of Running Scheduled Job",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "harbor_task_scheduled_total", "legendFormat": " " }
     ]
    },
    {
     "title": "Tasks Per Minute - Fail",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(harbor_jobservice_task_total{status=\"fail\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Max Task Process Time 0.99 - Fail",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(harbor_jobservice_task_process_time_seconds{quantile=\"0.99\", status=\"fail\"}) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Tasks Per Minute - Success",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(harbor_jobservice_task_total{status=\"success\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Max Task Process Time 0.99 - Success",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(harbor_jobservice_task_process_time_seconds{quantile=\"0.99\", status=\"success\"}) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Registry Metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Registry request inflight",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(registry_http_in_flight_requests) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Registry request rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(registry_http_requests_total[5m])) by (method)",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "registry storage cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(registry_storage_cache_total[5m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "registry request time 0.99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(histogram_quantile(0.99, rate(registry_http_request_duration_seconds_bucket[10m]))) by (handler)",
       "legendFormat": "{{ handler }}"
      }
     ]
    },
    {
     "title": "registry request size 0.99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(histogram_quantile(0.99, rate(registry_http_request_size_bytes_bucket[10m]))) by (handler)",
       "legendFormat": "{{ handler }}"
      }
     ]
    },
    {
     "title": "registry response size 0.99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(histogram_quantile(0.99, rate(registry_http_response_size_bytes_bucket[10m]))) by (handler)",
       "legendFormat": "{{ handler }}"
      }
     ]
    }
   ]
  }
 ]
}