apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-ps09rp-harbor-http-2xx
  namespace: harbor
  labels:
    app.kubernetes.io/name: blackbox-ps09rp-harbor-http-2xx
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/part-of: harbor
spec:
  prober:
    url: ps09rp.alexlebens.net:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - https://harbor.alexlebens.net
