apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-key-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: prowlarr-key-secret
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: key
      remoteRef:
        key: /cl01tl/prowlarr/key
        property: key

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-oauth-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: prowlarr-oauth-proxy
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: OAUTH2_PROXY_CLIENT_ID
      remoteRef:
        key: /cl01tl/pocket-id/oidc/prowlarr
        property: clientId
    - secretKey: OAUTH2_PROXY_CLIENT_SECRET
      remoteRef:
        key: /cl01tl/pocket-id/oidc/prowlarr
        property: clientSecret
    - secretKey: OAUTH2_PROXY_COOKIE_SECRET
      remoteRef:
        key: /cl01tl/pocket-id/oidc/prowlarr
        property: cookie
    - secretKey: OAUTH2_PROXY_OIDC_ISSUER_URL
      remoteRef:
        key: /cl01tl/pocket-id/config
        property: issuer-url
