apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-config-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: n8n-config-secret
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    template:
      engineVersion: v2
      data:
        N8N_ENCRYPTION_KEY: "{{ `{{ .key }}` }}"
        N8N_HOST: "n8n{{ include "custom.domain" . }}"
        N8N_PORT: "5678"
        N8N_PROTOCOL: "https"
  data:
    - secretKey: key
      remoteRef:
        key: /cl01tl/n8n/key
        property: key

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "custom.defaultOauthProxySecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "custom.defaultOauthProxySecret" . }}
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: OAUTH2_PROXY_CLIENT_ID
      remoteRef:
        key: /cl01tl/pocket-id/oidc/n8n
        property: clientId
    - secretKey: OAUTH2_PROXY_CLIENT_SECRET
      remoteRef:
        key: /cl01tl/pocket-id/oidc/n8n
        property: clientSecret
    - secretKey: OAUTH2_PROXY_COOKIE_SECRET
      remoteRef:
        key: /cl01tl/pocket-id/oidc/n8n
        property: cookie
    - secretKey: OAUTH2_PROXY_OIDC_ISSUER_URL
      remoteRef:
        key: /cl01tl/pocket-id/config
        property: issuer-url
