apiVersion: v2
name: cert-manager
version: 1.0.0
description: Cert Manager
keywords:
  - cert-manager
  - certificates
home: https://docs.alexlebens.dev/Applications/cert-manager/
sources:
  - https://github.com/cert-manager/cert-manager
  - https://github.com/cert-manager/cert-manager/tree/master/deploy/charts/cert-manager
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/common-helpers
maintainers:
  - name: alexlebens
dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.21.1
  - name: common-helpers
    repository: oci://harbor.alexlebens.dev/helm-charts
    version: 0.4.1
icon: https://raw.githubusercontent.com/cert-manager/cert-manager/refs/heads/master/logo/logo.png
# renovate: datasource=github-releases depName=cert-manager/cert-manager
appVersion: v1.21.1
