cert-manager:
  crds:
    enabled: true
  replicaCount: 2
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  config:
    gatewayAPI:
      enabled: true
  resources:
    requests:
      cpu: 1m
      memory: 40Mi
  prometheus:
    servicemonitor:
      enabled: true
      honorLabels: true
  cainjector:
    enabled: true
    replicaCount: 2
