apiVersion: v2
name: code-server
version: 1.0.0
description: Code Server
keywords:
  - code-server
  - code
home: https://docs.alexlebens.dev/applications/code-server/
sources:
  - https://github.com/coder/code-server
  - https://github.com/linuxserver/docker-code-server
  - https://github.com/linuxserver/docker-code-server/pkgs/container/code-server
  - https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/cloudflared
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/volsync-target
maintainers:
  - name: alexlebens
dependencies:
  - name: app-template
    alias: code-server
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 4.6.2
  - name: cloudflared
    repository: oci://harbor.alexlebens.net/helm-charts
    version: 2.4.0
  - name: volsync-target
    alias: volsync-target-config
    version: 0.8.0
    repository: oci://harbor.alexlebens.net/helm-charts
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/visual-studio-code.png
# renovate: datasource=github-releases depName=linuxserver/docker-code-server
appVersion: 4.114.0-ls328
