code-server:
  controllers:
    main:
      type: deployment
      replicas: 1
      strategy: Recreate
      pod:
        securityContext:
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
      containers:
        main:
          image:
            repository: ghcr.io/linuxserver/code-server
            tag: 4.114.0-ls328@sha256:928e63f0b775d76cda606f181bae9d81c6d3fbd2d1daeef9438e3ba5579f391d
          env:
            - name: TZ
              value: America/Chicago
            - name: PUID
              value: 1000
            - name: PGID
              value: 1000
            - name: DEFAULT_WORKSPACE
              value: /config
          envFrom:
            - secretRef:
                name: codeserver-password-secret
          resources:
            requests:
              cpu: 1m
              memory: 40Mi
  service:
    main:
      controller: main
      ports:
        http:
          port: 8443
          targetPort: 8443
  route:
    main:
      kind: HTTPRoute
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway
          namespace: traefik
      hostnames:
        - code-server.alexlebens.net
      rules:
        - backendRefs:
            - name: code-server
              port: 8443
          matches:
            - path:
                type: PathPrefix
                value: /
  persistence:
    config:
      forceRename: code-server-config
      storageClass: ceph-block
      accessMode: ReadWriteOnce
      size: 2Gi
      advancedMounts:
        main:
          main:
            - path: /config
              readOnly: false
volsync-target-config:
  pvcTarget: code-server-config
  moverSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  local:
    enabled: true
    schedule: 16 8 * * *
  remote:
    enabled: true
    schedule: 16 9 * * *
  external:
    enabled: true
    schedule: 16 10 * * *
