apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grimmory-database-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: grimmory-database-config
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: password
      remoteRef:
        key: /cl01tl/grimmory/database
        property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grimmory-mariadb-cluster-backup-secret-external
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: grimmory-mariadb-cluster-backup-secret-external
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: access
      remoteRef:
        key: /digital-ocean/home-infra/mariadb-backups
        property: access
    - secretKey: secret
      remoteRef:
        key: /digital-ocean/home-infra/mariadb-backups
        property: secret

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grimmory-mariadb-cluster-backup-secret-garage
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: grimmory-mariadb-cluster-backup-secret-garage
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: access
      remoteRef:
        key: /garage/home-infra/mariadb-backups
        property: ACCESS_KEY_ID
    - secretKey: secret
      remoteRef:
        key: /garage/home-infra/mariadb-backups
        property: ACCESS_SECRET_KEY
