apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.grimmory.persistence.data.existingClaim }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.grimmory.persistence.data.existingClaim }}
    {{- include "custom.labels" . | nindent 4 }}
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume2/Storage/Books
    server: synology-bond{{ include "custom.domain" . }}
  mountOptions:
    - vers=4
    - minorversion=1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.grimmory.persistence.ingest.existingClaim }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.grimmory.persistence.ingest.existingClaim }}
    {{- include "custom.labels" . | nindent 4 }}
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: '/volume2/Storage/Books Import'
    server: synology-bond{{ include "custom.domain" . }}
  mountOptions:
    - vers=4
    - minorversion=1
