apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-cl01tl-yubal-http-2xx
  namespace: yubal
  labels:
    app.kubernetes.io/name: blackbox-cl01tl-yubal-http-2xx
    app.kubernetes.io/instance: yubal
    app.kubernetes.io/part-of: yubal
spec:
  prober:
    url: kube-prometheus-stack-prometheus-blackbox-exporter.kube-prometheus-stack.svc.cluster.local:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - http://yubal.yubal:80
