apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: yubal-backup-source-remote
  namespace: yubal
  labels:
    helm.sh/chart: volsync-target-config-2.0.0
    app.kubernetes.io/instance: yubal
    app.kubernetes.io/part-of: yubal
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: yubal-backup
spec:
  sourcePVC: yubal
  trigger:
    schedule: 15 10 * * 6
  restic:
    pruneIntervalDays: 7
    repository: yubal-backup-secret-remote
    retain:
      daily: 0
      hourly: 0
      monthly: 0
      weekly: 12
      yearly: 0
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-blockpool-snapshot
    cacheCapacity: 1Gi
