intel-device-plugins-operator:
  manager:
    image:
      hub: intel
      # renovate: datasource=docker depName=intel/intel-deviceplugin-operator
      tag: 0.35.0@sha256:d7eeac081bd17e58d8d4d542f3cb33d67cc1bdab314b09ad591e8eacb51dd5ec
  resources:
    limits:
      cpu: null
      memory: null
    requests:
      cpu: 10m
      memory: 50Mi
intel-device-plugins-gpu:
  name: gpudeviceplugin
  image:
    hub: intel
    # renovate: datasource=docker depName=intel/intel-deviceplugin-operator
    tag: 0.35.0@sha256:34697f9c286857da986381595ac2a693524a83c831955247dae47dfda4d2f526
  sharedDevNum: 5
