---
services:
    tailscale-homepage:
        image: ghcr.io/tailscale/tailscale:v1.98.3@sha256:854b77123b9536adae2e97f5a5fdb1790ed03438b911ab7f07780155e0af6ce2
        container_name: tailscale-homepage
        cap_add:
            - net_admin
            - sys_module
        environment:
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_ENABLE_METRICS=true
            - TS_HOSTNAME=home-ps10rp
            - TS_SERVE_CONFIG=/config/serve.json
        network_mode: service:homepage
        restart: always
        volumes:
            - tailscale:/var/lib/tailscale
            - ${PWD}/serve.json:/config/serve.json
        devices:
            - /dev/net/tun:/dev/net/tun

    dockerproxy:
        image: ghcr.io/tecnativa/docker-socket-proxy:v0.4.2@sha256:1f3a6f303320723d199d2316a3e82b2e2685d86c275d5e3deeaf182573b47476
        container_name: homepage-dockerproxy
        environment:
            - CONTAINERS=1
            - POST=0
        network_mode: service:homepage
        privileged: true
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro

    homepage:
        image: ghcr.io/gethomepage/homepage:v1.13.1@sha256:d8d784e5090111b6e4c56dfd90e272d2953a2094e87349f647165df0fa6c4401
        container_name: homepage
        labels:
            traefik.enable: true
            traefik.docker.network: internal
            traefik.http.routers.homepage.entrypoints: web-secure
            traefik.http.routers.homepage.rule: Host(`www.lebens-home.net`)
            traefik.http.routers.homepage.service: homepage
            traefik.http.services.homepage.loadbalancer.server.port: 3000
        environment:
            - HOMEPAGE_ALLOWED_HOSTS=www.lebens-home.net
        networks:
            internal: null
        restart: always
        volumes:
            - ${PWD}/homepage_config:/app/config

networks:
    internal:
        name: internal
        external: true

volumes:
    tailscale:
