apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-data-backup-secret-d
  namespace: mealie
  labels:
    helm.sh/chart: volsync-target-data-3.0.0
    app.kubernetes.io/instance: mealie
    app.kubernetes.io/part-of: mealie
    app.kubernetes.io/version: "0.16.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mealie-data-backup-secret-d
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      mergePolicy: Merge
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "s3:{{ .ENDPOINT }}/{{ .BUCKET }}/cl01tl/mealie/mealie-data"
  data:
    - secretKey: ENDPOINT
      remoteRef:
        key: /cs01bb/s3/config
        property: ENDPOINT
    - secretKey: BUCKET
      remoteRef:
        key: /cs01bb/s3/keys/volsync-backups
        property: BUCKET_NAME
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: /cs01bb/s3/keys/volsync-backups
        property: RESTIC_PASSWORD
    - secretKey: AWS_DEFAULT_REGION
      remoteRef:
        key: /cs01bb/s3/keys/volsync-backups
        property: AWS_REGION
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /cs01bb/s3/keys/volsync-backups
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /cs01bb/s3/keys/volsync-backups
        property: AWS_SECRET_ACCESS_KEY
