apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-token
  namespace: vault
  labels:
    app.kubernetes.io/name: vault-token
    app.kubernetes.io/instance: vault
    app.kubernetes.io/part-of: vault
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: token
      remoteRef:
        key: /cl01tl/vault/role/snapshot
        property: root
