apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-ntfy-unseal-config
  namespace: vault
  labels:
    app.kubernetes.io/name: vault-ntfy-unseal-config
    app.kubernetes.io/instance: vault
    app.kubernetes.io/part-of: vault
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    template:
      mergePolicy: Merge
      engineVersion: v2
      data:
        NOTIFY_QUEUE_URLS: "{{ .endpoint }}/{{ .topic }}/?priority=4&tags=vault,unseal&title=Vault+Unsealed"
  data:
    - secretKey: endpoint
      remoteRef:
        key: /cl01tl/ntfy/users/cl01tl
        property: internal-endpoint-credential
    - secretKey: topic
      remoteRef:
        key: /cl01tl/ntfy/topics
        property: vault
