apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-unseal-config-3
  namespace: vault
  labels:
    app.kubernetes.io/name: vault-unseal-config-3
    app.kubernetes.io/instance: vault
    app.kubernetes.io/part-of: vault
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: ENVIRONMENT
      remoteRef:
        key: /cl01tl/vault/unseal
        property: environment
    - secretKey: NODES
      remoteRef:
        key: /cl01tl/vault/unseal
        property: nodes
    - secretKey: TOKENS
      remoteRef:
        key: /cl01tl/vault/unseal
        property: tokens-3
