apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-unseal
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: unseal-5.0.0
  namespace: vault
