apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tubearchivist-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tubearchivist-config
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: ELASTIC_PASSWORD
      remoteRef:
        key: /cl01tl/tubearchivist/elasticsearch
        property: password
    - secretKey: TA_PASSWORD
      remoteRef:
        key: /cl01tl/tubearchivist/config
        property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tubearchivist-elasticsearch-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tubearchivist-elasticsearch-config
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: username
      remoteRef:
        key: /cl01tl/tubearchivist/elasticsearch
        property: username
    - secretKey: password
      remoteRef:
        key: /cl01tl/tubearchivist/elasticsearch
        property: password
    - secretKey: roles
      remoteRef:
        key: /cl01tl/tubearchivist/elasticsearch
        property: roles

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: protonvpn-wireguard-conf
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: protonvpn-wireguard-conf
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: conf
      remoteRef:
        key: /protonvpn/config
        property: conf
    - secretKey: email
      remoteRef:
        key: /protonvpn/config
        property: email
    - secretKey: password
      remoteRef:
        key: /protonvpn/config
        property: password
    - secretKey: private-key
      remoteRef:
        key: /protonvpn/config
        property: private-key
