apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    {{- include "custom.labels" . | nindent 4 }}
spec:
  name: "MediaLyze"
  launchUrl: https://medialyze{{ include "custom.domain" . }}
  description: "Self-hosted media library analysis for large video collections."
  callbackUrls:
    - https://medialyze{{ include "custom.domain" . }}/oauth2/callback
  pkceEnabled: true
  skipConsent: true
  allowedUserGroups:
    - name: user
      namespace: pocket-id-operator
  clientID: 3D6B1C7B-03C7-43F7-B5FD-9369CB5CFC9C
  clientSecretRef:
    name: {{ include "custom.defaultOauthProxySecret" . }}
    key: OAUTH2_PROXY_CLIENT_SECRET
  logo:
    logoUrl: {{ include "custom.iconUrl" . }}medialyze.webp
    darkLogoUrl: {{ include "custom.iconUrl" . }}medialyze-light.webp
