apiVersion: v2
name: jellyfin-testing
version: 1.0.0
description: Jellyfin
keywords:
  - jellyfin
  - testing
home: https://docs.alexlebens.dev/applications/jellyfin-testing/
sources:
  - https://github.com/jellyfin/jellyfin
  - https://github.com/jellyfin/jellyfin/pkgs/container/jellyfin
  - https://github.com/jellyfin/jellyfin-helm/tree/master/charts/jellyfin
maintainers:
  - name: alexlebens
dependencies:
  - name: jellyfin
    alias: jellyfin-testing
    repository: https://jellyfin.github.io/jellyfin-helm
    version: 3.2.0
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/jellyfin.png
# renovate: datasource=github-releases depName=jellyfin/jellyfin
appVersion: 12.0-rc1
