apiVersion: v1
kind: ServiceAccount
metadata:
  name: pocket-id-seed
  namespace: affine
  labels:
    app.kubernetes.io/name: pocket-id-seed
    app.kubernetes.io/instance: affine
    app.kubernetes.io/part-of: affine
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-10"
    "argocd.argoproj.io/hook": PreSync
    "argocd.argoproj.io/hook-delete-policy": BeforeHookCreation
