apiVersion: v1
kind: Service
metadata:
  name: affine
  labels:
    app.kubernetes.io/instance: affine
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: affine
    app.kubernetes.io/service: affine
    helm.sh/chart: affine-5.2.1
  namespace: affine
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3010
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: affine
    app.kubernetes.io/name: affine
