apiVersion: v1
kind: ServiceAccount
metadata:
  name: affine
  labels:
    app.kubernetes.io/instance: affine
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: affine
    helm.sh/chart: affine-5.2.1
  namespace: affine
