apiVersion: v2
name: jellyfin
version: 1.0.0
description: Jellyfin
keywords:
  - jellyfin
  - media
home: https://docs.alexlebens.dev/Applications/jellyfin/
sources:
  - https://github.com/jellyfin/jellyfin
  - https://github.com/jellyfin/jellyfin/pkgs/container/jellyfin
  - https://github.com/jellyfin/jellyfin-helm/tree/master/charts/jellyfin
  - https://github.com/meilisearch/meilisearch-kubernetes/tree/main/charts/meilisearch
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/volsync-target
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/common-helpers
maintainers:
  - name: alexlebens
dependencies:
  - name: jellyfin
    repository: https://jellyfin.github.io/jellyfin-helm
    version: 3.2.0
  - name: meilisearch
    repository: https://meilisearch.github.io/meilisearch-kubernetes
    version: 0.38.0
  - name: volsync-target
    alias: volsync-target-config
    repository: oci://harbor.alexlebens.dev/helm-charts
    version: 2.2.2
  - name: common-helpers
    repository: oci://harbor.alexlebens.dev/helm-charts
    version: 0.4.1
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/jellyfin.png
# renovate: datasource=github-releases depName=jellyfin/jellyfin
appVersion: 10.11.11
