garage-ui:
  fullnameOverride: garage-ui
  config:
    server:
      domain: a-ui.s3.alexlebens.dev
      root_url: https://a-ui.s3.alexlebens.dev
    garage:
      endpoint: http://synology.alexlebens.dev:3900
      admin_endpoint: http://synology.alexlebens.dev:3903
      existingSecret:
        name: garage-token
        key: admin-token
    auth:
      jwt_private_key_secret:
        name: garage-ui-jwt-key
        key: jwt-key.pem
      oidc:
        enabled: true
        provider_name: AlexAuth
        client_id: 8C33EB93-937D-4E94-AE16-9B7B9659C4D9
        existingSecret:
          name: garage-ui-oidc
          key: clientSecret
        issuer_url: https://auth.alexlebens.dev
        scopes:
          - openid
          - email
          - profile
          - groups
        role_attribute_path: groups
        admin_role: "platform-admin"

pocket-id-client:
  mode: oidc
  client:
    displayName: "Garage Cluster (A)"
    description: "An S3-compatible object storage service running on ps02sn."
    launchUrl: https://a-ui.s3.alexlebens.dev
    callbackUrls:
      - https://a-ui.s3.alexlebens.dev/auth/oidc/callback
      - https://a-ui.s3.alexlebens.dev/api/v1/auth/oidc/callback
    clientID: 8C33EB93-937D-4E94-AE16-9B7B9659C4D9
    pkceEnabled: false
    allowedUserGroups:
      - name: platform-admin
        namespace: pocket-id-operator
    logo:
      selfhstLogoName: garage

common-helpers:
  probe:
    internal: http://garage-ui.garage-a:80
    external: https://a-ui.s3.alexlebens.dev
