apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: loki-data-key
  namespace: loki
  labels:
    app.kubernetes.io/name: loki-data-key
    helm.sh/chart: garage-bucket-loki-data-0.3.10
    app.kubernetes.io/instance: loki
    app.kubernetes.io/part-of: loki
    app.kubernetes.io/version: "v0.7.5"
    app.kubernetes.io/managed-by: Helm
spec:
  name: loki-data-key
  clusterRef:
    name: garage-cluster-a
    namespace: garage-operator
  importKey:
    secretRef:
      name: loki-data-secret
    accessKeyIdKey: AWS_ACCESS_KEY_ID
    secretAccessKeyKey: AWS_SECRET_ACCESS_KEY
  bucketPermissions:
    - bucketRef:
        name: loki-data
      read: true
      write: true
      owner: true
