apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shelfmark-grimmory-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: shelfmark-grimmory-config
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: grimmory-user
      remoteRef:
        key: /cl01tl/grimmory/users/shelfmark
        property: user
    - secretKey: grimmory-password
      remoteRef:
        key: /cl01tl/grimmory/users/shelfmark
        property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shelfmark-prowlarr-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: shelfmark-prowlarr-config
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: prowlarr-key
      remoteRef:
        key: /cl01tl/prowlarr/key
        property: key
