apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synology-iscsi-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: synology-iscsi-credentials
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: username
      remoteRef:
        key: /cl01tl/democratic-csi-synology-iscsi/config
        property: username
    - secretKey: password
      remoteRef:
        key: /cl01tl/democratic-csi-synology-iscsi/config
        property: password
