apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: omni-tools-oauth-proxy
  namespace: omni-tools
  labels:
    app.kubernetes.io/name: omni-tools-oauth-proxy
    app.kubernetes.io/instance: omni-tools
    app.kubernetes.io/part-of: omni-tools
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: OAUTH2_PROXY_CLIENT_ID
      remoteRef:
        key: /cl01tl/pocket-id/oidc/omni-tools
        property: clientId
    - secretKey: OAUTH2_PROXY_CLIENT_SECRET
      remoteRef:
        key: /cl01tl/pocket-id/oidc/omni-tools
        property: clientSecret
    - secretKey: OAUTH2_PROXY_COOKIE_SECRET
      remoteRef:
        key: /cl01tl/pocket-id/oidc/omni-tools
        property: cookie
    - secretKey: OAUTH2_PROXY_OIDC_ISSUER_URL
      remoteRef:
        key: /cl01tl/pocket-id/config
        property: issuer-url
