apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: headlamp
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: headlamp
    {{- include "custom.labels" . | nindent 4 }}
spec:
  name: "Headlamp"
  launchUrl: https://headlamp.alexlebens.net
  description: "An easy-to-use and extensible Kubernetes web UI."
  callbackUrls:
    - https://headlamp.alexlebens.net/oidc-callback
  pkceEnabled: true
  skipConsent: true
  allowedUserGroups:
    - name: platform-admin
      namespace: pocket-id-operator
  clientID: 131F7026-5D4E-4B1E-A941-0BF74C2DD9EB
  clientSecretRef:
    name: headlamp-oidc-secret
    key: clientSecret
  logo:
    logoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/headlamp.webp
    darkLogoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons@main/webp/headlamp-light.webp
