apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp-admin
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: headlamp-admin
    {{- include "custom.labels" . | nindent 4 }}
