apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-ps08rp-cluster-nodes
  namespace: blackbox
  labels:
    app.kubernetes.io/name: blackbox-ps08rp-cluster-nodes
    probe.category: cluster_nodes
    app.kubernetes.io/instance: blackbox
    app.kubernetes.io/part-of: blackbox
spec:
  prober:
    url: ps08rp.alexlebens.dev:9115
  module: http_401_insecure
  targets:
    staticConfig:
      labels:
        probe_category: cluster_nodes
      static:
        - https://cl01tl.alexlebens.dev:6443
        - https://cl01tl-api.alexlebens.dev:6443
        - https://cl01tl-endpoint.alexlebens.dev:10250/healthz
