apiVersion: v1
kind: ServiceAccount
metadata:
  name: blackbox-cloudflare
  namespace: blackbox
  labels:
    helm.sh/chart: prometheus-blackbox-exporter-cloudflare-11.18.0
    app.kubernetes.io/name: prometheus-blackbox-exporter-cloudflare
    app.kubernetes.io/instance: blackbox
    app.kubernetes.io/version: "v0.28.0"
    app.kubernetes.io/managed-by: Helm
