apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kyoo-transcodermetadata
  namespace: kyoo
  labels:
    helm.sh/chart: kyoo-5.0.0
    app.kubernetes.io/name: kyoo-transcoder
    app.kubernetes.io/instance: kyoo
    app.kubernetes.io/component: transcoder
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyoo
    app.kubernetes.io/version: "5.0.0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
