apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kyoo-media-anime-nfs-storage
  namespace: kyoo
  labels:
    app.kubernetes.io/name: kyoo-media-anime-nfs-storage
    app.kubernetes.io/instance: kyoo
    app.kubernetes.io/part-of: kyoo
spec:
  volumeName: kyoo-media-anime-nfs-storage
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
