apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: kyoo-front
  namespace: kyoo
  labels:
    helm.sh/chart: kyoo-5.0.0
    app.kubernetes.io/name: kyoo-front
    app.kubernetes.io/instance: kyoo
    app.kubernetes.io/component: front
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyoo
    app.kubernetes.io/version: "5.0.0"
