apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postfix
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: postfix
    {{- include "custom.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postfix
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: audiobookshelf
          podSelector:
            matchLabels:
              app.kubernetes.io/name: audiobookshelf
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: grimmory
          podSelector:
            matchLabels:
              app.kubernetes.io/name: grimmory
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: pocket-id-operator
          podSelector:
            matchLabels:
              app.kubernetes.io/name: pocket-id
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: vaultwarden
          podSelector:
            matchLabels:
              app.kubernetes.io/name: vaultwarden
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gitea
          podSelector:
            matchLabels:
              app.kubernetes.io/name: gitea
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: dawarich
          podSelector:
            matchLabels:
              app.kubernetes.io/name: dawarich
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: trek
          podSelector:
            matchLabels:
              app.kubernetes.io/name: trek
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: immich
          podSelector:
            matchLabels:
              app.kubernetes.io/name: immich
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: outline
          podSelector:
            matchLabels:
              app.kubernetes.io/name: outline
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: home-assistant
          podSelector:
            matchLabels:
              app.kubernetes.io/name: home-assistant
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: postiz
          podSelector:
            matchLabels:
              app.kubernetes.io/name: postiz
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: reactive-resume
          podSelector:
            matchLabels:
              app.kubernetes.io/name: reactive-resume
      ports:
        - protocol: TCP
          port: 25
        - protocol: TCP
          port: 587
