kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: thanos-compact-data
  labels:
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-5.2.1
  namespace: thanos
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "30Gi"
  storageClassName: "ceph-block"
