apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-store
  labels:
    app.kubernetes.io/controller: store
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-5.2.1
  namespace: thanos
spec:
  revisionHistoryLimit: 3
  replicas:
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/controller: store
      app.kubernetes.io/name: thanos
      app.kubernetes.io/instance: thanos
  serviceName: thanos
  template:
    metadata:
      labels:
        app.kubernetes.io/controller: store
        app.kubernetes.io/instance: thanos
        app.kubernetes.io/name: thanos
    spec:
      enableServiceLinks: false
      serviceAccountName: thanos
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1001
        runAsUser: 1001
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - args:
            - store
            - --http-address=0.0.0.0:9090
            - --grpc-address=0.0.0.0:10901
            - --data-dir=/var/thanos/store
            - --objstore.config-file=/etc/thanos/thanos.yaml
          image: thanosio/thanos:v0.42.4@sha256:b567818fe608067eb0f1d7c2c4fe361e7ad83c8a256234c97685f1d0bf670cc8
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
          name: main
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 50m
              memory: 256Mi
          volumeMounts:
            - mountPath: /etc/thanos/thanos.yaml
              name: objstore-config
              readOnly: true
              subPath: thanos.yaml
            - mountPath: /var/thanos/store
              name: store-cache
      volumes:
        - name: objstore-config
          secret:
            secretName: thanos-objstore-secret
        - emptyDir: {}
          name: store-cache
