---
name: blackbox-exporter
services:
  blackbox-exporter:
    image: quay.io/prometheus/blackbox-exporter:v0.29.0@sha256:9613f2884689b6fad9f1939f6a3b0388c93a022cfaededb19545b329b5c83dea
    container_name: blackbox-exporter
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml:ro
    ports:
      - '0.0.0.0:9115:9115'
    command:
      - --config.file=/etc/blackbox_exporter/config.yml
    restart: always
