apiVersion: v1
kind: ServiceAccount
metadata:
  name: music-grabber
  labels:
    app.kubernetes.io/instance: music-grabber
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: music-grabber
    helm.sh/chart: music-grabber-5.0.0
  namespace: music-grabber
