apiVersion: apps/v1
kind: Deployment
metadata:
  name: whodb
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: whodb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: whodb
    helm.sh/chart: whodb-5.0.1
  namespace: whodb
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/name: whodb
      app.kubernetes.io/instance: whodb
  template:
    metadata:
      labels:
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: whodb
        app.kubernetes.io/name: whodb
    spec:
      enableServiceLinks: false
      serviceAccountName: whodb
      automountServiceAccountToken: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - env:
            - name: WHODB_OLLAMA_HOST
              value: ollama-server-2.ollama
            - name: WHODB_OLLAMA_PORT
              value: "11434"
          image: clidey/whodb:0.116.0@sha256:398185b5933fb5cfdb6d5a9c5345dd3e60673a6014afe7f14b1a936bd87c547f
          name: main
          resources:
            requests:
              cpu: 1m
              memory: 20Mi
