{
 "title": "Radarr",
 "tags": [
  "application",
  "movies"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Instance",
    "query": {
     "query": "label_values(radarr_system_status,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Movies Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 16, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(radrr_queue_total{namespace=\"$namespace\"} OR on() vector(0)) by (namespace)",
     "legendFormat": "Queued"
    },
    {
     "expr": "sum(radarr_history_total{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Movies",
   "type": "stat",
   "gridPos": { "h": 16, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(radarr_movie_missing_total{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "Missing"
    },
    {
     "expr": "sum(radarr_movie_monitored_total{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "Monitored"
    },
    {
     "expr": "sum(radarr_movie_total{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Episode quality",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 11, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(radarr_movie_quality_total{namespace=\"$namespace\"}) by (quality))",
     "legendFormat": "{{ quality }}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Storage Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(radarr_movie_filesize_total{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(radarr_rootfolder_freespace_bytes{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}