s3-exporter:
  controllers:
    a-ps02sn:
      type: deployment
      strategy: Recreate
      containers:
        main:
          image:
            repository: molu8bits/s3bucket_exporter
            tag: 1.0.2@sha256:75fc839c5f12cdbf20babab534959c96356b4483743e730409132bbda6944505
          env:
            - name: S3_NAME
              value: a-ps02sn
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: a-ps02sn
                  key: ENDPOINT
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: a-ps02sn
                  key: AWS_ACCESS_KEY_ID
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: a-ps02sn
                  key: AWS_SECRET_ACCESS_KEY
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: a-ps02sn
                  key: AWS_REGION
            - name: LOG_LEVEL
              value: debug
            - name: S3_FORCE_PATH_STYLE
              value: true
          resources:
            requests:
              cpu: 1m
              memory: 20Mi
    b-cl01tl:
      type: deployment
      strategy: Recreate
      containers:
        main:
          image:
            repository: molu8bits/s3bucket_exporter
            tag: 1.0.2@sha256:75fc839c5f12cdbf20babab534959c96356b4483743e730409132bbda6944505
          env:
            - name: S3_NAME
              value: b-cl01tl
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: b-cl01tl
                  key: ENDPOINT
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: b-cl01tl
                  key: AWS_ACCESS_KEY_ID
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: b-cl01tl
                  key: AWS_SECRET_ACCESS_KEY
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: b-cl01tl
                  key: AWS_REGION
            - name: LOG_LEVEL
              value: debug
            - name: S3_FORCE_PATH_STYLE
              value: true
          resources:
            requests:
              cpu: 1m
              memory: 20Mi
    c-ps10rp:
      type: deployment
      strategy: Recreate
      containers:
        main:
          image:
            repository: molu8bits/s3bucket_exporter
            tag: 1.0.2@sha256:75fc839c5f12cdbf20babab534959c96356b4483743e730409132bbda6944505
          env:
            - name: S3_NAME
              value: c-ps10rp
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: c-ps10rp
                  key: ENDPOINT
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: c-ps10rp
                  key: AWS_ACCESS_KEY_ID
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: c-ps10rp
                  key: AWS_SECRET_ACCESS_KEY
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: c-ps10rp
                  key: AWS_REGION
            - name: LOG_LEVEL
              value: debug
            - name: S3_FORCE_PATH_STYLE
              value: true
          resources:
            requests:
              cpu: 1m
              memory: 20Mi
    d-cs01bb:
      type: deployment
      strategy: Recreate
      containers:
        main:
          image:
            repository: molu8bits/s3bucket_exporter
            tag: 1.0.2@sha256:75fc839c5f12cdbf20babab534959c96356b4483743e730409132bbda6944505
          env:
            - name: S3_NAME
              value: d-cs01bb
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: d-cs01bb
                  key: ENDPOINT
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: d-cs01bb
                  key: AWS_ACCESS_KEY_ID
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: d-cs01bb
                  key: AWS_SECRET_ACCESS_KEY
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: d-cs01bb
                  key: AWS_REGION
            - name: LOG_LEVEL
              value: info
            - name: S3_FORCE_PATH_STYLE
              value: false
          resources:
            requests:
              cpu: 1m
              memory: 20Mi
  service:
    a-ps02sn:
      controller: a-ps02sn
      ports:
        metrics:
          port: 9655
    b-cl01tl:
      controller: b-cl01tl
      ports:
        metrics:
          port: 9655
    c-ps10rp:
      controller: c-ps10rp
      ports:
        metrics:
          port: 9655
    d-cs01bb:
      controller: d-cs01bb
      ports:
        metrics:
          port: 9655
  serviceMonitor:
    a-ps02sn:
      serviceName: a-ps02sn
      endpoints:
        - port: metrics
          interval: 30m
          scrapeTimeout: 2m
    b-cl01tl:
      serviceName: b-cl01tl
      endpoints:
        - port: metrics
          interval: 30m
          scrapeTimeout: 2m
    c-ps10rp:
      serviceName: c-ps10rp
      endpoints:
        - port: metrics
          interval: 30m
          scrapeTimeout: 2m
    d-cs01bb:
      serviceName: d-cs01bb
      endpoints:
        - port: metrics
          interval: 6h
          scrapeTimeout: 5m
