apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: docs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: docs
    helm.sh/chart: docs-5.0.1
  namespace: docs
spec:
  revisionHistoryLimit: 3
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/name: docs
      app.kubernetes.io/instance: docs
  template:
    metadata:
      labels:
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: docs
        app.kubernetes.io/name: docs
    spec:
      enableServiceLinks: false
      serviceAccountName: docs
      automountServiceAccountToken: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - image: harbor.alexlebens.net/images/docs:1.16.0@sha256:2e09319ec5506b1e241f02ec7ce6bc0f4b67e84800837d73e83c38e4ef0273f7
          name: main
          resources:
            requests:
              cpu: 1m
              memory: 60Mi
