apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docs-cloudflared-secret
  namespace: docs
  labels:
    helm.sh/chart: cloudflared-3.4.1
    app.kubernetes.io/instance: docs
    app.kubernetes.io/part-of: docs
    app.kubernetes.io/version: "3.4.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: docs-cloudflared-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: cf-tunnel-token
      remoteRef:
        key: /cloudflare/tunnels/docs
        property: token
