apiVersion: v2
name: isponsorblocktv
version: 1.0.0
description: iSponsorBlockTV
keywords:
  - isponsorblocktv
  - purpose
home: https://docs.alexlebens.dev/applications/isponsorblocktv/
sources:
  - https://github.com/dmunozv04/iSponsorBlockTV
  - https://github.com/dmunozv04/iSponsorBlockTV/pkgs/container/isponsorblocktv
  - https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
maintainers:
  - name: alexlebens
dependencies:
  - name: app-template
    alias: isponsorblocktv
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 4.6.2
icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/youtube.png
# renovate: datasource=github-releases depName=dmunozv04/iSponsorBlockTV
appVersion: v2.7.0
