isponsorblocktv:
  controllers:
    main:
      type: deployment
      strategy: Recreate
      pod:
        automountServiceAccountToken: true
      containers:
        main:
          image:
            repository: ghcr.io/dmunozv04/isponsorblocktv
            tag: v2.11.0@sha256:d1e876636754fb2b54490feebe3af4a321f7f2a932a2d57b67b2a667eea40823
          resources:
            requests:
              cpu: 1m
              memory: 50Mi
  persistence:
    config:
      type: custom
      volumeSpec:
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: isponsorblocktv-config
      advancedMounts:
        main:
          main:
            - path: /app/data/config.json
              readOnly: true
              mountPropagation: None
              subPath: config.json
