tdarr:
  controllers:
    server:
      type: deployment
      replicas: 1
      strategy: Recreate
      pod:
        securityContext:
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
      containers:
        main:
          image:
            repository: ghcr.io/haveagitgat/tdarr
            tag: 2.68.01@sha256:db9520315f83974cb5b8f2a8ed89a8a2be3d97d29575f54cbe4b5cc5e6daf5a5
          env:
            - name: TZ
              value: America/Chicago
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
            - name: UMASK_SET
              value: "002"
            - name: ffmpegVersion
              value: "6"
            - name: internalNode
              value: "false"
            - name: inContainer
              value: "true"
            - name: nodeName
              value: tdarr-server
            - name: serverIP
              value: 0.0.0.0
            - name: serverPort
              value: "8266"
            - name: webUIPort
              value: "8265"
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
    node:
      type: statefulset
      replicas: 3
      statefulset:
        volumeClaimTemplates:
          - name: transcode-cache
            accessMode: ReadWriteOnce
            size: 20Gi
            storageClass: local-path
            globalMounts:
              - path: /tcache
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/instance
                      operator: In
                      values:
                        - node
                topologyKey: kubernetes.io/hostname
        nodeSelector:
          intel.feature.node.kubernetes.io/gpu: "true"
      containers:
        main:
          image:
            repository: ghcr.io/haveagitgat/tdarr_node
            tag: 2.68.01@sha256:6359991d297ec23e2a5fe3a6b5b19c65d9eabdc63172d2cbe6aa576bbe5356c2
          env:
            - name: TZ
              value: America/Chicago
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
            - name: UMASK_SET
              value: "002"
            - name: ffmpegVersion
              value: "6"
            - name: inContainer
              value: "true"
            - name: nodeName
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: serverIP
              value: tdarr-api
            - name: serverPort
              value: "8266"
          resources:
            limits:
              gpu.intel.com/i915: 1
            requests:
              gpu.intel.com/i915: 1
              cpu: 10m
              memory: 100Mi
  service:
    api:
      controller: server
      ports:
        http:
          port: 8266
          targetPort: 8266
    web:
      controller: server
      ports:
        http:
          port: 8265
          targetPort: 8265
  route:
    main:
      kind: HTTPRoute
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway
          namespace: traefik
      hostnames:
        - tdarr.alexlebens.net
      rules:
        - backendRefs:
            - name: tdarr-web
              port: 8265
          matches:
            - path:
                type: PathPrefix
                value: /
  persistence:
    config:
      forceRename: tdarr-config
      storageClass: ceph-block
      accessMode: ReadWriteOnce
      size: 50Gi
      advancedMounts:
        server:
          main:
            - path: /app/configs
              readOnly: false
    server:
      forceRename: tdarr-server
      storageClass: ceph-block
      accessMode: ReadWriteOnce
      size: 50Gi
      advancedMounts:
        server:
          main:
            - path: /app/server
              readOnly: false
    server-cache:
      type: emptyDir
      advancedMounts:
        server:
          main:
            - path: /tcache
              readOnly: false
    media:
      existingClaim: tdarr-nfs-storage
      advancedMounts:
        server:
          main:
            - path: /mnt/store
              readOnly: true
        node:
          main:
            - path: /mnt/store
              readOnly: true
tdarr-exporter:
  image:
    name: homeylab/tdarr-exporter
    tag: 1.4.3@sha256:88254cb505bfff20e86e04fa23a71789a411e7939e3bcbccbd5ef397ff91d052
  metrics:
    serviceMonitor:
      enabled: true
  settings:
    config:
      url: http://tdarr-web.tdarr:8265
      verify_ssl: false
  resources:
    requests:
      cpu: 1m
      memory: 10Mi
volsync-target-config:
  pvcTarget: tdarr-config
  local:
    enabled: true
    schedule: 30 11 * * *
  remote:
    enabled: true
    schedule: 30 12 * * *
  external:
    enabled: true
    schedule: 30 13 * * *
volsync-target-server:
  pvcTarget: tdarr-server
  local:
    enabled: true
    schedule: 32 11 * * *
  remote:
    enabled: true
    schedule: 32 12 * * *
  external:
    enabled: true
    schedule: 32 13 * * *
