apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-runner-configmap
  namespace: gitea
  labels:
    helm.sh/chart: gitea-actions-0.1.1
    app: gitea-actions
    app.kubernetes.io/name: gitea-actions
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/version: "0.261.3"
    version: "0.261.3"
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    log:
      level: debug
    cache:
      enabled: false
    container:
      require_docker: true
      docker_timeout: 300s
