apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-assets-secret-backup-primary
  namespace: gitea
  labels:
    app.kubernetes.io/name: gitea-assets-secret-backup-primary
    helm.sh/chart: garage-bucket-gitea-assets-0.3.11
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/part-of: gitea
    app.kubernetes.io/version: "v0.7.6"
    app.kubernetes.io/managed-by: Helm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /garage/home-infra/gitea-assets
        property: ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /garage/home-infra/gitea-assets
        property: ACCESS_SECRET_KEY
    - secretKey: AWS_REGION
      remoteRef:
        key: /garage/home-infra/gitea-assets
        property: ACCESS_REGION
