apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-meilisearch-key
  namespace: gitea
  labels:
    app.kubernetes.io/name: gitea-meilisearch-key
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/part-of: gitea
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    template:
      mergePolicy: Merge
      engineVersion: v2
      data:
        ISSUE_INDEXER_CONN_STR: "http://:{{ .MEILI_MASTER_KEY }}@gitea-meilisearch.gitea:7700/"
  data:
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: /cl01tl/gitea/meilisearch
        property: master-key
