apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildx-runner
  namespace: gitea
  labels:
    app.kubernetes.io/name: buildx-runner
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/part-of: gitea
