apiVersion: v1
kind: ServiceAccount
metadata:
  name: anubis
  labels:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: anubis
    helm.sh/chart: anubis-5.0.1
  namespace: gitea
