apiVersion: v1
kind: Service
metadata:
  name: anubis
  labels:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: anubis
    app.kubernetes.io/service: anubis
    helm.sh/chart: anubis-5.0.1
  namespace: gitea
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: anubis
