apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: gitea-ssh.alexlebens.net
  labels:
    helm.sh/chart: gitea-12.7.0
    app: gitea
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/version: "1.27.1"
    version: "1.27.1"
    app.kubernetes.io/managed-by: Helm
  name: gitea
  namespace: gitea
spec:
  parentRefs:
    - name: cilium-ssh-gateway
      namespace: kube-system
      sectionName: ssh
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: gitea-ssh
          port: 22
          weight: 1
