apiVersion: v1
kind: ServiceAccount
metadata:
  name: bazarr
  labels:
    app.kubernetes.io/instance: bazarr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: bazarr
    helm.sh/chart: bazarr-5.0.1
  namespace: bazarr
