apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-ui-jwt-key
  namespace: garage-b
  labels:
    app.kubernetes.io/name: garage-ui-jwt-key
    app.kubernetes.io/instance: garage-b
    app.kubernetes.io/part-of: garage-b
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: jwt-key.pem
      remoteRef:
        key: /cl01tl/garage-b/key
        property: ui-cluster-b-jwt-key.pem
