apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-ps08rp-garage-b-http-2xx
  namespace: garage-b
  labels:
    app.kubernetes.io/name: blackbox-ps08rp-garage-b-http-2xx
    app.kubernetes.io/instance: garage-b
    app.kubernetes.io/part-of: garage-b
spec:
  prober:
    url: ps08rp.alexlebens.dev:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - https://b-ui.s3.alexlebens.dev
