democratic-csi:
  driver:
    image:
      registry: ghcr.io/democratic-csi/democratic-csi
      tag: v1.9.5@@sha256:fc3b7d7ed3a616714139525075312758e23a5d425ffb539ad12c9bd20fb6001f
    existingConfigSecret: synology-iscsi-config-secret
    config:
      driver: synology-iscsi
    resources:
      requests:
        cpu: 1m
        memory: 128Mi
  csiDriver:
    name: "org.democratic-csi.iscsi-synology"
  controller:
    replicaCount: 3
    externalAttacher:
      image:
        registry: registry.k8s.io/sig-storage/csi-attacher
        tag: v4.11.0@sha256:b74b05b39501565022883fc128002b4cb857a7bb6c858606bcb3fdedba0b0b80
    externalProvisioner:
      image:
        registry: registry.k8s.io/sig-storage/csi-provisioner
        tag: v3.6.4@sha256:e7ad666f1d9b0caa077c7f0c157c9f87d1e73858390732496f66dcc716ff10c5
    externalResizer:
      image:
        registry: registry.k8s.io/sig-storage/csi-resizer
        tag: v1.9.4@sha256:522911ef68bd2c5c17d90fb2a6d2b2fb72ae790f2c1463a466b4262a07fdbf5a
    externalSnapshotter:
      image:
        registry: registry.k8s.io/sig-storage/csi-snapshotter
        tag: v8.5.0@sha256:da081c27e8a6d91f36042c1942362d0515ced8d06e18c11b8f893e58c4d6d797
  storageClasses:
    - name: synology-iscsi-delete
      defaultClass: false
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: ext4
    - name: synology-iscsi-retain
      defaultClass: false
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: ext4
  node:
    hostPID: true
    driver:
      extraEnv:
        - name: ISCSIADM_HOST_STRATEGY
          value: nsenter
        - name: ISCSIADM_HOST_PATH
          value: /usr/local/sbin/iscsiadm
      iscsiDirHostPath: /var/iscsi
      iscsiDirHostPathType: ""
  driverRegistrar:
    image:
      registry: registry.k8s.io/sig-storage/csi-node-driver-registrar
      tag: v2.16.0@sha256:ab482308a4921e28a6df09a16ab99a457e9af9641ff44fb1be1a690d07ce8b70
