external-secrets:
  replicaCount: 3
  image:
    repository: ghcr.io/external-secrets/external-secrets
    tag: v2.10.0@sha256:814117b0fd6d121b03e8ba3b6db1cecbe7449a354fc0fc9c4faf73a37aa221b1
  leaderElect: true
  extendedMetricLabels: true
  resources:
    requests:
      cpu: 5m
      memory: 50Mi
  serviceMonitor:
    enabled: true
  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  webhook:
    image:
      repository: ghcr.io/external-secrets/external-secrets
      tag: v2.10.0@sha256:814117b0fd6d121b03e8ba3b6db1cecbe7449a354fc0fc9c4faf73a37aa221b1
    resources:
      requests:
        cpu: 1m
        memory: 30Mi
  certController:
    image:
      repository: ghcr.io/external-secrets/external-secrets
      tag: v2.10.0@sha256:814117b0fd6d121b03e8ba3b6db1cecbe7449a354fc0fc9c4faf73a37aa221b1
    resources:
      requests:
        cpu: 1m
        memory: 60Mi
