external-secrets:
  replicaCount: 3
  image:
    repository: ghcr.io/external-secrets/external-secrets
    tag: v2.12.0@sha256:7a3c4f7e038fa0f86a3172da19b9388f3f4d846e87e9994ee3474c5b72a9330d
  leaderElect: true
  extendedMetricLabels: true
  resources:
    requests:
      cpu: 5m
      memory: 50Mi
  serviceMonitor:
    enabled: true
  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  webhook:
    image:
      repository: ghcr.io/external-secrets/external-secrets
      tag: v2.12.0@sha256:7a3c4f7e038fa0f86a3172da19b9388f3f4d846e87e9994ee3474c5b72a9330d
    resources:
      requests:
        cpu: 1m
        memory: 30Mi
  certController:
    image:
      repository: ghcr.io/external-secrets/external-secrets
      tag: v2.12.0@sha256:7a3c4f7e038fa0f86a3172da19b9388f3f4d846e87e9994ee3474c5b72a9330d
    resources:
      requests:
        cpu: 1m
        memory: 60Mi
