external-secrets:
  replicaCount: 1
  image:
    repository: ghcr.io/external-secrets/external-secrets
    tag: v2.2.0@sha256:876e627dbee5b0edd12da49b035469d12418cd6c3c4be5e383ae6a82e8bd4565
  installCRDs: true
  crds:
    createClusterExternalSecret: true
    createClusterSecretStore: true
    createSecretStore: true
    createClusterGenerator: true
    createClusterPushSecret: true
    createPushSecret: true
  leaderElect: true
  extendedMetricLabels: true
  resources:
    requests:
      cpu: 5m
      memory: 50Mi
  serviceMonitor:
    enabled: true
  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  webhook:
    image:
      repository: ghcr.io/external-secrets/external-secrets
      tag: v2.2.0@sha256:876e627dbee5b0edd12da49b035469d12418cd6c3c4be5e383ae6a82e8bd4565
    resources:
      requests:
        cpu: 1m
        memory: 30Mi
  certController:
    image:
      repository: ghcr.io/external-secrets/external-secrets
      tag: v2.2.0@sha256:876e627dbee5b0edd12da49b035469d12418cd6c3c4be5e383ae6a82e8bd4565
    resources:
      requests:
        cpu: 1m
        memory: 60Mi
