apiVersion: v2
name: volsync
version: 1.0.0
description: Volsync
keywords:
  - volsync
home: https://docs.alexlebens.dev/Applications/cl01tl/volsync/
sources:
  - https://github.com/backube/volsync
  - https://quay.io/repository/backube/volsync?tab=tags
  - https://github.com/backube/volsync/tree/main/helm/volsync
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/s3-bucket
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/common-helpers
maintainers:
  - name: alexlebens
dependencies:
  - name: volsync
    repository: https://backube.github.io/helm-charts/
    version: 0.16.0
  - name: s3-bucket
    repository: oci://harbor.alexlebens.dev/helm-charts
    version: 0.8.0
  - name: common-helpers
    repository: oci://harbor.alexlebens.dev/helm-charts
    version: 1.2.0
icon: https://raw.githubusercontent.com/backube/volsync/main/docs/media/volsync.svg?sanitize=true
# renovate: datasource=github-releases depName=backube/volsync
appVersion: 0.16.0
