apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-backups-rclone-destination-config
  namespace: cloudnative-pg
  labels:
    helm.sh/chart: rclone-postgres-backups-remote-0.4.2
    app.kubernetes.io/instance: cloudnative-pg
    app.kubernetes.io/part-of: cloudnative-pg
    app.kubernetes.io/version: "0.4.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgres-backups-rclone-destination-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: /garage/home-infra/postgres-backups
        property: ACCESS_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: /garage/home-infra/postgres-backups
        property: ACCESS_SECRET_KEY
    - secretKey: ACCESS_REGION
      remoteRef:
        key: /garage/home-infra/postgres-backups
        property: ACCESS_REGION
    - secretKey: DEST_ENDPOINT
      remoteRef:
        key: /garage/config
        property: ENDPOINT_REMOTE
