apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudnative-pg-postgres-backups-external-rclone
  labels:
    app.kubernetes.io/instance: cloudnative-pg
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgres-backups-external-rclone
    app.kubernetes.io/version: v1.74.1
    helm.sh/chart: rclone-postgres-backups-external-0.11.5
  namespace: cloudnative-pg
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - cloudnative-pg
  selector:
    matchLabels:
      app.kubernetes.io/instance: cloudnative-pg
      app.kubernetes.io/name: postgres-backups-external-rclone
  endpoints:
    - interval: 10s
      path: /metrics
      port: rc-sync
      scrapeTimeout: 5s
    - interval: 10s
      path: /metrics
      port: rc-prune
      scrapeTimeout: 5s
