apiVersion: garage.rajsingh.info/v1beta1
kind: GarageReferenceGrant
metadata:
  name: reactive-resume-assets-grant
  namespace: garage-operator
  labels:
    app.kubernetes.io/name: reactive-resume-assets-grant
    helm.sh/chart: garage-bucket-reactive-resume-assets-0.3.10
    app.kubernetes.io/instance: reactive-resume
    app.kubernetes.io/part-of: reactive-resume
    app.kubernetes.io/version: "v0.7.5"
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  from:
    - kind: GarageKey
      namespace: reactive-resume
    - kind: GarageBucket
      namespace: reactive-resume
  to:
    - kind: GarageCluster
      name: garage-cluster-a
