apiVersion: v1
kind: ServiceAccount
metadata:
  name: reactive-resume-valkey
  labels:
    helm.sh/chart: valkey-0.11.0
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: reactive-resume
    app.kubernetes.io/version: "9.1.1"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: false
