apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: talos-etcd-backup-external-config
  namespace: talos
  labels:
    app.kubernetes.io/name: talos-etcd-backup-external-config
    app.kubernetes.io/instance: talos
    app.kubernetes.io/part-of: talos
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /digital-ocean/home-infra/talos-backups
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /digital-ocean/home-infra/talos-backups
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_REGION
      remoteRef:
        key: /digital-ocean/home-infra/talos-backups
        property: AWS_REGION
    - secretKey: BUCKET_NAME
      remoteRef:
        key: /digital-ocean/home-infra/talos-backups
        property: BUCKET
    - secretKey: BUCKET
      remoteRef:
        key: /digital-ocean/home-infra/talos-backups
        property: BUCKET_PATH
    - secretKey: AGE_X25519_PUBLIC_KEY
      remoteRef:
        key: /cl01tl/talos/etcd-backup
        property: AGE_X25519_PUBLIC_KEY
