apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: garage-operator-webhook-cert
  namespace: garage-operator
  labels:
    helm.sh/chart: garage-operator-0.7.3
    app.kubernetes.io/name: garage-operator
    app.kubernetes.io/instance: garage-operator
    control-plane: controller-manager
    app.kubernetes.io/version: "0.7.3"
    app.kubernetes.io/managed-by: Helm
spec:
  secretName: garage-operator-webhook-cert
  dnsNames:
    - garage-operator-webhook
    - garage-operator-webhook.garage-operator
    - garage-operator-webhook.garage-operator.svc
    - garage-operator-webhook.garage-operator.svc.cluster.local
  issuerRef:
    name: garage-operator-selfsigned-issuer
    kind: Issuer
  duration: 8760h
  renewBefore: 720h
