apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-ui-cluster-a-jwt-key
  namespace: garage-operator
  labels:
    app.kubernetes.io/name: garage-ui-cluster-a-jwt-key
    app.kubernetes.io/instance: garage-operator
    app.kubernetes.io/part-of: garage-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: jwt-key.pem
      remoteRef:
        key: /cl01tl/garage-operator/key
        property: ui-cluster-a-jwt-key.pem
