apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-cluster-a-ui-oidc
  namespace: garage-operator
  labels:
    app.kubernetes.io/name: garage-cluster-a-ui-oidc
    app.kubernetes.io/instance: garage-operator
    app.kubernetes.io/part-of: garage-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: clientSecret
      remoteRef:
        key: /cl01tl/pocket-id/oidc/garage-operator/cluster-a
        property: clientSecret
