apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: garage-operator-s3
  namespace: garage-operator
  labels:
    app.kubernetes.io/name: garage-operator-s3
    app.kubernetes.io/instance: garage-operator
    app.kubernetes.io/part-of: garage-operator
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: traefik
  hostnames:
    - "s3.alexlebens.net"
    - "*.s3.alexlebens.net"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: garage-cluster-a
          port: 3900
