apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-cl01tl-garage-operator-http-2xx
  namespace: garage-operator
  labels:
    app.kubernetes.io/name: blackbox-cl01tl-garage-operator-http-2xx
    app.kubernetes.io/instance: garage-operator
    app.kubernetes.io/part-of: garage-operator
spec:
  prober:
    url: kube-prometheus-stack-prometheus-blackbox-exporter.kube-prometheus-stack.svc.cluster.local:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - http://garage-ui-cluster-a.garage-operator:80
        - http://garage-ui-cluster-b.garage-operator:80
