apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: garage-cluster-a
  namespace: garage-operator
  labels:
    app.kubernetes.io/name: garage-cluster-a
    app.kubernetes.io/instance: garage-operator
    app.kubernetes.io/part-of: garage-operator
spec:
  selector:
    matchLabels:
      garage.rajsingh.info/cluster: garage-cluster-a
  endpoints:
    - port: admin
      interval: 5m
      scrapeTimeout: 2m
      bearerTokenSecret:
        name: garage-operator-token
        key: metrics-token
