apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: qbittorrent
  namespace: qbittorrent
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: qbittorrent
    app.kubernetes.io/part-of: qbittorrent
spec:
  name: "qBittorrent"
  launchUrl: https://qbittorrent.alexlebens.net
  description: "An open-source BitTorrent client."
  callbackUrls:
    - https://qbittorrent.alexlebens.net/oauth2/callback
  pkceEnabled: true
  skipConsent: true
  allowedUserGroups:
    - name: admin
      namespace: pocket-id-operator
  clientID: 2C3D83D2-C0CF-4301-B16B-F96D09C030BA
  clientSecretRef:
    name: qbittorrent-oauth-proxy
    key: OAUTH2_PROXY_CLIENT_SECRET
  logo:
    logoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/qbittorrent.webp
    darkLogoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/qbittorrent.webp
