apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-ps09rp-qbittorrent-http-2xx
  namespace: qbittorrent
  labels:
    app.kubernetes.io/name: blackbox-ps09rp-qbittorrent-http-2xx
    app.kubernetes.io/instance: qbittorrent
    app.kubernetes.io/part-of: qbittorrent
spec:
  prober:
    url: ps09rp.alexlebens.net:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - https://qbittorrent.alexlebens.net
        - https://qui.alexlebens.net
