apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: qbittorrent-qui-config-data-backup-source-c
  namespace: qbittorrent
  labels:
    helm.sh/chart: volsync-target-qui-config-3.0.0
    app.kubernetes.io/instance: qbittorrent
    app.kubernetes.io/part-of: qbittorrent
    app.kubernetes.io/version: "0.16.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: qbittorrent-qui-config-data-backup-source-c
spec:
  sourcePVC: qbittorrent-qui-config-data
  trigger:
    schedule: 55 10 * * 6
  restic:
    pruneIntervalDays: 7
    repository: qbittorrent-qui-config-data-backup-secret-c
    retain:
      daily: 0
      hourly: 0
      monthly: 0
      weekly: 12
      yearly: 0
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-blockpool-snapshot
    cacheCapacity: 1Gi
