apiVersion: v2
name: karakeep
version: 1.0.0
description: Karakeep
keywords:
  - karakeep
  - bookmarks
home: https://docs.alexlebens.dev/applications/karakeep/
sources:
  - https://github.com/karakeep-app/karakeep
  - https://github.com/jlandure/alpine-chrome
  - https://github.com/karakeep-app/karakeep/pkgs/container/karakeep
  - https://console.cloud.google.com/artifacts/docker/zenika-hub/us/gcr.io/alpine-chrome
  - https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
  - https://github.com/meilisearch/meilisearch-kubernetes/tree/main/charts/meilisearch
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/cloudflared
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/volsync-target
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/rclone-bucket
maintainers:
  - name: alexlebens
dependencies:
  - name: app-template
    alias: karakeep
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 4.6.2
  - name: meilisearch
    version: 0.32.0
    repository: https://meilisearch.github.io/meilisearch-kubernetes
  - name: cloudflared
    repository: oci://harbor.alexlebens.net/helm-charts
    version: 2.6.0
  - name: volsync-target
    alias: volsync-target-data
    version: 1.0.0
    repository: oci://harbor.alexlebens.net/helm-charts
  - name: rclone-bucket
    alias: rclone-karakeep-assets-remote
    repository: oci://harbor.alexlebens.net/helm-charts
    version: 0.2.0
icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/karakeep.png
# renovate: datasource=github-releases depName=karakeep-app/karakeep
appVersion: 0.31.0
