apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: bgp-ip-pool
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: bgp-ip-pool
    {{- include "custom.labels" . | nindent 4 }}
spec:
  blocks:
    - start: "10.234.0.30"
      stop: "10.234.0.39"
