apiVersion: v2
name: talos
version: 1.0.0
description: Talos
keywords:
  - talos
  - operating-system
  - job
home: https://docs.alexlebens.dev/applications/talos/
sources:
  - https://github.com/siderolabs/talos
  - https://github.com/siderolabs/talos-backup
  - https://github.com/Angatar/s3cmd
  - https://github.com/siderolabs/talos/pkgs/container/talosctl
  - https://github.com/siderolabs/talos-backup/pkgs/container/talos-backup
  - https://hub.docker.com/r/d3fk/s3cmd
  - https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
maintainers:
  - name: alexlebens
dependencies:
  - name: app-template
    alias: etcd-backup
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 4.6.2
  - name: app-template
    alias: etcd-defrag
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 4.6.2
icon: https://raw.githubusercontent.com/siderolabs/docs/3989ed11f0622252d7cee03b3ba3a3052be242d7/public/images/talos.svg
# renovate: datasource=github-releases depName=siderolabs/talos-backup
appVersion: v0.1.0-beta.3-7-ge8e193c
