apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-ps09rp-jellyfin-http-2xx
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: blackbox-ps09rp-jellyfin-http-2xx
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/part-of: jellyfin
spec:
  prober:
    url: ps09rp.alexlebens.net:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - https://jellyfin.alexlebens.net
