apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: n8n-postgres-pgvector-database-app
  namespace: n8n
  labels:
    app.kubernetes.io/name: n8n-postgres-pgvector-database-app
    helm.sh/chart: postgres-pgvector-cluster-8.5.0
    app.kubernetes.io/instance: n8n
    app.kubernetes.io/part-of: n8n
    app.kubernetes.io/version: "v1.30.1"
    app.kubernetes.io/managed-by: Helm
spec:
  name: app
  cluster:
    name: n8n-postgres-pgvector-cluster
  ensure: present
  owner: app
  template: template1
  encoding: UTF8
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
      ensure: present
    - name: vchord
      ensure: present
