apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: n8n-oauth2-proxy
  labels:
    app.kubernetes.io/instance: n8n
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: n8n
    helm.sh/chart: oauth2-proxy-5.1.0
  namespace: n8n
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - n8n
  selector:
    matchLabels:
      app.kubernetes.io/instance: n8n
      app.kubernetes.io/service: n8n-oauth2-proxy
  endpoints:
    - port: metrics
