apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: protonvpn-wireguard-conf
  namespace: tubearchivist
  labels:
    app.kubernetes.io/name: protonvpn-wireguard-conf
    app.kubernetes.io/instance: tubearchivist
    app.kubernetes.io/part-of: tubearchivist
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: conf
      remoteRef:
        key: /protonvpn/config
        property: conf
    - secretKey: email
      remoteRef:
        key: /protonvpn/config
        property: email
    - secretKey: password
      remoteRef:
        key: /protonvpn/config
        property: password
    - secretKey: private-key
      remoteRef:
        key: /protonvpn/config
        property: private-key
