apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tubearchivist-config
  namespace: tubearchivist
  labels:
    app.kubernetes.io/name: tubearchivist-config
    app.kubernetes.io/instance: tubearchivist
    app.kubernetes.io/part-of: tubearchivist
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: ELASTIC_PASSWORD
      remoteRef:
        key: /cl01tl/tubearchivist/elasticsearch
        property: password
    - secretKey: TA_PASSWORD
      remoteRef:
        key: /cl01tl/tubearchivist/config
        property: password
