apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    {{- include "custom.labels" . | nindent 4 }}
spec:
  name: "Vaultwarden"
  launchUrl: https://passwords{{ include "custom.domain" . }}
  description: "Alternative Bitwarden server implementation written in Rust."
  callbackUrls:
    - https://passwords{{ include "custom.domain" . }}/identity/connect/oidc-signin
  pkceEnabled: true
  skipConsent: true
  allowedUserGroups:
    - name: user
      namespace: pocket-id-operator
  clientID: 6F93B4CB-3042-4A84-8EBB-E1E8CB393F09
  clientSecretRef:
    name: {{ include "custom.defaultOidcSecret" . }}
    key: clientSecret
  logo:
    logoUrl: {{ include "custom.iconUrl" . }}vaultwarden.webp
    darkLogoUrl: {{ include "custom.iconUrl" . }}vaultwarden-light.webp
