apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foldergram-pictures-collection-mia-nfs-storage
  namespace: foldergram
  labels:
    app.kubernetes.io/name: foldergram-pictures-collection-mia-nfs-storage
    app.kubernetes.io/instance: foldergram
    app.kubernetes.io/part-of: foldergram
spec:
  volumeName: foldergram-pictures-collection-mia-nfs-storage
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
