apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-ps08rp-foldergram-http-2xx
  namespace: foldergram
  labels:
    app.kubernetes.io/name: blackbox-ps08rp-foldergram-http-2xx
    app.kubernetes.io/instance: foldergram
    app.kubernetes.io/part-of: foldergram
spec:
  prober:
    url: ps08rp.alexlebens.net:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - https://foldergram.alexlebens.net
