apiVersion: v1
kind: ServiceAccount
metadata:
  name: unpackerr
  labels:
    app.kubernetes.io/instance: unpackerr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: unpackerr
    helm.sh/chart: unpackerr-5.0.0
  namespace: unpackerr
