apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: unpackerr
  labels:
    app.kubernetes.io/instance: unpackerr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: unpackerr
    helm.sh/chart: unpackerr-5.1.0
  namespace: unpackerr
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - unpackerr
  selector:
    matchLabels:
      app.kubernetes.io/instance: unpackerr
      app.kubernetes.io/name: unpackerr
  endpoints:
    - interval: 5m
      port: metrics
