apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grimmory-mariadb-cluster-backup-secret-external
  namespace: grimmory
  labels:
    app.kubernetes.io/name: grimmory-mariadb-cluster-backup-secret-external
    app.kubernetes.io/instance: grimmory
    app.kubernetes.io/part-of: grimmory
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: access
      remoteRef:
        key: /digital-ocean/home-infra/mariadb-backups
        property: AWS_ACCESS_KEY_ID
    - secretKey: secret
      remoteRef:
        key: /digital-ocean/home-infra/mariadb-backups
        property: AWS_SECRET_ACCESS_KEY
