apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: grimmory-config-restore
  namespace: grimmory
  labels:
    app.kubernetes.io/name: grimmory-config-restore
    app.kubernetes.io/instance: grimmory
    app.kubernetes.io/part-of: grimmory
spec:
  trigger:
    manual: restore-once
  restic:
    repository: booklore-config-backup-secret-local
    destinationPVC: grimmory-config
    copyMethod: Direct
