apiVersion: v1
kind: ServiceAccount
metadata:
  name: grimmory
  labels:
    app.kubernetes.io/instance: grimmory
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grimmory
    helm.sh/chart: grimmory-5.0.0
  namespace: grimmory
