apiVersion: v1
kind: ServiceAccount
metadata:
  name: radarr
  labels:
    app.kubernetes.io/instance: radarr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: radarr
    helm.sh/chart: radarr-5.0.0
  namespace: radarr
