apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-cloudflared-secret
  namespace: karakeep
  labels:
    helm.sh/chart: cloudflared-2.6.0
    app.kubernetes.io/instance: karakeep
    app.kubernetes.io/part-of: karakeep
    app.kubernetes.io/version: "2.6.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karakeep-cloudflared-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: cf-tunnel-token
      remoteRef:
        key: /cloudflare/tunnels/karakeep
        property: token
