apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: karakeep
  namespace: karakeep
  labels:
    app.kubernetes.io/name: karakeep
    app.kubernetes.io/instance: karakeep
    app.kubernetes.io/part-of: karakeep
spec:
  name: "Karakeep"
  launchUrl: https://karakeep.alexlebens.dev
  description: "A self-hostable bookmark-everything app with a touch of AI for the data hoarders out there."
  callbackUrls:
    - https://karakeep.alexlebens.dev/api/auth/callback/custom
  pkceEnabled: false
  skipConsent: true
  allowedUserGroups:
    - name: user
      namespace: pocket-id-operator
  clientID: A8F3B91C-4D2E-4A87-B6C1-9E5F2D8A7C3B
  clientSecretRef:
    name: karakeep-oidc-secret
    key: clientSecret
  logo:
    logoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/karakeep.webp
    darkLogoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/karakeep-light.webp
