apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: karakeep-karakeep-assets-rclone
  labels:
    app.kubernetes.io/instance: karakeep
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karakeep-assets-rclone
    app.kubernetes.io/version: v1.74.4
    helm.sh/chart: rclone-karakeep-assets-remote-1.0.2
  namespace: karakeep
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - karakeep
  selector:
    matchLabels:
      app.kubernetes.io/instance: karakeep
      app.kubernetes.io/name: karakeep-assets-rclone
  podMetricsEndpoints:
    - interval: 10s
      path: /metrics
      port: rc-sync
      relabelings:
        - action: drop
          regex: Succeeded|Failed
          sourceLabels:
            - __meta_kubernetes_pod_phase
      scrapeTimeout: 5s
