apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: karakeep-karakeep-assets-external-rclone
  labels:
    app.kubernetes.io/instance: karakeep
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karakeep-assets-external-rclone
    app.kubernetes.io/version: v1.74.1
    helm.sh/chart: rclone-karakeep-assets-external-0.11.5
  namespace: karakeep
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - karakeep
  selector:
    matchLabels:
      app.kubernetes.io/instance: karakeep
      app.kubernetes.io/name: karakeep-assets-external-rclone
  endpoints:
    - interval: 10s
      path: /metrics
      port: rc-sync
      scrapeTimeout: 5s
    - interval: 10s
      path: /metrics
      port: rc-prune
      scrapeTimeout: 5s
