apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: karakeep-cloudflared
  labels:
    app.kubernetes.io/instance: karakeep
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/version: 2026.3.0
    helm.sh/chart: cloudflared-3.2.0
  namespace: karakeep
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - karakeep
  selector:
    matchLabels:
      app.kubernetes.io/instance: cloudflared
      app.kubernetes.io/name: cloudflared
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
      scrapeTimeout: 10s
