{{- range $prober := list "ps08rp" "ps09rp" }}
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-{{ $prober }}-{{ $.Release.Namespace }}-http-2xx
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: blackbox-{{ $prober }}-{{ $.Release.Namespace }}-http-2xx
    {{- include "custom.labels" $ | nindent 4 }}
spec:
  prober:
    url: {{ $prober }}.alexlebens.net:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - https://{{ index $.Values "jellyfin-testing" "httpRoute" "hostnames" 0 }}
{{- end }}
