apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stalwart
  labels:
    app.kubernetes.io/instance: stalwart
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stalwart
    helm.sh/chart: stalwart-4.6.2
  namespace: stalwart
spec:
  jobLabel: stalwart
  namespaceSelector:
    matchNames:
      - stalwart
  selector:
    matchLabels:
      app.kubernetes.io/instance: stalwart-metrics
      app.kubernetes.io/name: stalwart-metrics
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
      scrapeTimeout: 10s
