site-profile:
  global:
    fullnameOverride: site-profile
  controllers:
    main:
      type: deployment
      replicas: 3
      strategy: RollingUpdate
      containers:
        main:
          image:
            repository: harbor.alexlebens.net/images/site-profile
            tag: 3.17.0@sha256:22c5bebe1148c019cdd50c2da06d9e8679e1b2653762cb3f3febf1aba75c309f
          resources:
            requests:
              cpu: 10m
              memory: 60Mi
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
          targetPort: 4321
