site-profile:
  global:
    fullnameOverride: site-profile
  controllers:
    main:
      type: deployment
      replicas: 3
      strategy: RollingUpdate
      containers:
        main:
          image:
            repository: harbor.alexlebens.net/images/site-profile
            tag: 3.16.1@sha256:656182fade379a0e8f1e6780c36bb64fe1374afbc8f06894126043105f66d29a
          resources:
            requests:
              cpu: 10m
              memory: 60Mi
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
          targetPort: 4321
