site-profile:
  global:
    fullnameOverride: site-profile
  controllers:
    main:
      type: deployment
      replicas: 3
      strategy: RollingUpdate
      containers:
        main:
          image:
            repository: harbor.alexlebens.net/images/site-profile
            tag: 3.18.6@sha256:6aacdb7270d21b02d85cd593999014c91614e70c8f6f84774e532f9141237a6c
          resources:
            requests:
              cpu: 10m
              memory: 60Mi
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
          targetPort: 4321
