apiVersion: v2
name: docs
version: 1.0.0
description: docs
keywords:
  - docs
  - zensical
home: https://docs.alexlebens.dev/Applications/docs/
sources:
  - https://gitea.alexlebens.dev/alexlebens/docs
  - https://zensical.org/
  - https://harbor.alexlebens.dev/harbor/projects/11/repositories/docs
  - https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/cloudflared
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/common-helpers
maintainers:
  - name: alexlebens
dependencies:
  - name: app-template
    alias: docs
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 5.1.0
  - name: cloudflared
    repository: oci://harbor.alexlebens.dev/helm-charts
    version: 4.3.1
  - name: common-helpers
    repository: oci://harbor.alexlebens.dev/helm-charts
    version: 0.4.1
icon: https://web-assets.alexlebens.dev/logo/logo-blue.png
# renovate: datasource=gitea-releases registryUrl=https://gitea.alexlebens.dev depName=alexlebens/docs
appVersion: 1.29.0
