docs:
  global:
    fullnameOverride: docs
  controllers:
    main:
      type: deployment
      replicas: 3
      strategy: RollingUpdate
      containers:
        main:
          image:
            repository: harbor.alexlebens.dev/images/docs
            tag: 1.30.0@sha256:7a3c3924a2ba0769e47674ed188367a1b815723af942557b65abcae8f3e76c79
          resources:
            requests:
              cpu: 1m
              memory: 60Mi
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /
                  port: 8000
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /
                  port: 8000
  service:
    main:
      ports:
        http:
          port: 80
          targetPort: 8000
  route:
    main:
      kind: HTTPRoute
      parentRefs:
        - name: traefik-gateway
          namespace: traefik
      hostnames:
        - docs.alexlebens.dev
      rules:
        - backendRefs:
            - name: docs
              port: 80
cloudflared:
  probe:
    enabled: true
    targetUrl: https://docs.alexlebens.dev
