docs:
  global:
    fullnameOverride: docs
  controllers:
    main:
      type: deployment
      replicas: 3
      strategy: RollingUpdate
      containers:
        main:
          image:
            repository: harbor.alexlebens.dev/images/docs
            tag: 1.40.0@sha256:f436e58195ede135fdadd6245f35eb142a3627f6a4c4a5a64d0f1faaf5f38e2c
          resources:
            requests:
              cpu: 1m
              memory: 60Mi
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /
                  port: 8000
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /
                  port: 8000
  service:
    main:
      ports:
        http:
          port: 80
          targetPort: 8000
  route:
    main:
      kind: HTTPRoute
      parentRefs:
        - name: traefik-gateway
          namespace: traefik
      hostnames:
        - docs.alexlebens.dev
      rules:
        - backendRefs:
            - name: docs
              port: 80
          matches:
            - path:
                type: PathPrefix
                value: /
cloudflared:
  probe:
    enabled: true
    targetUrl: https://docs.alexlebens.dev
