apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-sandbox-privileged-runner-registration-client
  labels:
    helm.sh/chart: n8n-sandbox-0.6.5
    app.kubernetes.io/name: n8n-sandbox
    app.kubernetes.io/instance: n8n-sandbox
    app.kubernetes.io/version: "1.3.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: privileged-runner
spec:
  secretName: n8n-sandbox-runner-registration-tls
  duration: 2160h
  renewBefore: 360h
  commonName: n8n-sandbox-privileged-runner-registration-client
  privateKey:
    rotationPolicy: "Always"
  usages:
    - client auth
  issuerRef:
    name: "n8n-sandbox-ca-issuer"
    kind: "Issuer"
    group: "cert-manager.io"
