apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-sandbox-ca
  namespace: n8n-sandbox
  labels:
    app.kubernetes.io/name: n8n-sandbox-ca
    app.kubernetes.io/instance: n8n-sandbox
    app.kubernetes.io/part-of: n8n-sandbox
spec:
  isCA: true
  commonName: n8n-sandbox-ca
  secretName: n8n-sandbox-ca-key-pair
  issuerRef:
    name: n8n-sandbox-bootstrap-issuer
    kind: Issuer
    group: cert-manager.io
