{
 "title": "Bazarr",
 "tags": [
  "application",
  "subtitles"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Instance",
    "query": {
     "query": "label_values(bazarr_system_status,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Subtitles Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 16, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bazarr_subtitles_wanted_total{namespace=\"$namespace\"} OR on() vector(0)) by (namespace)",
     "legendFormat": "Wanted"
    },
    {
     "expr": "sum(bazarr_subtitles_missing_total{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "Missing"
    },
    {
     "expr": "sum(bazarr_subtitles_history_total{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Subtitles",
   "type": "stat",
   "gridPos": { "h": 16, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bazarr_subtitles_downloaded_total{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "sum(bazarr_subtitles_monitored_total{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "Monitored"
    },
    {
     "expr": "count(count by (language) (bazarr_subtitles_language_total{namespace=\"$namespace\"}))",
     "legendFormat": "Languages"
    }
   ]
  },
  {
   "title": "Subtitles by Provider",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(bazarr_subtitles_provider_total{namespace=\"$namespace\"}) by (provider))",
     "legendFormat": "{{ provider }}"
    }
   ]
  },
  {
   "title": "Subtitles by Language",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(bazarr_subtitles_language_total{namespace=\"$namespace\"}) by (language))",
     "legendFormat": "{{ language }}"
    }
   ]
  },
  {
   "title": "Storage & System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Subtitles Storage Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bazarr_subtitles_filesize_total{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SignalR Upstream Status",
   "type": "stat",
   "description": "SignalR connection status to upstream Servarr instances (Radarr & Sonarr)",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazarr_signalr_connected{namespace=\"$namespace\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Provider Health & Issues",
   "type": "stat",
   "description": "Subtitle provider throttling and system health issues",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bazarr_throttled_providers{namespace=\"$namespace\"} OR on() vector(0)) by (namespace)",
     "legendFormat": "Throttled Providers"
    },
    {
     "expr": "sum(bazarr_system_health_issues{namespace=\"$namespace\"} OR on() vector(0)) by (namespace)",
     "legendFormat": "Health Issues"
    }
   ]
  }
 ]
}