apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ntfy-config
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: thanos-objstore
    template:
      engineVersion: v2
      data:
        S3_URI: "s3://{{ `{{ .AWS_ACCESS_KEY_ID }}` }}:{{ `{{ .AWS_SECRET_ACCESS_KEY }}` }}@{{ `{{ .BUCKET_NAME }}` }}/attachments?region={{ `{{ .AWS_REGION }}` }}&endpoint={{ `{{ .ENDPOINT }}` }}"
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /ps02sn/garage/keys/ntfy-assets
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /ps02sn/garage/keys/ntfy-assets
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_REGION
      remoteRef:
        key: /ps02sn/garage/keys/ntfy-assets
        property: AWS_REGION
    - secretKey: BUCKET_NAME
      remoteRef:
        key: /ps02sn/garage/keys/ntfy-assets
        property: BUCKET_NAME
    - secretKey: ENDPOINT
      remoteRef:
        key: /ps02sn/garage/config
        property: ENDPOINT
