apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freshrss-install-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: freshrss-install-config
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: ADMIN_EMAIL
      remoteRef:
        key: /cl01tl/freshrss/config
        property: admin-email
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: /cl01tl/freshrss/config
        property: admin-password
    - secretKey: ADMIN_API_PASSWORD
      remoteRef:
        key: /cl01tl/freshrss/config
        property: admin-api-password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freshrss-oidc-authentik
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: freshrss-oidc-authentik
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: /cl01tl/authentik/oidc/freshrss
        property: client
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: /cl01tl/authentik/oidc/freshrss
        property: secret
    - secretKey: OIDC_CLIENT_CRYPTO_KEY
      remoteRef:
        key: /cl01tl/freshrss/key
        property: oidc-client-crypto-key
