apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-operator-token
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: garage-operator-token
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: rpc-secret
      remoteRef:
        key: /cl01tl/garage-operator/config
        property: rpc-secret
    - secretKey: admin-token
      remoteRef:
        key: /cl01tl/garage-operator/config
        property: admin-token
    - secretKey: metrics-token
      remoteRef:
        key: /cl01tl/garage-operator/config
        property: metrics-token

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-ui-cluster-a-jwt-key
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: garage-ui-cluster-a-jwt-key
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: jwt-key.pem
      remoteRef:
        key: /cl01tl/garage-operator/key
        property: ui-cluster-a-jwt-key.pem

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-cluster-a-ui-oidc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: garage-cluster-a-ui-oidc
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: clientSecret
      remoteRef:
        key: /cl01tl/pocket-id/oidc/garage-operator/cluster-a
        property: clientSecret

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-cluster-a-admin-key
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: garage-cluster-a-admin-key
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: /garage/home-infra/admin
        property: ACCESS_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: /garage/home-infra/admin
        property: ACCESS_SECRET_KEY

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-cluster-a-read-key
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: garage-cluster-a-read-key
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: /garage/home-infra/read
        property: ACCESS_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: /garage/home-infra/read
        property: ACCESS_SECRET_KEY
