{
 "title": "Authentik",
 "tags": [
  "platform",
  "single sign on"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "authentik_outpost_connection" } },
   {
    "name": "outpost_proxy",
    "query": {
     "query": "authentik_outpost_info{outpost_type=\"proxy\"}"
    }
   },
   {
    "name": "outpost_ldap",
    "query": {
     "query": "authentik_outpost_info{outpost_type=\"ldap\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "authentik Core",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "FlowPlanner time by flow",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (flow_slug) (rate(authentik_flows_plan_time_sum{namespace=~\"$namespace\"}[5m]) / rate(authentik_flows_plan_time_count{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{ flow_slug }}"
    }
   ]
  },
  {
   "title": "Task status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(authentik_system_tasks{namespace=~\"$namespace\",status=\"TaskResultStatus.ERROR\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(authentik_system_tasks{namespace=~\"$namespace\",status=\"TaskResultStatus.SUCCESSFUL\"})",
     "legendFormat": "Successful"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": {
    "content": "\n\n<img src=\"https://goauthentik.io/img/icon_top_brand.svg\">"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connected Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(authentik_admin_workers{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Cached policies",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(authentik_policies_cached{namespace=~\"$namespace\"})",
     "legendFormat": "Cached policies"
    },
    {
     "expr": "sum(authentik_models{namespace=~\"$namespace\",app=\"authentik_policies\", model_name=\"policy\"}) - authentik_policies_cached",
     "legendFormat": "Total policies"
    }
   ]
  },
  {
   "title": "Connected Outposts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(authentik_outposts_connected{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "System task duration",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (task_name) (authentik_system_tasks{namespace=~\"$namespace\"})",
     "legendFormat": "{{ task_name }}"
    }
   ]
  },
  {
   "title": "PolicyEngine Execution time by binding type (Top 5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, avg by(binding_target_type) (rate(authentik_policies_execution_time_sum{namespace=~\"$namespace\"}[5m]) / rate(authentik_policies_execution_time_count{namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ binding_target_type }}"
    }
   ]
  },
  {
   "title": "PolicyEngine Execution time by binding target (Top 5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, avg by(object_type) (rate(authentik_policies_execution_time_sum{namespace=~\"$namespace\"}[5m]) / rate(authentik_policies_execution_time_count{namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ object_type }}"
    }
   ]
  },
  {
   "title": "authentik Proxy Outpost $outpost_proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "repeat": "outpost_proxy",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Outpost requests (per 5 minutes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum by (host) (rate(authentik_outpost_proxy_requests_sum{namespace=~\"$namespace\", outpost_name=\"$outpost_proxy\"}[5m]))",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "Outpost requests (per 5 minutes) (unauthenticated, but allow-listed)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "sum by (host) (rate(authentik_outpost_proxy_requests_sum{outpost_name=\"$outpost_proxy\", namespace=~\"$namespace\",user=\"\"}[5m]))",
       "legendFormat": "{{ host }}"
      }
     ]
    }
   ]
  },
  {
   "title": "authentik LDAP Outpost $outpost_ldap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "outpost_ldap",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "LDAP Requests (per 5 minutes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "avg by (dn) (rate(authentik_outpost_ldap_requests_bucket{namespace=~\"$namespace\", outpost_name=\"$outpost_ldap\"}[5m]))",
       "legendFormat": "{{ dn }}"
      }
     ]
    },
    {
     "title": "LDAP Rejected Requests (per 5 minutes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "avg by (reason) (rate(authentik_outpost_ldap_requests_rejected{namespace=~\"$namespace\", outpost_name=\"$outpost_ldap\"}[5m]))",
       "legendFormat": "{{ reason }}"
      }
     ]
    },
    {
     "title": "FlowExecutor Timings",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "avg by (flow) (rate(authentik_outpost_flow_timing_get_bucket{namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "{{ flow }} GET"
      },
      {
       "expr": "avg by (flow) (rate(authentik_outpost_flow_timing_post_bucket{namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "{{ flow }} POST"
      }
     ]
    },
    {
     "title": "LDAP Requests by type",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "group by (type) (authentik_outpost_ldap_requests_sum)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "LDAP Rejected Requests by reason",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "group by (reason) (authentik_outpost_ldap_requests_rejected)",
       "legendFormat": "{{ reason }}"
      }
     ]
    }
   ]
  }
 ]
}