apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pixelprobe-secret
  namespace: pixelprobe
  labels:
    app.kubernetes.io/name: pixelprobe-secret
    app.kubernetes.io/instance: pixelprobe
    app.kubernetes.io/part-of: pixelprobe
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: secret-key
      remoteRef:
        key: /cl01tl/pixelprobe/key
        property: secret-key
