apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pixelprobe-nfs-storage
  namespace: pixelprobe
  labels:
    app.kubernetes.io/name: pixelprobe-nfs-storage
    app.kubernetes.io/instance: pixelprobe
    app.kubernetes.io/part-of: pixelprobe
spec:
  volumeName: pixelprobe-nfs-storage
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
