apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pixelprobe
  labels:
    app.kubernetes.io/instance: pixelprobe
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pixelprobe
    helm.sh/chart: pixelprobe-5.1.0
  namespace: pixelprobe
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - pixelprobe
  selector:
    matchLabels:
      app.kubernetes.io/instance: pixelprobe
      app.kubernetes.io/name: pixelprobe
  endpoints:
    - port: oauth-metrics
