apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: paperless-ngx-postgres-pgvector-database-app
  namespace: paperless-ngx
  labels:
    app.kubernetes.io/name: paperless-ngx-postgres-pgvector-database-app
    helm.sh/chart: postgres-pgvector-cluster-8.4.3
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/part-of: paperless-ngx
    app.kubernetes.io/version: "v1.30.0"
    app.kubernetes.io/managed-by: Helm
spec:
  name: app
  cluster:
    name: paperless-ngx-postgres-pgvector-cluster
  ensure: present
  owner: app
  template: template1
  encoding: UTF8
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
      ensure: present
    - name: vchord
      ensure: present
