apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-config
  namespace: paperless-ngx
  labels:
    app.kubernetes.io/name: paperless-ngx-config
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/part-of: paperless-ngx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: admin-user
      remoteRef:
        key: /cl01tl/paperless-ngx/config
        property: admin-user
    - secretKey: admin-password
      remoteRef:
        key: /cl01tl/paperless-ngx/config
        property: admin-password
