apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: paperless-ngx-media-backup-source-external
  namespace: paperless-ngx
  labels:
    helm.sh/chart: volsync-target-media-2.0.0
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/part-of: paperless-ngx
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: paperless-ngx-media-backup
spec:
  sourcePVC: paperless-ngx-media
  trigger:
    schedule: 30 9 * * 3
  restic:
    pruneIntervalDays: 35
    repository: paperless-ngx-media-backup-secret-external
    retain:
      daily: 0
      hourly: 0
      monthly: 0
      weekly: 12
      yearly: 0
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-blockpool-snapshot
    cacheCapacity: 1Gi
