apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: paperless-ngx-consume-backup-source-external
  namespace: paperless-ngx
  labels:
    helm.sh/chart: volsync-target-consume-0.8.0
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/part-of: paperless-ngx
    app.kubernetes.io/version: "0.8.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: paperless-ngx-consume-backup
spec:
  sourcePVC: paperless-ngx-consume
  trigger:
    schedule: 4 10 * * *
  restic:
    pruneIntervalDays: 7
    repository: paperless-ngx-consume-backup-secret-external
    retain:
      daily: 7
      hourly: 0
      monthly: 3
      weekly: 4
      yearly: 1
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-blockpool-snapshot
    cacheCapacity: 1Gi
