apiVersion: v1
kind: Service
metadata:
  name: paperless-ngx-valkey
  labels:
    helm.sh/chart: valkey-0.9.3
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: paperless-ngx
    app.kubernetes.io/version: "9.0.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: paperless-ngx
    statefulset.kubernetes.io/pod-name: paperless-ngx-valkey-0
