apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: yamtrack-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: yamtrack-config
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: SECRET
      remoteRef:
        key: /cl01tl/yamtrack/config
        property: secret

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: yamtrack-oidc-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: yamtrack-oidc-secret
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    template:
      engineVersion: v2
      data:
        clientId: "{{ `{{ .clientId }}` }}"
        clientSecret: "{{ `{{ .clientSecret }}` }}"
        SOCIALACCOUNT_PROVIDERS: |
          {
            "openid_connect": {
              "OAUTH_PKCE_ENABLED": true,
              "APPS": [
                {
                  "provider_id": "pocket-id",
                  "name": "AlexAuth",
                  "client_id": "{{ `{{ .clientId }}` }}",
                  "secret": "{{ `{{ .clientSecret }}` }}",
                  "settings": {
                    "server_url": "https://auth.alexlebens.dev/.well-known/openid-configuration"
                  }
                }
              ],
              "SCOPE": ["openid", "profile", "email"]
            }
          }
  data:
    - secretKey: clientId
      remoteRef:
        key: /cl01tl/pocket-id/oidc/yamtrack
        property: clientId
    - secretKey: clientSecret
      remoteRef:
        key: /cl01tl/pocket-id/oidc/yamtrack
        property: clientSecret
