apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-token
  namespace: garage
  labels:
    app.kubernetes.io/name: garage-token
    app.kubernetes.io/instance: garage
    app.kubernetes.io/part-of: garage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: GARAGE_RPC_SECRET
      remoteRef:
        key: /cl01tl/garage/config
        property: rpc-secret
    - secretKey: GARAGE_ADMIN_TOKEN
      remoteRef:
        key: /cl01tl/garage/config
        property: admin-token
    - secretKey: GARAGE_METRICS_TOKEN
      remoteRef:
        key: /cl01tl/garage/config
        property: metrics-token
