descheduler:
  kind: Deployment
  image:
    repository: registry.k8s.io/descheduler/descheduler
    tag: v0.36.0@sha256:7ca92c0a7b4f1c51d306409da6b832005fcadb224e384795646376726734c6e5
  resources:
    requests:
      cpu: 1m
      memory: 20Mi
  deschedulerPolicy:
    profiles:
      - name: default
        pluginConfig:
          - name: DefaultEvictor
            args:
              ignorePvcPods: true
              evictLocalStoragePods: false
              evictDaemonSetPods: false
          - name: RemoveDuplicates
          - name: RemovePodsViolatingNodeAffinity
            args:
              nodeAffinityType:
                - requiredDuringSchedulingIgnoredDuringExecution
          - name: RemovePodsViolatingNodeTaints
          - name: RemovePodsViolatingInterPodAntiAffinity
          - name: RemovePodsViolatingTopologySpreadConstraint
          - name: LowNodeUtilization
            args:
              thresholds:
                cpu: 60
                memory: 60
                pods: 60
              targetThresholds:
                cpu: 90
                memory: 70
                pods: 80
        plugins:
          balance:
            enabled:
              - RemoveDuplicates
              - RemovePodsViolatingTopologySpreadConstraint
              - LowNodeUtilization
          deschedule:
            enabled:
              - RemovePodsViolatingNodeTaints
              - RemovePodsViolatingNodeAffinity
              - RemovePodsViolatingInterPodAntiAffinity
  service:
    enabled: true
  serviceMonitor:
    enabled: true
