apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rybbit-clickhouse-config
  namespace: rybbit
  labels:
    app.kubernetes.io/name: rybbit-clickhouse-config
    app.kubernetes.io/instance: rybbit
    app.kubernetes.io/part-of: rybbit
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: clickhouse-user
      remoteRef:
        key: /cl01tl/rybbit/clickhouse
        property: user
    - secretKey: clickhouse-password
      remoteRef:
        key: /cl01tl/rybbit/clickhouse
        property: password
