apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-ps09rp-rybbit-http-2xx
  namespace: rybbit
  labels:
    app.kubernetes.io/name: blackbox-ps09rp-rybbit-http-2xx
    app.kubernetes.io/instance: rybbit
    app.kubernetes.io/part-of: rybbit
spec:
  prober:
    url: ps09rp.alexlebens.net:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - https://rybbit.alexlebens.dev
