apiVersion: v1
kind: ServiceAccount
metadata:
  name: rybbit
  labels:
    app.kubernetes.io/instance: rybbit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rybbit
    helm.sh/chart: rybbit-5.0.1
  namespace: rybbit
