apiVersion: apps/v1
kind: Deployment
metadata:
  name: element-web
  labels:
    helm.sh/chart: element-web-1.4.41
    app.kubernetes.io/name: element-web
    app.kubernetes.io/instance: element-web
    app.kubernetes.io/version: "1.12.24"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: element-web
      app.kubernetes.io/instance: element-web
  template:
    metadata:
      annotations:
        checksum/config: af01a1541b778776521e768988d9242af912ad1085b42d229cde244b508c90cf
        checksum/config-nginx: 93f4ac221e3b7cf8a84d8967f0d6252c6ae1e442e47b2ee60b4029ee0d29f700
      labels:
        app.kubernetes.io/name: element-web
        app.kubernetes.io/instance: element-web
    spec:
      serviceAccountName: element-web
      securityContext: {}
      containers:
        - name: element-web
          securityContext: {}
          image: "ghcr.io/element-hq/element-web:v1.12.24@sha256:9f9b546280e67e492d56f6e775c449e74356bffb98daaf211abc755276713fad"
          imagePullPolicy: IfNotPresent
          env:
            - name: ELEMENT_WEB_PORT
              value: '8080'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 1m
              memory: 10Mi
          volumeMounts:
            - mountPath: /app/config.json
              name: config
              subPath: config.json
            - mountPath: /etc/nginx/conf.d/config.json
              name: config-nginx
              subPath: config.json
      volumes:
        - name: config
          configMap:
            name: element-web
        - name: config-nginx
          configMap:
            name: element-web-nginx
