apiVersion: v1
kind: ServiceAccount
metadata:
  name: element-web-cloudflared
  labels:
    app.kubernetes.io/instance: element-web
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/version: 2026.5.1
    helm.sh/chart: cloudflared-3.3.2
  namespace: element-web
