apiVersion: v2
name: foldergram
version: 1.0.0
description: Foldergram
keywords:
  - foldergram
  - pictures
home: https://wiki.alexlebens.dev/
sources:
  - https://github.com/foldergram/foldergram
  - https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
maintainers:
  - name: alexlebens
dependencies:
  - name: app-template
    alias: foldergram
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 4.6.2
  - name: volsync-target
    alias: volsync-target-data
    version: 0.8.0
    repository: oci://harbor.alexlebens.net/helm-charts
icon: https://raw.githubusercontent.com/foldergram/foldergram/refs/heads/main/client/public/icon-512.png
# renovate: datasource=github-releases depName=foldergram/foldergram
appVersion: v1.0.6
