apiVersion: v2
name: foldergram
version: 1.0.0
description: Foldergram
keywords:
  - foldergram
  - pictures
home: https://docs.alexlebens.dev/applications/foldergram/
sources:
  - https://github.com/foldergram/foldergram
  - https://github.com/foldergram/foldergram/pkgs/container/foldergram
  - https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/cloudflared
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/volsync-target
maintainers:
  - name: alexlebens
dependencies:
  - name: app-template
    alias: foldergram
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 4.6.2
  - name: cloudflared
    repository: oci://harbor.alexlebens.net/helm-charts
    version: 2.6.0
  - name: volsync-target
    alias: volsync-target-db
    version: 0.8.0
    repository: oci://harbor.alexlebens.net/helm-charts
icon: https://raw.githubusercontent.com/foldergram/foldergram/refs/heads/main/client/public/icon-512.png
# renovate: datasource=github-releases depName=foldergram/foldergram
appVersion: v1.1.0
