apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy-attachments-rclone-source-config
  namespace: ntfy
  labels:
    helm.sh/chart: rclone-ntfy-attachments-remote-0.2.0
    app.kubernetes.io/instance: ntfy
    app.kubernetes.io/part-of: ntfy
    app.kubernetes.io/version: "0.2.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ntfy-attachments-rclone-source-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: /garage/home-infra/ntfy-attachments
        property: ACCESS_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: /garage/home-infra/ntfy-attachments
        property: ACCESS_SECRET_KEY
    - secretKey: ACCESS_REGION
      remoteRef:
        key: /garage/home-infra/ntfy-attachments
        property: ACCESS_REGION
    - secretKey: SRC_ENDPOINT
      remoteRef:
        key: /garage/config
        property: ENDPOINT_LOCAL
