apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy-config
  namespace: ntfy
  labels:
    app.kubernetes.io/name: ntfy-config
    app.kubernetes.io/instance: ntfy
    app.kubernetes.io/part-of: ntfy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: attachment-cache-dir
      remoteRef:
        key: /garage/home-infra/ntfy-attachments
        property: S3_URI
