apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ntfy
  labels:
    app.kubernetes.io/instance: ntfy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ntfy
    helm.sh/chart: ntfy-5.2.1
  annotations:
    gethomepage.dev/description: Ntfy
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Services
    gethomepage.dev/icon: sh-ntfy.webp
    gethomepage.dev/name: Notifications
    gethomepage.dev/siteMonitor: http://ntfy.ntfy:80/v1/health
    gethomepage.dev/statusStyle: dot
    gethomepage.dev/weight: "100"
  namespace: ntfy
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: "traefik"
  hostnames:
    - "ntfy.alexlebens.dev"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: ntfy
          namespace: ntfy
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
