apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-browser-metrics-auth
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: searxng-browser-metrics-auth
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: metrics-password
      remoteRef:
        key: cl01tl/searxng/browser
        property: metrics-password
    - secretKey: metrics-username
      remoteRef:
        key: cl01tl/searxng/browser
        property: metrics-username

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-api-config-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: searxng-api-config-secret
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: settings.yml
      remoteRef:
        key: /cl01tl/searxng/api/config
        property: settings.yml
    - secretKey: limiter.toml
      remoteRef:
        key: /cl01tl/searxng/api/config
        property: limiter.toml
