apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: searxng-api-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: searxng-api-config
    {{- include "custom.labels" . | nindent 4 }}
spec:
  provider: openbao
  parameters:
    baoAddress: "http://openbao-internal.openbao:8200"
    roleName: searxng
    objects: |
      - objectName: limiter.toml
        fileName: limiter.toml
        secretPath: secret/data/cl01tl/searxng/api
        secretKey: limiter.toml
      - objectName: settings.yml
        fileName: settings.yml
        secretPath: secret/data/cl01tl/searxng/api
        secretKey: settings.yml
