apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-main
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: grafana-main
    app: grafana-main
    grafana.internal/instance: grafana
    {{- include "custom.labels" . | nindent 4 }}
spec:
  config:
    analytics:
      enabled: "false"
      check_for_updates: "false"
      reporting_enabled: "false"
    server:
      domain: {{ include "custom.domain" . | trimPrefix "." }}
      root_url: https://grafana{{ include "custom.domain" . }}
    log:
      mode: "console"
    users:
      auto_assign_org: "true"
      auto_assign_org_id: "1"
    auth:
      disable_login_form: "true"
      auto_login: "true"
    auth.generic_oauth:
      enabled: "true"
      name: AlexAuth
      allow_sign_up: "true"
      client_id: ${AUTH_CLIENT_ID}
      client_secret: ${AUTH_CLIENT_SECRET}
      scopes: openid profile email groups
      auth_url: https://auth.alexlebens.dev/authorize
      token_url: https://auth.alexlebens.dev/api/oidc/token
      api_url: https://auth.alexlebens.dev/api/oidc/userinfo
      role_attribute_path: contains(groups[*], 'platform-admin') && 'Admin' || contains(groups[*], 'admin') && 'Editor' || contains(groups[*], 'user') && 'Viewer'
    database:
      type: postgres
      host: "${DB_HOST}:${DB_PORT}"
      name: ${DB_DATABASE}
      user: ${DB_USER}
      password: ${DB_PASSWORD}
    remote_cache:
      type: redis
      connstr: addr=grafana-operator-valkey-remote-cache.grafana-operator:6379,pool_size=100,db=0,ssl=false
    unified_alerting:
      enabled: "true"
      ha_redis_address: grafana-operator-valkey-unified-alerting.grafana-operator:6379
  deployment:
    spec:
      replicas: 2
      template:
        spec:
          containers:
            - name: grafana
              # renovate: datasource=docker depName=grafana/grafana
              image: grafana/grafana:13.2.1@sha256:f772d434e8fab0049deb2b1b30abd43342bcfca1537614aa8d36080232cf4283
              resources:
                requests:
                  cpu: 50m
                  memory: 300Mi
              env:
                - name: AUTH_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "custom.defaultOidcSecret" . }}
                      key: clientId
                - name: AUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "custom.defaultOidcSecret" . }}
                      key: clientSecret
                - name: ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      name: grafana-config
                      key: admin-user
                - name: ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: grafana-config
                      key: admin-password
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: grafana-operator-postgresql-18-cluster-app
                      key: host
                - name: DB_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: grafana-operator-postgresql-18-cluster-app
                      key: dbname
                - name: DB_PORT
                  valueFrom:
                    secretKeyRef:
                      name: grafana-operator-postgresql-18-cluster-app
                      key: port
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: grafana-operator-postgresql-18-cluster-app
                      key: user
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: grafana-operator-postgresql-18-cluster-app
                      key: password
  httpRoute:
    spec:
      parentRefs:
        - name: traefik-gateway
          namespace: traefik
      hostnames:
        - grafana{{ include "custom.domain" . }}
