{
 "title": "Version Checker",
 "tags": [
  "service",
  "scan"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(version_checker_is_latest_version,exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Need Attention",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(version_checker_is_latest_version{exported_namespace=~\"$namespace\"}==0) by (image))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptodate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(version_checker_is_latest_version{exported_namespace=~\"$namespace\"}==1) by (image))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage Uptodate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(count(version_checker_is_latest_version{exported_namespace=~\"$namespace\"}==1) / count(version_checker_is_latest_version{exported_namespace=~\"$namespace\"}) * 100,1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Image Version Checks",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort(sum by(image,current_version,latest_version) (version_checker_is_latest_version{exported_namespace=~\"$namespace\"}))",
     "legendFormat": "Up to date"
    }
   ]
  }
 ]
}