apiVersion: v1
kind: Service
metadata:
  name: version-checker
  labels:
    app: version-checker
    app.kubernetes.io/name: version-checker
    helm.sh/chart: version-checker-v0.10.0
    app.kubernetes.io/instance: version-checker
    app.kubernetes.io/version: "v0.10.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/name: version-checker
    app.kubernetes.io/instance: version-checker
