apiVersion: apps/v1
kind: Deployment
metadata:
  name: eraser-metrics
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: eraser
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: eraser-metrics
    helm.sh/chart: eraser-metrics-4.6.2
  namespace: eraser
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/name: eraser-metrics
      app.kubernetes.io/instance: eraser
  template:
    metadata:
      annotations:
        checksum/configMaps: 99c74a4734ce3f4e4e91c516068ad606c1095d48c5049b2f51f1231db31e0122
      labels:
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: eraser
        app.kubernetes.io/name: eraser-metrics
    spec:
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - command:
            - /otelcol
            - --config=/conf/otel-collector-config.yaml
          image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.150.1@sha256:618f7867e49fdb173d9b46d535b01f82254b0b14beac6ab1f6f2eb8cf62c5d42
          name: main
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - mountPath: /conf/otel-collector-config.yaml
              mountPropagation: None
              name: config
              readOnly: true
              subPath: otel-collector-config.yaml
      volumes:
        - configMap:
            name: eraser-config
          name: config
