---
name: alloy
services:
  alloy:
    image: grafana/alloy:v1.19.2@sha256:b8ec653c44235fbe910879145dac3597d66b0aaecf60bcbbe82580767771a839
    container_name: alloy
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - alloy-data:/var/lib/alloy/data
    environment:
      - TZ=America/Chicago
    ports:
      - '0.0.0.0:12345:12345'
      - '0.0.0.0:1514:1514/udp'
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    restart: always
    user: root
    init: true
    security_opt:
      - apparmor:unconfined

volumes:
  alloy-data:
