apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: music-grabber
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: music-grabber
    {{- include "custom.labels" . | nindent 4 }}
spec:
  name: "Music Grabber"
  launchUrl: https://music-grabber.alexlebens.net
  description: "A self-hosted music acquisition service. Search YouTube, SoundCloud, Soulseek, MP3Phoenix and Monochrome (Tidal lossless)."
  callbackUrls:
    - https://music-grabber.alexlebens.net/oauth2/callback
  pkceEnabled: true
  skipConsent: true
  allowedUserGroups:
    - name: user
      namespace: pocket-id-operator
  clientID: 0BF3D1EA-4A90-48F6-ABB0-17FF2236ACD8
  clientSecretRef:
    name: music-grabber-oauth-proxy
    key: OAUTH2_PROXY_CLIENT_SECRET
  logo:
    logoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons@main/webp/music-grabber.webp
