apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: audiobookshelf-oidc-secret
  namespace: audiobookshelf
  labels:
    app.kubernetes.io/name: audiobookshelf-oidc-secret
    app.kubernetes.io/instance: audiobookshelf
    app.kubernetes.io/part-of: audiobookshelf
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: clientSecret
      remoteRef:
        key: /cl01tl/pocket-id/oidc/audiobookshelf
        property: clientSecret
