apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: audiobookshelf-oidc-secret
  namespace: audiobookshelf
  labels:
    app.kubernetes.io/name: audiobookshelf-oidc-secret
    helm.sh/chart: pocket-id-client-0.4.1
    app.kubernetes.io/instance: audiobookshelf
    app.kubernetes.io/part-of: audiobookshelf
    app.kubernetes.io/managed-by: Helm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: clientId
      remoteRef:
        key: /cl01tl/pocket-id/oidc/audiobookshelf
        property: clientId
    - secretKey: clientSecret
      remoteRef:
        key: /cl01tl/pocket-id/oidc/audiobookshelf
        property: clientSecret
