apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-audiobooks-nfs-storage
  namespace: audiobookshelf
  labels:
    app.kubernetes.io/name: audiobookshelf/templates/persistent-volume-claim.yaml
    app.kubernetes.io/instance: audiobookshelf
    app.kubernetes.io/part-of: audiobookshelf
spec:
  volumeName: audiobookshelf/templates/persistent-volume-claim.yaml
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
