apiVersion: v2
name: headlamp
version: 1.0.0
description: Headlamp
keywords:
  - headlamp
  - dashboard
home: https://docs.alexlebens.dev/Applications/headlamp/
sources:
  - https://github.com/headlamp-k8s/headlamp
  - https://github.com/headlamp-k8s/headlamp/tree/main/charts/headlamp
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/common-helpers
maintainers:
  - name: alexlebens
dependencies:
  - name: headlamp
    repository: https://kubernetes-sigs.github.io/headlamp/
    version: 0.45.0
  - name: common-helpers
    repository: oci://harbor.alexlebens.net/helm-charts
    version: 0.4.1
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/headlamp.png
# renovate: datasource=github-releases depName=headlamp-k8s/headlamp
appVersion: vv0.45.0
