headlamp:
  replicaCount: 2
  image:
    registry: ghcr.io
    repository: headlamp-k8s/headlamp
    tag: v0.41.0@sha256:89c6c65810bfde61796483c93c70d659104355593792bf55cab680d685da8eeb
  config:
    oidc:
      secret:
        create: false
      externalSecret:
        enabled: true
        name: headlamp-oidc-authentik
    watchPlugins: true
  httpRoute:
    enabled: true
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: traefik-gateway
        namespace: traefik
    hostnames:
      - headlamp.alexlebens.net
    rules:
      - matches:
        - path:
            type: PathPrefix
            value: /
        backendRefs:
          - kind: Service
            name: headlamp
            port: 80
  resources:
    requests:
      cpu: 1m
      memory: 80Mi
  pluginsManager:
    enabled: true
    securityContext:
      readOnlyRootFilesystem: false
      runAsNonRoot: false
      runAsUser: 0
    configContent: |
      plugins:
        - name: cert-manager
          source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_cert-manager
          version: 0.1.0
        - name: external-secrets-operator
          source: https://artifacthub.io/packages/headlamp/external-secrets-operator-headlamp-plugin/external-secrets-operator
          version: 0.1.0-beta7
      installOptions:
        parallel: false
        maxConcurrent: 1
