apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komodo-oidc-authentik
  namespace: komodo
  labels:
    app.kubernetes.io/name: komodo-oidc-authentik
    app.kubernetes.io/instance: komodo
    app.kubernetes.io/part-of: komodo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: client
      remoteRef:
        key: /cl01tl/authentik/oidc/komodo
        property: client
    - secretKey: secret
      remoteRef:
        key: /cl01tl/authentik/oidc/komodo
        property: secret
