apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komodo-mongodb-user-secret
  namespace: komodo
  labels:
    app.kubernetes.io/name: komodo-mongodb-user-secret
    app.kubernetes.io/instance: komodo
    app.kubernetes.io/part-of: komodo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: password
      remoteRef:
        key: /cl01tl/komodo/mongodb
        property: password
