apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komodo-secret
  namespace: komodo
  labels:
    app.kubernetes.io/name: komodo-secret
    app.kubernetes.io/instance: komodo
    app.kubernetes.io/part-of: komodo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: passkey
      remoteRef:
        key: /cl01tl/komodo/key
        property: passkey
    - secretKey: jwt
      remoteRef:
        key: /cl01tl/komodo/key
        property: jwt
    - secretKey: webhook
      remoteRef:
        key: /cl01tl/komodo/key
        property: webhook
