apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komodo-secret
  namespace: komodo
  labels:
    app.kubernetes.io/name: komodo-secret
    app.kubernetes.io/instance: komodo
    app.kubernetes.io/part-of: komodo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: passkey
      remoteRef:
        key: /cl01tl/komodo/config
        property: passkey
    - secretKey: jwt
      remoteRef:
        key: /cl01tl/komodo/config
        property: jwt
    - secretKey: webhook
      remoteRef:
        key: /cl01tl/komodo/config
        property: webhook
    - secretKey: oidc-client-id
      remoteRef:
        key: /authentik/oidc/komodo
        property: client
    - secretKey: oidc-client-secret
      remoteRef:
        key: /authentik/oidc/komodo
        property: secret
