apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: komodo-postgresql-17-fdb-scheduled-backup
  namespace: komodo
  labels:
    app.kubernetes.io/name: komodo-postgresql-17-fdb-scheduled-backup
    helm.sh/chart: postgresql-17-fdb-cluster-8.4.2
    app.kubernetes.io/instance: komodo
    app.kubernetes.io/part-of: komodo
    app.kubernetes.io/version: "v1.30.0"
    app.kubernetes.io/managed-by: Helm
spec:
  immediate: true
  suspend: false
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: komodo-postgresql-17-fdb-cluster
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: komodo-postgresql-17-fdb-backup
