apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: server-host-records
  namespace: external-dns
  labels:
    app.kubernetes.io/name: server-host-records
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/part-of: external-dns
spec:
  endpoints:
    - dnsName: nw01un.alexlebens.dev
      recordTTL: 180
      recordType: A
      targets:
        - 192.168.1.1
    - dnsName: nw01un.alexlebens.net
      recordTTL: 180
      recordType: CNAME
      targets:
        - nw01un.alexlebens.dev
    - dnsName: ps02sn.alexlebens.dev
      recordTTL: 180
      recordType: A
      targets:
        - 10.232.1.61
    - dnsName: ps02sn.alexlebens.net
      recordTTL: 180
      recordType: CNAME
      targets:
        - ps02sn.alexlebens.dev
    - dnsName: ps02sn-bond.alexlebens.dev
      recordTTL: 180
      recordType: A
      targets:
        - 10.232.1.64
    - dnsName: ps02sn-bond.alexlebens.net
      recordTTL: 180
      recordType: CNAME
      targets:
        - ps02sn-bond.alexlebens.dev
    - dnsName: ps08rp.alexlebens.dev
      recordTTL: 180
      recordType: A
      targets:
        - 10.232.1.51
    - dnsName: ps08rp.alexlebens.net
      recordTTL: 180
      recordType: CNAME
      targets:
        - ps08rp.alexlebens.dev
    - dnsName: ps09rp.alexlebens.dev
      recordTTL: 180
      recordType: A
      targets:
        - 10.232.1.52
    - dnsName: ps09rp.alexlebens.net
      recordTTL: 180
      recordType: CNAME
      targets:
        - ps09rp.alexlebens.dev
    - dnsName: dv01hr.alexlebens.dev
      recordTTL: 180
      recordType: A
      targets:
        - 10.232.1.72
    - dnsName: dv02kv.alexlebens.dev
      recordTTL: 180
      recordType: A
      targets:
        - 10.232.1.71
    - dnsName: pd05wd.alexlebens.dev
      recordTTL: 180
      recordType: A
      targets:
        - 10.230.0.115
    - dnsName: pl02mc.alexlebens.dev
      recordTTL: 180
      recordType: A
      targets:
        - 10.230.0.105
