apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: server-host-common-names
  namespace: external-dns
  labels:
    app.kubernetes.io/name: server-host-common-names
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/part-of: external-dns
spec:
  endpoints:
    - dnsName: unifi.alexlebens.dev
      recordTTL: 180
      recordType: CNAME
      targets:
        - nw01un.alexlebens.dev
    - dnsName: unifi.alexlebens.net
      recordTTL: 180
      recordType: CNAME
      targets:
        - nw01un.alexlebens.dev
    - dnsName: synology.alexlebens.dev
      recordTTL: 180
      recordType: CNAME
      targets:
        - ps02sn.alexlebens.dev
    - dnsName: synology.alexlebens.net
      recordTTL: 180
      recordType: CNAME
      targets:
        - ps02sn.alexlebens.dev
    - dnsName: synology-bond.alexlebens.dev
      recordTTL: 180
      recordType: CNAME
      targets:
        - ps02sn-bond.alexlebens.dev
    - dnsName: synologybond.alexlebens.net
      recordTTL: 180
      recordType: CNAME
      targets:
        - ps02sn-bond.alexlebens.dev
    - dnsName: hdhr.alexlebens.dev
      recordTTL: 180
      recordType: CNAME
      targets:
        - dv01hr.alexlebens.dev
    - dnsName: hdhr.alexlebens.net
      recordTTL: 180
      recordType: CNAME
      targets:
        - dv01hr.alexlebens.dev
    - dnsName: pikvm.alexlebens.dev
      recordTTL: 180
      recordType: CNAME
      targets:
        - dv02kv.alexlebens.dev
    - dnsName: pikvm.alexlebens.net
      recordTTL: 180
      recordType: CNAME
      targets:
        - dv02kv.alexlebens.dev
