apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-pdns-cluster
  namespace: external-dns
  labels:
    helm.sh/chart: external-dns-pdns-cluster-1.21.1
    app.kubernetes.io/name: external-dns-pdns-cluster
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/version: "0.21.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
