bazarr:
  controllers:
    main:
      type: deployment
      replicas: 1
      strategy: Recreate
      pod:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
      containers:
        main:
          image:
            repository: ghcr.io/linuxserver/bazarr
            tag: v1.5.6-ls342@sha256:9a631194c0dee21c85b5bff59e23610e1ae2f54594e922973949d271102e585e
          env:
            - name: TZ
              value: America/Chicago
            - name: PUID
              value: 1000
            - name: PGID
              value: 1000
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 1m
              memory: 250Mi
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
          targetPort: 6767
  route:
    main:
      kind: HTTPRoute
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway
          namespace: traefik
      hostnames:
        - bazarr.alexlebens.net
      rules:
        - backendRefs:
            - name: bazarr
              port: 80
          matches:
            - path:
                type: PathPrefix
                value: /
  persistence:
    config:
      forceRename: bazarr-config
      storageClass: ceph-block
      accessMode: ReadWriteOnce
      size: 5Gi
      advancedMounts:
        main:
          main:
            - path: /config
              readOnly: false
    media:
      existingClaim: bazarr-nfs-storage
      advancedMounts:
        main:
          main:
            - path: /mnt/store
              readOnly: false
volsync-target-config:
  pvcTarget: bazarr-config
  moverSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  local:
    enabled: true
    schedule: 10 8 * * *
  remote:
    enabled: true
    schedule: 10 9 * * *
  external:
    enabled: true
    schedule: 10 10 * * *
