apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: blog
  labels:
    app.kubernetes.io/instance: blog
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: blog
    helm.sh/chart: blog-5.1.0
  namespace: blog
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: "traefik"
  hostnames:
    - "blog.alexlebens.dev"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: blog
          namespace: blog
          port: 80
          weight: 1
