apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: cloudflared
  namespace: blog
  labels:
    app.kubernetes.io/name: cloudflared
    helm.sh/chart: cloudflared-4.2.0
    app.kubernetes.io/version: "4.2.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: blog
spec:
  prober:
    url: kube-prometheus-stack-prometheus-blackbox-exporter.kube-prometheus-stack.svc.cluster.local:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - https://www.alexlebens.dev
