apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog
  labels:
    app.kubernetes.io/instance: blog
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: blog
    helm.sh/chart: blog-5.0.1
  namespace: blog
