apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-cloudflared
  labels:
    app.kubernetes.io/instance: blog
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/version: 2026.8.2
    helm.sh/chart: cloudflared-4.2.2
  namespace: blog
