apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airvpn-wireguard-conf
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: airvpn-wireguard-conf
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: conf
      remoteRef:
        key: /airvpn/config
        property: conf
    - secretKey: private-key
      remoteRef:
        key: /airvpn/config
        property: private-key
    - secretKey: preshared-key
      remoteRef:
        key: /airvpn/config
        property: preshared-key
    - secretKey: addresses
      remoteRef:
        key: /airvpn/config
        property: addresses
    - secretKey: input-ports
      remoteRef:
        key: /airvpn/config
        property: input-ports

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: protonvpn-wireguard-conf
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: protonvpn-wireguard-conf
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: conf
      remoteRef:
        key: /protonvpn/config
        property: conf
    - secretKey: email
      remoteRef:
        key: /protonvpn/config
        property: email
    - secretKey: password
      remoteRef:
        key: /protonvpn/config
        property: password
    - secretKey: private-key
      remoteRef:
        key: /protonvpn/config
        property: private-key
