apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-backups-secret-backup-c
  namespace: psmdb-operator
  labels:
    app.kubernetes.io/name: mongodb-backups-secret-backup-c
    helm.sh/chart: s3-bucket-0.8.0
    app.kubernetes.io/name: mongodb-backups
    app.kubernetes.io/instance: psmdb-operator
    app.kubernetes.io/version: "v1.75.1"
    app.kubernetes.io/managed-by: Helm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /ps10rp/garage/keys/mongodb-backups
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /ps10rp/garage/keys/mongodb-backups
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_REGION
      remoteRef:
        key: /ps10rp/garage/keys/mongodb-backups
        property: AWS_REGION
    - secretKey: ENDPOINT
      remoteRef:
        key: /ps10rp/garage/config
        property: ENDPOINT
