apiVersion: v1
kind: ConfigMap
metadata:
  name: openbao-snapshot
  namespace: openbao
  labels:
    helm.sh/chart: openbao-0.27.1
    app.kubernetes.io/name: openbao
    app.kubernetes.io/instance: openbao
    app.kubernetes.io/managed-by: Helm
data:
  S3_HOST: garage-main.garage:3900
  S3_BUCKET: openbao-backups
  S3CMD_EXTRA_FLAG: -v
  S3_URI: s3://openbao-backups
  S3_EXPIRE_DAYS: "30"
  BAO_AUTH_PATH: kubernetes
  BAO_ROLE: bao-snapshot
  BAO_ADDR: http://openbao-active.openbao.svc:8200
