apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-snapshot-secret
  namespace: openbao
  labels:
    app.kubernetes.io/name: openbao-snapshot-secret
    app.kubernetes.io/instance: openbao
    app.kubernetes.io/part-of: openbao
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /ps02sn/garage/keys/openbao-backups
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_REGION
      remoteRef:
        key: /ps02sn/garage/keys/openbao-backups
        property: AWS_REGION
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /ps02sn/garage/keys/openbao-backups
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: BUCKET
      remoteRef:
        key: /ps02sn/garage/keys/openbao-backups
        property: BUCKET_NAME
