{
 "title": "OpenBao",
 "tags": [
  "platform",
  "secrets"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(up{job=\"openbao-active\"}, instance)"
   },
   {
    "name": "port",
    "query": "label_values(up{job=\"openbao-active\",instance=~\"$node:(.*)\"}, instance)"
   },
   {
    "name": "mountpoint",
    "label": "Mount Point:",
    "query": "label_values(${metrics_prefix}_secret_kv_count, mount_point)"
   },
   { "name": "metrics_prefix", "label": "Metrics Prefix", "query": "vault" }
  ]
 },
 "panels": [
  {
   "title": "Healthy Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"openbao-active\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Secrets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${metrics_prefix}_secret_kv_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Identity Entities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(${metrics_prefix}_identity_num_entities)"
    }
   ]
  },
  {
   "title": "Identity Entities Aliases by Method",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without(instance) (${metrics_prefix}_identity_entity_alias_count)",
     "legendFormat": "{{ auth_method }}"
    }
   ]
  },
  {
   "title": "Sealed Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(1 + ${metrics_prefix}_core_unsealed{})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Number of Leases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(${metrics_prefix}_expire_num_leases)"
    }
   ]
  },
  {
   "title": "Path Info: $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "mountpoint",
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Operations in \"$mountpoint\"",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg(increase(${metrics_prefix}_route_create_${mountpoint}__count[5m]))",
     "legendFormat": "Create"
    },
    {
     "expr": "avg(increase(${metrics_prefix}_route_delete_${mountpoint}__count[5m]))",
     "legendFormat": "Delete"
    },
    {
     "expr": "avg(increase(${metrics_prefix}_route_read_${mountpoint}__count[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "avg(increase(${metrics_prefix}_route_list_${mountpoint}__count[5m]))",
     "legendFormat": "List"
    }
   ]
  },
  {
   "title": "Time of Operations in \"$mountpoint\"",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg(rate(${metrics_prefix}_route_create_${mountpoint}__sum[1m]) / rate(${metrics_prefix}_route_create_${mountpoint}__count[1m]) * 1000)",
     "legendFormat": "Create"
    },
    {
     "expr": "avg(rate(${metrics_prefix}_route_delete_${mountpoint}__sum[1m]) / rate(${metrics_prefix}_route_delete_${mountpoint}__count[1m]) * 1000)",
     "legendFormat": "Delete"
    },
    {
     "expr": "avg(rate(${metrics_prefix}_route_read_${mountpoint}__sum[1m]) / rate(${metrics_prefix}_route_read_${mountpoint}__count[1m]) * 1000)",
     "legendFormat": "Read"
    },
    {
     "expr": "avg(rate(${metrics_prefix}_route_list_${mountpoint}__sum[1m]) / rate(${metrics_prefix}_route_list_${mountpoint}__count[1m]) * 1000)",
     "legendFormat": "List"
    }
   ]
  },
  {
   "title": "CPU/Mem Info: $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Heap Objects Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(${metrics_prefix}_runtime_heap_objects{} / ${metrics_prefix}_runtime_malloc_count{})"
    }
   ]
  },
  {
   "title": "Number of Goroutines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(${metrics_prefix}_runtime_num_goroutines{})"
    }
   ]
  },
  {
   "title": "Allocated MB",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(${metrics_prefix}_runtime_alloc_bytes{})",
     "legendFormat": "$node"
    }
   ]
  },
  {
   "title": "Token",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Available Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(${metrics_prefix}_token_count)"
    }
   ]
  },
  {
   "title": "Tokens by Policy",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without(instance) (${metrics_prefix}_token_count_by_policy)",
     "legendFormat": "{{ policy }}"
    }
   ]
  },
  {
   "title": "Pending Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(${metrics_prefix}_token_create_count - ${metrics_prefix}_token_store_count)"
    }
   ]
  },
  {
   "title": "Tokens by TTL",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without(instance) (${metrics_prefix}_token_count_by_ttl)",
     "legendFormat": "{{ creation_ttl }}"
    }
   ]
  },
  {
   "title": "Tokens by Auth Method",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without(instance) (${metrics_prefix}_token_count_by_auth)",
     "legendFormat": "{{ auth_method }}"
    }
   ]
  },
  {
   "title": "Tokens Creation by Method & TTL",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "avg by(auth_method, creation_ttl) (${metrics_prefix}_token_creation)",
     "legendFormat": "{{ auth_method }} - {{ creation_ttl }}"
    }
   ]
  },
  {
   "title": "Token Creation/Storage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "avg without(instance) (${metrics_prefix}_token_create_count)",
     "legendFormat": "Create"
    },
    {
     "expr": "avg without(instance) (${metrics_prefix}_token_store_count)",
     "legendFormat": "Store"
    }
   ]
  },
  {
   "title": "Token Lookups",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "avg(irate(${metrics_prefix}_token_lookup_count[1m]))",
     "legendFormat": "Lookups"
    }
   ]
  },
  {
   "title": "Audit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Log Request Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(${metrics_prefix}_audit_log_request_failure[1m]))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Log Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 3, "y": 54 },
   "targets": [
    {
     "expr": "avg(irate(${metrics_prefix}_audit_log_request_count[1m]))",
     "legendFormat": "Request "
    },
    {
     "expr": "avg(irate(${metrics_prefix}_audit_log_response_count[1m]))",
     "legendFormat": "Response"
    },
    {
     "expr": "avg(irate(${metrics_prefix}_core_handle_request_count[1m]))",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Consul Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 54 },
   "targets": [
    {
     "expr": "avg(irate(${metrics_prefix}_consul_get_count[1m]))",
     "legendFormat": "GET"
    },
    {
     "expr": "avg(irate(${metrics_prefix}_consul_put_count[1m]))",
     "legendFormat": "PUT"
    },
    {
     "expr": "avg(irate(${metrics_prefix}_consul_delete_count[1m]))",
     "legendFormat": "DELETE"
    },
    {
     "expr": "irate(${metrics_prefix}_consul_list_count{instance=\"$node:$port\"}[1m])",
     "legendFormat": "LIST"
    }
   ]
  },
  {
   "title": "Log Response Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(${metrics_prefix}_audit_log_response_failure[1m]))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Policy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Policy Set",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "avg(irate(${metrics_prefix}_policy_set_policy_count[1m]))",
     "legendFormat": "SET"
    }
   ]
  },
  {
   "title": "Policy Get",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "avg(irate(${metrics_prefix}_policy_get_policy_count[1m]))",
     "legendFormat": "GET"
    }
   ]
  }
 ]
}