apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: openbao
  namespace: openbao
  labels:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/instance: openbao
    app.kubernetes.io/part-of: openbao
spec:
  name: "OpenBao"
  launchUrl: https://bao.alexlebens.dev
  description: "Secrets management, encryption as a service, and privileged access management."
  callbackUrls:
    - https://bao.alexlebens.dev/ui/vault/auth/oidc/oidc/callback
    - http://localhost:8250/oidc/callback
  pkceEnabled: true
  skipConsent: true
  allowedUserGroups:
    - name: platform-admin
      namespace: pocket-id-operator
  clientID: FB30DF49-299D-40B4-A021-564633DC45A8
  clientSecretRef:
    name: openbao-oidc-secret
    key: clientSecret
  logo:
    logoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/openbao.webp
    darkLogoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/openbao.webp
