apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: openbao-openbao-backups-remote-rclone
  labels:
    app.kubernetes.io/instance: openbao
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: openbao-backups-remote-rclone
    app.kubernetes.io/version: v1.74.0
    helm.sh/chart: rclone-openbao-backups-remote-0.9.0
  namespace: openbao
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - openbao
  selector:
    matchLabels:
      app.kubernetes.io/instance: openbao-backups-remote-rclone
      app.kubernetes.io/name: openbao-backups-remote-rclone
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
      scrapeTimeout: 10s
