apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shelfmark-grimmory-config
  namespace: shelfmark
  labels:
    app.kubernetes.io/name: shelfmark-grimmory-config
    app.kubernetes.io/instance: shelfmark
    app.kubernetes.io/part-of: shelfmark
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: grimmory-user
      remoteRef:
        key: /cl01tl/grimmory/users/shelfmark
        property: user
    - secretKey: grimmory-password
      remoteRef:
        key: /cl01tl/grimmory/users/shelfmark
        property: password
