apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: talos-etcd-backup-local-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: talos-etcd-backup-local-config
    {{- include "custom.labels" . | nindent 4 }}
spec:
  provider: openbao
  parameters:
    baoAddress: "http://openbao-internal.openbao:8200"
    roleName: slskd
    objects: |
      - objectName: .s3cfg
        fileName: .s3cfg
        secretPath: secret/data/garage/home-infra/talos-backups
        secretKey: s3cfg-local

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: talos-etcd-backup-remote-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: talos-etcd-backup-remote-config
    {{- include "custom.labels" . | nindent 4 }}
spec:
  provider: openbao
  parameters:
    baoAddress: "http://openbao-internal.openbao:8200"
    roleName: slskd
    objects: |
      - objectName: .s3cfg
        fileName: .s3cfg
        secretPath: secret/data/garage/home-infra/talos-backups
        secretKey: s3cfg-remote

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: talos-etcd-backup-external-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: talos-etcd-backup-external-config
    {{- include "custom.labels" . | nindent 4 }}
spec:
  provider: openbao
  parameters:
    baoAddress: "http://openbao-internal.openbao:8200"
    roleName: slskd
    objects: |
      - objectName: .s3cfg
        fileName: .s3cfg
        secretPath: secret/data/digital-ocean/home-infra/talos-backups
        secretKey: s3cfg

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: talos-etcd-defrag-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: talos-etcd-defrag-config
    {{- include "custom.labels" . | nindent 4 }}
spec:
  provider: openbao
  parameters:
    baoAddress: "http://openbao-internal.openbao:8200"
    roleName: slskd
    objects: |
      - objectName: config
        fileName: config
        secretPath: secret/data/cl01tl/talos/talosconfig
        secretKey: config
