outline:
  controllers:
    main:
      type: deployment
      strategy: Recreate
      pod:
        securityContext:
          fsGroup: 1001
      containers:
        main:
          image:
            repository: outlinewiki/outline
            tag: 1.9.2@sha256:32d76719c378931dd65d93945930ca380d8376a0337d98a991fcc12b266f33cf
          env:
            - name: NODE_ENV
              value: production
            - name: URL
              value: https://outline.alexlebens.dev
            - name: PORT
              value: 3000
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: outline-key
                  key: secret-key
            - name: UTILS_SECRET
              valueFrom:
                secretKeyRef:
                  name: outline-key
                  key: utils-key
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: outline-postgresql-18-cluster-app
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: outline-postgresql-18-cluster-app
                  key: password
            - name: POSTGRES_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: outline-postgresql-18-cluster-app
                  key: dbname
            - name: POSTGRES_DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: outline-postgresql-18-cluster-app
                  key: host
            - name: POSTGRES_DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: outline-postgresql-18-cluster-app
                  key: port
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@$(POSTGRES_DATABASE_HOST):$(POSTGRES_DATABASE_PORT)/$(POSTGRES_DATABASE_NAME)
            - name: DATABASE_URL_TEST
              value: postgres://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@$(POSTGRES_DATABASE_HOST):$(POSTGRES_DATABASE_PORT)/$(POSTGRES_DATABASE_NAME)-test
            - name: DATABASE_CONNECTION_POOL_MIN
              value: "2"
            - name: DATABASE_CONNECTION_POOL_MAX
              value: "20"
            - name: PGSSLMODE
              value: disable
            - name: REDIS_URL
              value: redis://outline-valkey.outline:6379
            - name: FILE_STORAGE
              value: local
            - name: FILE_STORAGE_UPLOAD_MAX_SIZE
              value: "26214400"
            - name: FORCE_HTTPS
              value: false
            - name: ENABLE_UPDATES
              value: false
            - name: WEB_CONCURRENCY
              value: 1
            - name: FILE_STORAGE_IMPORT_MAX_SIZE
              value: 5120000
            - name: LOG_LEVEL
              value: info
            - name: DEFAULT_LANGUAGE
              value: en_US
            - name: RATE_LIMITER_ENABLED
              value: false
            - name: DEVELOPMENT_UNSAFE_INLINE_CSP
              value: false
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: outline-oidc-authentik
                  key: client
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: outline-oidc-authentik
                  key: secret
            - name: OIDC_ISSUER_URL
              value: https://auth.alexlebens.dev/application/o/outline
            - name: OIDC_USERNAME_CLAIM
              value: email
            - name: OIDC_DISPLAY_NAME
              value: Authentik
            - name: OIDC_SCOPES
              value: openid profile email
          resources:
            requests:
              cpu: 10m
              memory: 500Mi
  service:
    main:
      ports:
        http:
          port: 3000
  persistence:
    data:
      forceRename: outline-data
      storageClass: ceph-block
      accessMode: ReadWriteOnce
      size: 5Gi
      advancedMounts:
        main:
          main:
            - path: /var/lib/outline/data
cloudflared:
  probe:
    enabled: true
    targetUrl: https://outline.alexlebens.dev
postgres-18-cluster:
  mode: recovery
  recovery:
    objectStore:
      index: 1
  backup:
    objectStore:
      index: 1
      endpointURL: http://garage-cluster-a.garage-operator.svc.cluster.local:3900
    scheduledBackup:
      suspend: false
      schedule: "0 10 15 * * *"
volsync-target-data:
  pvcTarget: outline-data
  moverSecurityContext:
    fsGroup: 1001
  local:
    enabled: true
    schedule: 20 8 * * *
  remote:
    enabled: true
    schedule: 20 10 * * 3
  external:
    enabled: true
    schedule: 20 9 * * 3
