apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mautrix-whatsapp-backup-source-d
  namespace: matrix-synapse
  labels:
    helm.sh/chart: volsync-target-whatsapp-3.0.0
    app.kubernetes.io/instance: matrix-synapse
    app.kubernetes.io/part-of: matrix-synapse
    app.kubernetes.io/version: "0.16.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mautrix-whatsapp-backup-source-d
spec:
  sourcePVC: mautrix-whatsapp
  trigger:
    schedule: 45 9 * * 5
  restic:
    pruneIntervalDays: 35
    repository: mautrix-whatsapp-backup-secret-d
    retain:
      daily: 0
      hourly: 0
      monthly: 0
      weekly: 12
      yearly: 0
    moverSecurityContext:
      runAsGroup: 1337
      runAsUser: 1337
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-blockpool-snapshot
    cacheCapacity: 1Gi
