apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: matrix-synapse-hookshot-cloudflared
  labels:
    app.kubernetes.io/instance: matrix-synapse
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hookshot-cloudflared
    app.kubernetes.io/version: 2026.6.1
    helm.sh/chart: cloudflared-hookshot-3.4.1
  namespace: matrix-synapse
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - matrix-synapse
  selector:
    matchLabels:
      app.kubernetes.io/instance: matrix-synapse
      app.kubernetes.io/name: hookshot-cloudflared
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
      scrapeTimeout: 10s
