apiVersion: v1
kind: Service
metadata:
  name: matrix-synapse-hookshot-cloudflared
  labels:
    app.kubernetes.io/instance: matrix-synapse
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hookshot-cloudflared
    app.kubernetes.io/service: matrix-synapse-hookshot-cloudflared
    app.kubernetes.io/version: 2026.3.0
    helm.sh/chart: cloudflared-hookshot-3.2.0
  namespace: matrix-synapse
spec:
  type: ClusterIP
  ports:
    - port: 20241
      targetPort: 20241
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: matrix-synapse
    app.kubernetes.io/name: hookshot-cloudflared
