apiVersion: v1
kind: ServiceAccount
metadata:
  name: matrix-hookshot
  labels:
    app.kubernetes.io/instance: matrix-synapse
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: matrix-hookshot
    helm.sh/chart: matrix-hookshot-5.0.0
  namespace: matrix-synapse
