apiVersion: v1
kind: ServiceAccount
metadata:
  name: matrix-synapse
  namespace: matrix-synapse
  labels:
    app.kubernetes.io/name: matrix-synapse
    app.kubernetes.io/instance: matrix-synapse
    app.kubernetes.io/part-of: matrix-synapse
