apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mautrix-whatsapp
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: matrix-synapse
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mautrix-whatsapp
    helm.sh/chart: mautrix-whatsapp-5.0.1
  namespace: matrix-synapse
spec:
  revisionHistoryLimit: 3
  replicas: 1
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/name: mautrix-whatsapp
      app.kubernetes.io/instance: matrix-synapse
  serviceName: mautrix-whatsapp
  template:
    metadata:
      labels:
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: matrix-synapse
        app.kubernetes.io/name: mautrix-whatsapp
    spec:
      enableServiceLinks: false
      serviceAccountName: mautrix-whatsapp
      automountServiceAccountToken: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - image: dock.mau.dev/mautrix/whatsapp:v0.2606.0@sha256:3ecf348ac3451199fe1e7b894469bd8cf9b2abe58699f3b9a8029172c4356877
          name: main
          resources:
            requests:
              cpu: 1m
              memory: 20Mi
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: mautrix-whatsapp-config
          name: config
        - name: data
          persistentVolumeClaim:
            claimName: mautrix-whatsapp
