apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backblaze
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: backblaze
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /backblaze/home-infra/s3-exporter
        property: ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /backblaze/home-infra/s3-exporter
        property: ACCESS_SECRET_KEY
    - secretKey: AWS_REGION
      remoteRef:
        key: /backblaze/home-infra/s3-exporter
        property: ACCESS_REGION
    - secretKey: ENDPOINT
      remoteRef:
        key: /backblaze/config
        property: ENDPOINT

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-cluster-a
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: garage-cluster-a
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /garage/home-infra/read
        property: ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /garage/home-infra/read
        property: ACCESS_SECRET_KEY
    - secretKey: ACCESS_REGION
      remoteRef:
        key: /garage/home-infra/read
        property: ACCESS_REGION
    - secretKey: ENDPOINT
      remoteRef:
        key: /garage/config
        property: ENDPOINT_CLUSTER_A

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-cluster-b
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: garage-cluster-b
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /garage/home-infra/read
        property: ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /garage/home-infra/read
        property: ACCESS_SECRET_KEY
    - secretKey: ACCESS_REGION
      remoteRef:
        key: /garage/home-infra/read
        property: ACCESS_REGION
    - secretKey: ENDPOINT
      remoteRef:
        key: /garage/config
        property: ENDPOINT_CLUSTER_B

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-remote
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: garage-remote
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /garage/home-infra/s3-exporter
        property: ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /garage/home-infra/s3-exporter
        property: ACCESS_SECRET_KEY
    - secretKey: ACCESS_REGION
      remoteRef:
        key: /garage/home-infra/s3-exporter
        property: ACCESS_REGION
    - secretKey: ENDPOINT
      remoteRef:
        key: /garage/config
        property: ENDPOINT_REMOTE
