apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synology-iscsi-config
  namespace: democratic-csi-synology-iscsi
  labels:
    app.kubernetes.io/name: synology-iscsi-config
    app.kubernetes.io/instance: democratic-csi-synology-iscsi
    app.kubernetes.io/part-of: democratic-csi-synology-iscsi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: driver-config-file.yaml
      remoteRef:
        key: /cl01tl/democratic-csi-synology-iscsi/config
        property: driver-config-file.yaml
