apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-immich-memories-notify
  labels:
    app.kubernetes.io/controller: immich-memories-notify
    app.kubernetes.io/instance: immich
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: immich
    helm.sh/chart: immich-5.0.1
  namespace: immich
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/controller: immich-memories-notify
      app.kubernetes.io/name: immich
      app.kubernetes.io/instance: immich
  template:
    metadata:
      annotations:
        checksum/configMaps: 363911225c1382ac483de7217ec026eec3b7d46346fd6f48af77576910cf8f7e
      labels:
        app.kubernetes.io/controller: immich-memories-notify
        app.kubernetes.io/instance: immich
        app.kubernetes.io/name: immich
    spec:
      enableServiceLinks: false
      serviceAccountName: immich
      automountServiceAccountToken: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - env:
            - name: TZ
              value: America/Chicago
            - name: IMMICH_URL
              value: http://immich-main.immich:80
            - name: IMMICH_EXTERNAL_URL
              value: https://immich.alexlebens.net
            - name: IMMICH_API_KEY_USER1
              valueFrom:
                secretKeyRef:
                  key: IMMICH_API_KEY_USER1
                  name: immich-memories
            - name: NTFY_URL
              value: http://ntfy.ntfy:80
            - name: NTFY_EXTERNAL_URL
              value: http://ntfy.alexlebens.dev
            - name: NTFY_PASSWORD_USER1
              valueFrom:
                secretKeyRef:
                  key: NTFY_PASSWORD_USER1
                  name: immich-memories
          image: ghcr.io/ismaildakrory/immich-memories-notify:3.1.0@sha256:454b6fcaa032c588261f5191863d9da189d91f98b92c03b0c456f48cf3f2f7b0
          name: main
          volumeMounts:
            - mountPath: /app/config.yaml
              name: memories-notify-config
              readOnly: true
              subPath: config.yaml
            - mountPath: /app/state
              name: memories-state
      volumes:
        - configMap:
            name: immich-memories-notify-config
          name: memories-notify-config
        - name: memories-state
          persistentVolumeClaim:
            claimName: immich-memories-state
