apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  labels:
    app.kubernetes.io/controller: machine-learning
    app.kubernetes.io/instance: immich
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: immich
    helm.sh/chart: immich-5.1.0
  namespace: immich
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/controller: machine-learning
      app.kubernetes.io/name: immich
      app.kubernetes.io/instance: immich
  template:
    metadata:
      annotations:
        checksum/configMaps: 363911225c1382ac483de7217ec026eec3b7d46346fd6f48af77576910cf8f7e
      labels:
        app.kubernetes.io/controller: machine-learning
        app.kubernetes.io/instance: immich
        app.kubernetes.io/name: immich
    spec:
      enableServiceLinks: false
      serviceAccountName: immich
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - env:
            - name: TZ
              value: America/Chicago
          image: ghcr.io/immich-app/immich-machine-learning:v3.1.0-openvino@sha256:4b6ef958e7749fc548377bb23ee219c09c74da8decee080d76dc6a388c39b013
          livenessProbe:
            httpGet:
              path: /ping
              port: 3003
          name: main
          readinessProbe:
            httpGet:
              path: /ping
              port: 3003
          resources:
            limits:
              gpu.intel.com/i915: 1
            requests:
              cpu: 10m
              gpu.intel.com/i915: 1
              memory: 500Mi
          startupProbe:
            httpGet:
              path: /ping
              port: 3003
          volumeMounts:
            - mountPath: /cache
              name: model-cache
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: immich-model-cache
