apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-oidc-secret
  namespace: immich
  labels:
    app.kubernetes.io/name: immich-oidc-secret
    app.kubernetes.io/instance: immich
    app.kubernetes.io/part-of: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: clientId
      remoteRef:
        key: /cl01tl/pocket-id/oidc/immich
        property: clientId
    - secretKey: clientSecret
      remoteRef:
        key: /cl01tl/pocket-id/oidc/immich
        property: clientSecret
