{
 "title": "Immich",
 "tags": [
  "application",
  "photos"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "Logs Source", "query": "loki" },
   { "name": "NAMESPACE", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "System Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NodeJS Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "target_info{namespace=\"$NAMESPACE\", endpoint=\"metrics-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Immich Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "target_info{namespace=\"$NAMESPACE\", endpoint=\"metrics-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Immich Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{namespace=\"$NAMESPACE\", endpoint=\"metrics-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Immich Health",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (service) (up{namespace=\"$NAMESPACE\", endpoint=\"metrics-api\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "HTTP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "(sum(rate(http_server_duration_count{namespace=\"$NAMESPACE\", endpoint=\"metrics-api\"}[5m])) by (http_method, http_status_code)) * $__interval_ms / 1000",
     "legendFormat": "{{http_method}} {{http_status_code}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(http_method, http_status_code) (rate(http_server_duration_sum{namespace=\"$NAMESPACE\", endpoint=\"metrics-api\"}[5m])) / avg by(http_method, http_status_code) (rate(http_server_duration_count{namespace=\"$NAMESPACE\", endpoint=\"metrics-api\"}[5m]))",
     "legendFormat": "{{http_method}} {{http_status_code}}"
    }
   ]
  },
  {
   "title": "Total Errors (4XX | 5XX)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(http_method, http_status_code) (increase(http_server_duration_sum{namespace=\"$NAMESPACE\", endpoint=\"metrics-api\", http_status_code=~\"4.*|5.*\"}[5m]))",
     "legendFormat": "{{http_method}} {{http_status_code}}"
    }
   ]
  },
  { "title": "Logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Immich Server Logs (Promtail)",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"$NAMESPACE\"}"
    }
   ]
  },
  { "title": "Jobs Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Active Background Tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "immich_queues_background_task_active{namespace=\"$NAMESPACE\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "immich_queues_library_active{namespace=\"$NAMESPACE\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "immich_queues_metadata_extraction_active{namespace=\"$NAMESPACE\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "immich_queues_migration_active{namespace=\"$NAMESPACE\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "immich_queues_sidecar_active{namespace=\"$NAMESPACE\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "immich_queues_storage_template_migration_active{namespace=\"$NAMESPACE\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "immich_queues_video_conversion_active{namespace=\"$NAMESPACE\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "immich_queues_thumbnail_generation_active{namespace=\"$NAMESPACE\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "immich_queues_facial_recognition_active{namespace=\"$NAMESPACE\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Waiting Background Tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum({__name__=~\"immich_queues_.*_waiting\", namespace=\"$NAMESPACE\"}) by (__name__)",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Failed Background Tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum({__name__=~\"immich_queues_.*_failed\", namespace=\"$NAMESPACE\"}) by (__name__)",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Storage Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Storage Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_used_bytes{namespace=\"$NAMESPACE\", persistentvolumeclaim=\"immich\"})",
     "legendFormat": "Used - {{persistentvolumeclaim}}"
    },
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{namespace=\"$NAMESPACE\", persistentvolumeclaim=\"immich\"})",
     "legendFormat": "Capacity - {{persistentvolumeclaim}}"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "CPU Usage (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$NAMESPACE\", pod=~\"immich.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$NAMESPACE\", pod=~\"immich.*\", container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}