apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: immich-postgresql-18-backup
  namespace: immich
  labels:
    app.kubernetes.io/name: immich-postgresql-18-backup
    helm.sh/chart: postgres-18-cluster-8.4.2
    app.kubernetes.io/instance: immich
    app.kubernetes.io/part-of: immich
    app.kubernetes.io/version: "v1.30.0"
    app.kubernetes.io/managed-by: Helm
spec:
  retentionPolicy: 7d
  instanceSidecarConfiguration:
    env:
      - name: AWS_REQUEST_CHECKSUM_CALCULATION
        value: when_required
      - name: AWS_RESPONSE_CHECKSUM_VALIDATION
        value: when_required
  configuration:
    destinationPath: s3://postgres-backups/cl01tl/immich/immich-postgresql-18-cluster
    endpointURL: http://garage-cluster-a.garage-operator.svc.cluster.local:3900
    wal:
      compression: snappy
      maxParallel: 4
    data:
      compression: snappy
      jobs: 4
    s3Credentials:
      accessKeyId:
        name: immich-postgresql-18-backup-secret
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: immich-postgresql-18-backup-secret
        key: ACCESS_SECRET_KEY
      region:
        name: immich-postgresql-18-backup-secret
        key: ACCESS_REGION
