apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: cloudflared
  namespace: immich
  labels:
    app.kubernetes.io/name: cloudflared
    helm.sh/chart: cloudflared-4.1.2
    app.kubernetes.io/version: "4.1.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: immich
spec:
  prober:
    url: kube-prometheus-stack-prometheus-blackbox-exporter.kube-prometheus-stack.svc.cluster.local:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - https://immich.alexlebens.dev
