apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: immich-immich-sa-token
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: immich
    helm.sh/chart: immich-4.6.2
  annotations:
    kubernetes.io/service-account.name: immich
  namespace: immich
