apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: directus-config
  namespace: directus
  labels:
    app.kubernetes.io/name: directus-config
    app.kubernetes.io/instance: directus
    app.kubernetes.io/part-of: directus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: admin-email
      remoteRef:
        key: /cl01tl/directus/config
        property: admin-email
    - secretKey: admin-password
      remoteRef:
        key: /cl01tl/directus/config
        property: admin-password
    - secretKey: secret
      remoteRef:
        key: /cl01tl/directus/config
        property: secret
    - secretKey: key
      remoteRef:
        key: /cl01tl/directus/config
        property: key
