apiVersion: v1
kind: ServiceAccount
metadata:
  name: directus
  labels:
    app.kubernetes.io/instance: directus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: directus
    helm.sh/chart: directus-5.0.0
  namespace: directus
