apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: directus-directus-assets-remote-rclone
  labels:
    app.kubernetes.io/instance: directus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: directus-assets-remote-rclone
    app.kubernetes.io/version: v1.74.1
    helm.sh/chart: rclone-directus-assets-remote-0.11.1
  namespace: directus
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - directus
  selector:
    matchLabels:
      app.kubernetes.io/instance: directus
      app.kubernetes.io/name: directus-assets-remote-rclone
  endpoints:
    - interval: 10s
      path: /metrics
      port: metrics-sync
      scrapeTimeout: 5s
    - interval: 10s
      path: /metrics
      port: metrics-prune
      scrapeTimeout: 5s
