apiVersion: v1
kind: Service
metadata:
  name: directus-directus-assets-remote-rclone
  labels:
    app.kubernetes.io/instance: directus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: directus-assets-remote-rclone
    app.kubernetes.io/service: directus-directus-assets-remote-rclone
    app.kubernetes.io/version: v1.74.0
    helm.sh/chart: rclone-directus-assets-remote-0.9.0
  namespace: directus
spec:
  type: ClusterIP
  ports:
    - port: 5572
      targetPort: 5572
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: directus
    app.kubernetes.io/name: directus-assets-remote-rclone
