apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: lidarr
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: lidarr
    {{- include "custom.labels" . | nindent 4 }}
spec:
  name: "Lidarr"
  launchUrl: https://lidarr.alexlebens.net
  description: "A music collection manager for Usenet and BitTorrent users."
  callbackUrls:
    - https://lidarr.alexlebens.net/oauth2/callback
  pkceEnabled: true
  skipConsent: true
  allowedUserGroups:
    - name: admin
      namespace: pocket-id-operator
  clientID: 209274EA-537A-4E54-8A91-25A82EB1877B
  clientSecretRef:
    name: lidarr-oauth-proxy
    key: OAUTH2_PROXY_CLIENT_SECRET
  logo:
    logoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/lidarr.webp
    darkLogoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/lidarr.webp
