apiVersion: apps/v1
kind: Deployment
metadata:
  name: postiz-spotlight
  labels:
    app.kubernetes.io/controller: spotlight
    app.kubernetes.io/instance: postiz
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postiz
    helm.sh/chart: postiz-5.0.1
  namespace: postiz
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/controller: spotlight
      app.kubernetes.io/name: postiz
      app.kubernetes.io/instance: postiz
  template:
    metadata:
      labels:
        app.kubernetes.io/controller: spotlight
        app.kubernetes.io/instance: postiz
        app.kubernetes.io/name: postiz
    spec:
      enableServiceLinks: false
      serviceAccountName: postiz
      automountServiceAccountToken: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - image: ghcr.io/getsentry/spotlight:4.11.6@sha256:8893c309d36909b411a3426b1831cde100189f157cc0f5822fd284c6ea770577
          name: main
          resources:
            requests:
              cpu: 10m
              memory: 1000Mi
