apiVersion: apps/v1
kind: Deployment
metadata:
  name: postiz-temporal-admintools
  annotations:
  labels:
    app.kubernetes.io/component: admintools
    app.kubernetes.io/name: temporal
    helm.sh/chart: temporal-1.4.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: postiz
    app.kubernetes.io/version: "1.31.1"
    app.kubernetes.io/part-of: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: temporal
      app.kubernetes.io/instance: postiz
      app.kubernetes.io/component: admintools
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/component: admintools
        app.kubernetes.io/name: temporal
        helm.sh/chart: temporal-1.4.0
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: postiz
        app.kubernetes.io/version: "1.31.1"
        app.kubernetes.io/part-of: temporal
    spec:
      serviceAccountName: default
      containers:
        - name: admin-tools
          image: "temporalio/admin-tools:1.31.1@sha256:0fa94393f6254dea05df1cdacb7a8ee95f6fb51a2ffbde0c6847a73037f788c7"
          imagePullPolicy: IfNotPresent
          env:
            - name: TEMPORAL_CLI_ADDRESS
              value: postiz-temporal-frontend:7233
            - name: TEMPORAL_ADDRESS
              value: postiz-temporal-frontend:7233
          livenessProbe:
            exec:
              command:
                - ls
                - /
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
