apiVersion: apps/v1
kind: Deployment
metadata:
  name: postiz-temporal-web
  annotations:
  labels:
    app.kubernetes.io/component: web
    app.kubernetes.io/name: temporal
    helm.sh/chart: temporal-1.1.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: postiz
    app.kubernetes.io/version: "1.30.3"
    app.kubernetes.io/part-of: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: temporal
      app.kubernetes.io/instance: postiz
      app.kubernetes.io/component: web
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/component: web
        app.kubernetes.io/name: temporal
        helm.sh/chart: temporal-1.1.1
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: postiz
        app.kubernetes.io/version: "1.30.3"
        app.kubernetes.io/part-of: temporal
    spec:
      serviceAccountName: default
      containers:
        - name: temporal-web
          image: "temporalio/ui:2.48.4@sha256:b01df917af27067914b716a347eff78d232dfd47cc2c8527c621ce85e5bc15e3"
          imagePullPolicy: IfNotPresent
          env:
            - name: TEMPORAL_ADDRESS
              value: "postiz-temporal-frontend.postiz.svc:7233"
          livenessProbe:
            initialDelaySeconds: 10
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
