apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postiz-elasticsearch-secret
  namespace: postiz
  labels:
    app.kubernetes.io/name: postiz-elasticsearch-secret
    app.kubernetes.io/instance: postiz
    app.kubernetes.io/part-of: postiz
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: username
      remoteRef:
        key: /cl01tl/postiz/elasticsearch
        property: username
    - secretKey: password
      remoteRef:
        key: /cl01tl/postiz/elasticsearch
        property: password
    - secretKey: roles
      remoteRef:
        key: /cl01tl/postiz/elasticsearch
        property: roles
