apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postiz-oidc-secret
  namespace: postiz
  labels:
    app.kubernetes.io/name: postiz-oidc-secret
    app.kubernetes.io/instance: postiz
    app.kubernetes.io/part-of: postiz
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: clientId
      remoteRef:
        key: /cl01tl/pocket-id/oidc/postiz
        property: clientId
    - secretKey: clientSecret
      remoteRef:
        key: /cl01tl/pocket-id/oidc/postiz
        property: clientSecret
