apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postiz-oidc-authentik
  namespace: postiz
  labels:
    app.kubernetes.io/name: postiz-oidc-authentik
    app.kubernetes.io/instance: postiz
    app.kubernetes.io/part-of: postiz
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: client
      remoteRef:
        key: /cl01tl/authentik/oidc/postiz
        property: client
    - secretKey: secret
      remoteRef:
        key: /cl01tl/authentik/oidc/postiz
        property: secret
