apiVersion: v1
kind: Pod
metadata:
  name: "postiz-temporal-test-cluster-health"
  labels:
    app.kubernetes.io/component: test
    app.kubernetes.io/name: temporal
    helm.sh/chart: temporal-1.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: postiz
    app.kubernetes.io/version: "1.30.3"
    app.kubernetes.io/part-of: temporal
  annotations:
    "helm.sh/hook": test
spec:
  serviceAccountName: default
  containers:
    - name: cluster-health
      image: "temporalio/admin-tools:1.30.4@sha256:9ac15d500f4020f7cc694ecc17085dfcfc2d4b1d0d2020dbe83b6f3d49e156e0"
      imagePullPolicy: IfNotPresent
      command: ["temporal", "operator", "cluster", "health"]
      env:
        - name: TEMPORAL_ADDRESS
          value: postiz-temporal-frontend:7233
  restartPolicy: Never
