apiVersion: v1
kind: Pod
metadata:
  name: "postiz-temporal-test-cluster-health"
  labels:
    app.kubernetes.io/component: test
    app.kubernetes.io/name: temporal
    helm.sh/chart: temporal-1.0.0-rc.3
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: postiz
    app.kubernetes.io/version: "1.30.2"
    app.kubernetes.io/part-of: temporal
  annotations:
    "helm.sh/hook": test
spec:
  serviceAccountName: default
  containers:
    - name: cluster-health
      image: "temporalio/admin-tools:1.30.2@sha256:024c6473df113e4b220b3caf6056d30964582ffcae6f6e46a1074aa6c67968d3"
      imagePullPolicy: IfNotPresent
      command: ["temporal", "operator", "cluster", "health"]
      env:
        - name: TEMPORAL_ADDRESS
          value: postiz-temporal-frontend:7233
  restartPolicy: Never
