apiVersion: v2
name: kaneo
version: 1.0.0
description: Kaneo
keywords:
  - kaneo
  - issues
home: https://docs.alexlebens.dev/applications/kaneo/
sources:
  - https://kaneo.app
  - https://github.com/usekaneo/kaneo
  - https://github.com/usekaneo/kaneo/pkgs/container/kaneo
  - https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/postgres-cluster
maintainers:
  - name: alexlebens
dependencies:
  - name: app-template
    alias: kaneo
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 5.0.1
  - name: postgres-cluster
    alias: postgres-18-cluster
    version: 7.15.2
    repository: oci://harbor.alexlebens.net/helm-charts
  - name: rclone-bucket
    alias: rclone-kaneo-assets-remote
    repository: oci://harbor.alexlebens.net/helm-charts
    version: 0.12.5
  - name: rclone-bucket
    alias: rclone-kaneo-assets-external
    repository: oci://harbor.alexlebens.net/helm-charts
    version: 0.12.5
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/kaneo.png
# renovate: datasource=github-releases depName=usekaneo/kaneo
appVersion: 2.7.7
