{
 "title": "Actual Budget",
 "tags": [
  "application",
  "budget"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "budget", "label": "Budget", "query": { "query": "label_values(budget)" } }
  ]
 },
 "panels": [
  {
   "title": "IRA",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currency:financial:$" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (last_over_time(actual_budget_account_balance{budget=\"$budget\",account=\"Vanguard - Traditional IRA Brokerage\"}[$__interval]) / 100) by (job)"
    }
   ]
  },
  {
   "title": "Checking",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currency:financial:$" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (last_over_time(actual_budget_account_balance{budget=\"$budget\",account=\"USAA - Checking\"}[$__interval]) / 100) by (job)"
    }
   ]
  },
  {
   "title": "Savings",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currency:financial:$" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (last_over_time(actual_budget_account_balance{budget=\"$budget\",account=\"Vanguard - Cash Plus\"}[$__interval]) / 100) by (job)"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (last_over_time(actual_budget_transaction_count{budget=\"$budget\"}[$__interval])) by (job)"
    }
   ]
  },
  {
   "title": "Uncategorized Transactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (last_over_time(actual_budget_uncategorized_transaction_count{budget=\"$budget\"}[$__interval])) by (job)"
    }
   ]
  },
  {
   "title": "Balance per account",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currency:financial:$" } },
   "targets": [
    {
     "expr": "avg by(account) (last_over_time(actual_budget_account_balance{budget=\"$budget\", account!=\"Vanguard - Traditional IRA Brokerage\"}[$__rate_interval])) / 100",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Transactions per category",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(category) (last_over_time(actual_budget_category_tranasction_count{budget=\"$budget\",}[$__rate_interval])) / 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}