apiVersion: v1
kind: ServiceAccount
metadata:
  name: actual
  labels:
    app.kubernetes.io/instance: actual
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: actual
    helm.sh/chart: actual-5.0.1
  namespace: actual
