apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: bentopdf
  namespace: bentopdf
  labels:
    app.kubernetes.io/name: bentopdf
    app.kubernetes.io/instance: bentopdf
    app.kubernetes.io/part-of: bentopdf
spec:
  name: "BentoPDF"
  launchUrl: https://bentopdf.alexlebens.dev
  description: "A privacy first PDF toolkit."
  callbackUrls:
    - https://bentopdf.alexlebens.dev/oauth2/callback
  pkceEnabled: true
  skipConsent: true
  allowedUserGroups:
    - name: user
      namespace: pocket-id-operator
  clientID: 42E8BB2A-F67C-4AA5-8A4C-D8317AEE10AE
  clientSecretRef:
    name: bentopdf-oauth-proxy
    key: OAUTH2_PROXY_CLIENT_SECRET
  logo:
    logoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/bentopdf.webp
