apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    {{- include "custom.labels" . | nindent 4 }}
spec:
  name: "Sonarr 4K"
  launchUrl: https://sonarr-4k{{ include "custom.domain" . }}
  description: "A 4K PVR for Usenet and BitTorrent users."
  callbackUrls:
    - https://sonarr-4k{{ include "custom.domain" . }}/oauth2/callback
  pkceEnabled: true
  skipConsent: true
  allowedUserGroups:
    - name: admin
      namespace: pocket-id-operator
  clientID: F7A23B91-8D4C-4E15-92A3-71E9284D60B5
  clientSecretRef:
    name: {{ include "custom.defaultOauthProxySecret" . }}
    key: OAUTH2_PROXY_CLIENT_SECRET
  logo:
    logoUrl: {{ include "custom.iconUrl" . }}sonarr.webp
    darkLogoUrl: {{ include "custom.iconUrl" . }}sonarr-light.webp
