apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: web-assets-secret-backup-a
  namespace: web-assets
  labels:
    app.kubernetes.io/name: web-assets-secret-backup-a
    helm.sh/chart: s3-bucket-0.6.2
    app.kubernetes.io/name: web-assets
    app.kubernetes.io/instance: web-assets
    app.kubernetes.io/version: "v1.75.1"
    app.kubernetes.io/managed-by: Helm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /ps02sn/garage/keys/web-assets
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /ps02sn/garage/keys/web-assets
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_REGION
      remoteRef:
        key: /ps02sn/garage/keys/web-assets
        property: AWS_REGION
    - secretKey: ENDPOINT
      remoteRef:
        key: /ps02sn/garage/config
        property: ENDPOINT
