{
 "title": "Rclone",
 "tags": [
  "platform",
  "storage",
  "s3"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "rclone_pod",
    "label": "Pod",
    "query": {
     "query": "label_values(rclone_http_status_code{endpoint=\"rc-sync\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$rclone_pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "rclone_pod",
   "targets": [
    {}
   ]
  },
  {
   "title": "Rclone uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{pod=~\"$rclone_pod\", endpoint=\"rc-sync\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Status Totals",
   "type": "piechart",
   "description": "Since rclone process started",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rclone_checked_files_total{pod=~\"$rclone_pod\", endpoint=\"rc-sync\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "rclone_files_transferred_total{instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "rclone_files_renamed_total{instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "rclone_files_deleted_total{instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "rclone_dirs_deleted_total{instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "rclone_errors_total{instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "HTTP Status Code Totals",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rclone_http_status_code{pod=~\"$rclone_pod\", endpoint=\"rc-sync\"}",
     "legendFormat": "{{ method }} {{ host }} {{ code }}"
    }
   ]
  },
  {
   "title": "/metrcs - Requests by response code",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{pod=~\"$rclone_pod\", endpoint=\"rc-sync\"}",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Total Data Transferred",
   "type": "stat",
   "description": "Since rclone process started",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rclone_bytes_transferred_total{pod=~\"$rclone_pod\", endpoint=\"rc-sync\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Speed",
   "type": "stat",
   "description": "Since rclone process started",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rclone_speed{pod=~\"$rclone_pod\", endpoint=\"rc-sync\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status per action",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(rclone_checked_files_total{pod=~\"$rclone_pod\", endpoint=\"rc-sync\"}[$__rate_interval])",
     "legendFormat": "rclone_checked_files_total"
    },
    {
     "expr": "rate(rclone_files_transferred_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "rclone_files_transferred_total"
    },
    {
     "expr": "rate(rclone_files_renamed_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "rclone_files_renamed_total"
    },
    {
     "expr": "rate(rclone_files_deleted_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "rclone_files_deleted_total"
    },
    {
     "expr": "rate(rclone_dirs_deleted_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "rclone_dirs_deleted_total"
    },
    {
     "expr": "rate(rclone_errors_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "rclone_errors_total"
    }
   ]
  },
  {
   "title": "Data Transferred",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rclone_bytes_transferred_total{pod=~\"$rclone_pod\", endpoint=\"rc-sync\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Data Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(rclone_bytes_transferred_total{pod=~\"$rclone_pod\", endpoint=\"rc-sync\"}[$__rate_interval])",
     "legendFormat": "bytes_transferred_total"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_threads{pod=~\"$rclone_pod\", endpoint=\"rc-sync\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "process_cpu_seconds_total"
    }
   ]
  },
  {
   "title": "Go Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{pod=~\"$rclone_pod\", endpoint=\"rc-sync\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "go_goroutines{pod=~\"$rclone_pod\", endpoint=\"rc-sync\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Go Heap Objects",
   "type": "timeseries",
   "description": "Total number of allocated objects",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_heap_objects{pod=~\"$rclone_pod\", endpoint=\"rc-sync\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Go Heap Memory Overview",
   "type": "timeseries",
   "description": "**Allocated:** The amount of memory Rclone is actually using.  \n**Sys:** The amount of memory obtained from the OS.  \n**Sys requested:** The amount of memory requested from the OS.",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{pod=~\"$rclone_pod\", endpoint=\"rc-sync\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{pod=~\"$rclone_pod\", endpoint=\"rc-sync\"}",
     "legendFormat": "{{ __name__ }}"
    },
    {
     "expr": "process_max_fds{instance=\"$instance\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  }
 ]
}