apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-ps09rp-web-assets-http-2xx
  namespace: web-assets
  labels:
    app.kubernetes.io/name: blackbox-ps09rp-web-assets-http-2xx
    app.kubernetes.io/instance: web-assets
    app.kubernetes.io/part-of: web-assets
spec:
  prober:
    url: ps09rp.alexlebens.dev:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - https://web-assets.alexlebens.dev/logo/logo.svg
