apiVersion: v1
kind: Service
metadata:
  name: web-assets-web-assets-local-rclone
  labels:
    app.kubernetes.io/instance: web-assets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: web-assets-local-rclone
    app.kubernetes.io/service: web-assets-web-assets-local-rclone
    app.kubernetes.io/version: v1.75.0
    helm.sh/chart: rclone-web-assets-local-2.0.0
  namespace: web-assets
spec:
  type: ClusterIP
  ports:
    - port: 5572
      targetPort: 5572
      protocol: TCP
      name: rc-sync
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: web-assets
    app.kubernetes.io/name: web-assets-local-rclone
