blocky:
  controllers:
    main:
      type: deployment
      replicas: 3
      strategy: RollingUpdate
      containers:
        main:
          image:
            repository: ghcr.io/0xerr0r/blocky
            tag: v0.34.0@sha256:595136fb127f4c952b621113e668c09acdcf15ac054d96ee6d4c51a76c35f5fd
          env:
            - name: TZ
              value: America/Chicago
          resources:
            requests:
              cpu: 10m
              memory: 150Mi
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                tcpSocket:
                  port: 53
            readiness:
              enabled: true
              custom: true
              spec:
                tcpSocket:
                  port: 53
  configMaps:
    config:
      enabled: true
      data:
        config.yml: |
          upstreams:
            init:
              strategy: fast
            groups:
              default:
                - tcp-tls:1.1.1.1:853
                - tcp-tls:1.0.0.1:853
            strategy: parallel_best
            timeout: 2s

          connectIPVersion: v4

          conditional:
            fallbackUpstream: true
            mapping:
              auth.alexlebens.dev: tcp-tls:1.1.1.1:853
              docs.alexlebens.dev: tcp-tls:1.1.1.1:853
              blog.alexlebens.dev: tcp-tls:1.1.1.1:853
              gitea.alexlebens.dev: tcp-tls:1.1.1.1:853
              art.alexlebens.dev: tcp-tls:1.1.1.1:853
              chat.alexlebens.dev: tcp-tls:1.1.1.1:853
              immich.alexlebens.dev: tcp-tls:1.1.1.1:853
              karakeep.alexlebens.dev: tcp-tls:1.1.1.1:853
              matrix.alexlebens.dev: tcp-tls:1.1.1.1:853
              ntfy.alexlebens.dev: tcp-tls:1.1.1.1:853
              outline.alexlebens.dev: tcp-tls:1.1.1.1:853
              passwords.alexlebens.dev: tcp-tls:1.1.1.1:853
              postiz.alexlebens.dev: tcp-tls:1.1.1.1:853
              rss.alexlebens.dev: tcp-tls:1.1.1.1:853
              rybbit.alexlebens.dev: tcp-tls:1.1.1.1:853
              trek.alexlebens.dev: tcp-tls:1.1.1.1:853
              www.alexlebens.dev: tcp-tls:1.1.1.1:853
              web-assets.alexlebens.dev: tcp-tls:1.1.1.1:853
              alexlebens.net: tcp+udp:powerdns.blocky:53
              alexlebens.dev: tcp+udp:powerdns.blocky:53

          blocking:
            denylists:
              sus:
                - https://v.firebog.net/hosts/static/w3kbl.txt
              ads:
                - https://v.firebog.net/hosts/AdguardDNS.txt
                - https://v.firebog.net/hosts/Admiral.txt
                - https://v.firebog.net/hosts/Easylist.txt
                - https://adaway.org/hosts.txt
              priv:
                - https://v.firebog.net/hosts/Easyprivacy.txt
                - https://v.firebog.net/hosts/Prigent-Ads.txt
              mal:
                - https://v.firebog.net/hosts/Prigent-Crypto.txt
              pro:
                - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro.plus.txt
              oisd:
                - https://big.oisd.nl/domainswild
            allowlists:
              sus: &my_allowlist
                - |
                  *.alexlebens.net
                  *.alexlebens.dev
                  *.boreal-beaufort.ts.net
                  *.discord.com
                  cdn.trackjs.com
                  e.customeriomail.com
              ads: *my_allowlist
              priv: *my_allowlist
              mal: *my_allowlist
              pro: *my_allowlist
              oisd: *my_allowlist
            clientGroupsBlock:
              default:
                - sus
                - ads
                - priv
                - mal
                - pro
                - oisd
            blockType: zeroIp
            blockTTL: 1m
            loading:
              refreshPeriod: 24h
              downloads:
                timeout: 60s
                attempts: 5
                cooldown: 10s
              concurrency: 16
              strategy: fast
              maxErrorsPerSource: 5

          caching:
            minTime: 5m
            maxTime: 30m
            maxItemsCount: 20000
            prefetching: true
            prefetchExpires: 2h
            prefetchThreshold: 5
            prefetchMaxItemsCount: 5000
            cacheTimeNegative: 30m

          redis:
            address: blocky-valkey.blocky:6379
            required: true

          prometheus:
            enable: true
            path: /metrics

          queryLog:
            type: none

          minTlsServeVersion: 1.3

          ports:
            dns: 53
            http: 4000

          log:
            level: info
            format: text
            timestamp: true
            privacy: false
  service:
    dns-external:
      type: LoadBalancer
      annotations:
        tailscale.com/expose: "true"
        lbipam.cilium.io/ips: "10.234.0.32"
        external-dns.kubernetes.io/hostname: blocky.alexlebens.net
      ports:
        tcp:
          port: 53
          protocol: TCP
        udp:
          port: 53
          protocol: UDP
    metrics:
      controller: main
      ports:
        metrics:
          port: 4000
  serviceMonitor:
    main:
      selector:
        matchLabels:
          app.kubernetes.io/name: blocky
          app.kubernetes.io/instance: blocky
      serviceName: blocky-metrics
      endpoints:
        - port: metrics
  persistence:
    config:
      enabled: true
      type: configMap
      name: blocky
      advancedMounts:
        main:
          main:
            - path: /app/config.yml
              subPath: config.yml
              readOnly: true
powerdns:
  fullnameOverride: powerdns
  controllers:
    powerdns:
      type: deployment
      replicas: 3
      strategy: RollingUpdate
      containers:
        main:
          image:
            repository: powerdns/pdns-auth-51
            tag: 5.1.4@sha256:bb5b1c133bcca1dd455075321de7d55db4945a8d7f2ba23339e3c7bbe416b205
          args:
            - --no-config
            - --max-tcp-connections=1000
            - --api=yes
            - --api-key=$(PDNS_AUTH_API_KEY)
            - --webserver=yes
            - --webserver-address=0.0.0.0
            - --webserver-allow-from=0.0.0.0/0,::/0
            - --launch=gpgsql
            - --gpgsql-host=$(PDNS_AUTH_GPGSQL_HOST)
            - --gpgsql-dbname=$(PDNS_AUTH_GPGSQL_DBNAME)
            - --gpgsql-user=$(PDNS_AUTH_GPGSQL_USER)
            - --gpgsql-password=$(PDNS_AUTH_GPGSQL_PASSWORD)
          env:
            - name: PDNS_AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: powerdns-api-key
                  key: api-key
            - name: PDNS_AUTH_GPGSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: powerdns-postgresql-18-cluster-app
                  key: host
            - name: PDNS_AUTH_GPGSQL_DBNAME
              valueFrom:
                secretKeyRef:
                  name: powerdns-postgresql-18-cluster-app
                  key: dbname
            - name: PDNS_AUTH_GPGSQL_USER
              valueFrom:
                secretKeyRef:
                  name: powerdns-postgresql-18-cluster-app
                  key: username
            - name: PDNS_AUTH_GPGSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: powerdns-postgresql-18-cluster-app
                  key: password
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                exec:
                  command:
                    - pdns_control
                    - rping
            readiness:
              enabled: true
              custom: true
              spec:
                exec:
                  command:
                    - pdns_control
                    - rping
  service:
    main:
      controller: powerdns
      ports:
        http:
          port: 8081
        dns-tcp:
          port: 53
          protocol: TCP
        dns-udp:
          port: 53
          protocol: UDP
powerdns-postgres-18-cluster:
  nameOverride: powerdns-postgresql-18
  mode: recovery
  cluster:
    initdb:
      postInitApplicationSQL:
        - |
          CREATE TABLE domains (
            id                    SERIAL PRIMARY KEY,
            name                  VARCHAR(255) NOT NULL,
            master                VARCHAR(128) DEFAULT NULL,
            last_check            INT DEFAULT NULL,
            type                  TEXT NOT NULL,
            notified_serial       BIGINT DEFAULT NULL,
            account               VARCHAR(40) DEFAULT NULL,
            options               TEXT DEFAULT NULL,
            catalog               TEXT DEFAULT NULL,
            CONSTRAINT c_lowercase_name CHECK (((name)::TEXT = LOWER((name)::TEXT)))
          );
          CREATE UNIQUE INDEX name_index ON domains(name);
          CREATE INDEX catalog_idx ON domains(catalog);

          CREATE TABLE records (
            id                    BIGSERIAL PRIMARY KEY,
            domain_id             INT DEFAULT NULL,
            name                  VARCHAR(255) DEFAULT NULL,
            type                  VARCHAR(10) DEFAULT NULL,
            content               VARCHAR(65535) DEFAULT NULL,
            ttl                   INT DEFAULT NULL,
            prio                  INT DEFAULT NULL,
            disabled              BOOL DEFAULT 'f',
            ordername             VARCHAR(255),
            auth                  BOOL DEFAULT 't',
            CONSTRAINT domain_exists
            FOREIGN KEY(domain_id) REFERENCES domains(id)
            ON DELETE CASCADE,
            CONSTRAINT c_lowercase_name CHECK (((name)::TEXT = LOWER((name)::TEXT)))
          );

          CREATE INDEX rec_name_index ON records(name);
          CREATE INDEX nametype_index ON records(name,type);
          CREATE INDEX domain_id ON records(domain_id);
          CREATE INDEX recordorder ON records (domain_id, ordername text_pattern_ops);

          CREATE TABLE supermasters (
            ip                    INET NOT NULL,
            nameserver            VARCHAR(255) NOT NULL,
            account               VARCHAR(40) NOT NULL,
            PRIMARY KEY(ip, nameserver)
          );

          CREATE TABLE comments (
            id                    SERIAL PRIMARY KEY,
            domain_id             INT NOT NULL,
            name                  VARCHAR(255) NOT NULL,
            type                  VARCHAR(10) NOT NULL,
            modified_at           INT NOT NULL,
            account               VARCHAR(40) DEFAULT NULL,
            comment               VARCHAR(65535) NOT NULL,
            CONSTRAINT domain_exists
            FOREIGN KEY(domain_id) REFERENCES domains(id)
            ON DELETE CASCADE,
            CONSTRAINT c_lowercase_name CHECK (((name)::TEXT = LOWER((name)::TEXT)))
          );
          CREATE INDEX comments_domain_id_idx ON comments (domain_id);
          CREATE INDEX comments_name_type_idx ON comments (name, type);
          CREATE INDEX comments_order_idx ON comments (domain_id, modified_at);

          CREATE TABLE domainmetadata (
            id                    SERIAL PRIMARY KEY,
            domain_id             INT REFERENCES domains(id) ON DELETE CASCADE,
            kind                  VARCHAR(32),
            content               TEXT
          );

          CREATE INDEX domainidmetaindex ON domainmetadata(domain_id);


          CREATE TABLE cryptokeys (
            id                    SERIAL PRIMARY KEY,
            domain_id             INT REFERENCES domains(id) ON DELETE CASCADE,
            flags                 INT NOT NULL,
            active                BOOL,
            published             BOOL DEFAULT TRUE,
            content               TEXT
          );
          CREATE INDEX domainidindex ON cryptokeys(domain_id);

          CREATE TABLE tsigkeys (
            id                    SERIAL PRIMARY KEY,
            name                  VARCHAR(255),
            algorithm             VARCHAR(50),
            secret                VARCHAR(255),
            CONSTRAINT c_lowercase_name CHECK (((name)::TEXT = LOWER((name)::TEXT)))
          );
          CREATE UNIQUE INDEX namealgoindex ON tsigkeys(name, algorithm);

          INSERT INTO domains (name, type)
          VALUES ('alexlebens.net', 'NATIVE');

          INSERT INTO domains (name, type)
          VALUES ('alexlebens.dev', 'NATIVE');

          INSERT INTO records (domain_id, name, type, content, ttl, auth)
          SELECT id, 'alexlebens.net', 'SOA', 'ns1.alexlebens.net hostmaster.alexlebens.net 1 10800 3600 604800 3600', 3600, true
          FROM domains
          WHERE name = 'alexlebens.net';

          INSERT INTO records (domain_id, name, type, content, ttl, auth)
          SELECT id, 'alexlebens.dev', 'SOA', 'ns1.alexlebens.dev hostmaster.alexlebens.dev 1 10800 3600 604800 3600', 3600, true
          FROM domains
          WHERE name = 'alexlebens.dev';

          INSERT INTO records (domain_id, name, type, content, ttl, auth)
          SELECT id, 'alexlebens.net', 'NS', 'ns1.alexlebens.net', 3600, true
          FROM domains
          WHERE name = 'alexlebens.net';

          INSERT INTO records (domain_id, name, type, content, ttl, auth)
          SELECT id, 'alexlebens.dev', 'NS', 'ns1.alexlebens.dev', 3600, true
          FROM domains
          WHERE name = 'alexlebens.dev';

          GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO app;
          GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO app;
  recovery:
    objectStore:
      index: 1
  backup:
    objectStore:
      index: 1
    scheduledBackups:
      suspend: false
      schedule: "0 25 15 * * *"
