apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-keys-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: homepage-keys-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: HOMEPAGE_VAR_GITEA_API_TOKEN
      remoteRef:
        key: /cl01tl/gitea/auth/homepage
        property: token
    - secretKey: HOMEPAGE_VAR_ARGOCD_API_TOKEN
      remoteRef:
        key: /cl01tl/argocd/credentials/homepage
        property: token
    - secretKey: HOMEPAGE_VAR_KOMODO_API_KEY
      remoteRef:
        key: /cl01tl/komodo/homepage
        property: key
    - secretKey: HOMEPAGE_VAR_KOMODO_API_SECRET
      remoteRef:
        key: /cl01tl/komodo/homepage
        property: secret
    - secretKey: HOMEPAGE_VAR_JELLYSTAT_API_KEY
      remoteRef:
        key: /cl01tl/jellystat/homepage
        property: key
    - secretKey: HOMEPAGE_VAR_SYNOLOGY_USER
      remoteRef:
        key: /synology/auth/cl01tl
        property: user
    - secretKey: HOMEPAGE_VAR_SYNOLOGY_PASSWORD
      remoteRef:
        key: /synology/auth/cl01tl
        property: password
    - secretKey: HOMEPAGE_VAR_UNIFI_API_KEY
      remoteRef:
        key: /unifi/auth/cl01tl
        property: api-key
    - secretKey: HOMEPAGE_VAR_SONARR_KEY
      remoteRef:
        key: /cl01tl/sonarr4/key
        property: key
    - secretKey: HOMEPAGE_VAR_SONARR4K_KEY
      remoteRef:
        key: /cl01tl/sonarr4-4k/key
        property: key
    - secretKey: HOMEPAGE_VAR_SONARRANIME_KEY
      remoteRef:
        key: /cl01tl/sonarr4-anime/key
        property: key
    - secretKey: HOMEPAGE_VAR_RADARR_KEY
      remoteRef:
        key: /cl01tl/radarr5/key
        property: key
    - secretKey: HOMEPAGE_VAR_RADARR4K_KEY
      remoteRef:
        key: /cl01tl/radarr5-4k/key
        property: key
    - secretKey: HOMEPAGE_VAR_RADARRANIME_KEY
      remoteRef:
        key: /cl01tl/radarr5-anime/key
        property: key
    - secretKey: HOMEPAGE_VAR_RADARRSTANDUP_KEY
      remoteRef:
        key: /cl01tl/radarr5-standup/key
        property: key
    - secretKey: HOMEPAGE_VAR_LIDARR_KEY
      remoteRef:
        key: /cl01tl/lidarr2/key
        property: key
    - secretKey: HOMEPAGE_VAR_PROWLARR_KEY
      remoteRef:
        key: /cl01tl/prowlarr/key
        property: key
