apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-custom-templates
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gitea-custom-templates
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
data:
  header.tmpl: |
    <script defer src="https://rybbit.alexlebens.dev/api/script.js" data-website-id="b515c34a6dcc"></script>
