apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-assets-secret-backup-primary
  namespace: pocket-id-operator
  labels:
    app.kubernetes.io/name: pocket-id-assets-secret-backup-primary
    helm.sh/chart: garage-bucket-pocket-id-assets-0.3.10
    app.kubernetes.io/instance: pocket-id-operator
    app.kubernetes.io/part-of: pocket-id-operator
    app.kubernetes.io/version: "v0.7.5"
    app.kubernetes.io/managed-by: Helm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /garage/home-infra/pocket-id-assets
        property: ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /garage/home-infra/pocket-id-assets
        property: ACCESS_SECRET_KEY
    - secretKey: AWS_REGION
      remoteRef:
        key: /garage/home-infra/pocket-id-assets
        property: ACCESS_REGION
