apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-s3
  namespace: pocket-id-operator
  labels:
    app.kubernetes.io/name: pocket-id-s3
    app.kubernetes.io/instance: pocket-id-operator
    app.kubernetes.io/part-of: pocket-id-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: access-key
      remoteRef:
        key: /garage/home-infra/pocket-id-assets
        property: ACCESS_KEY_ID
    - secretKey: secret-key
      remoteRef:
        key: /garage/home-infra/pocket-id-assets
        property: ACCESS_SECRET_KEY
