apiVersion: garage.rajsingh.info/v1beta1
kind: GarageReferenceGrant
metadata:
  name: pocket-id-assets-grant
  namespace: garage-operator
  labels:
    app.kubernetes.io/name: pocket-id-assets-grant
    helm.sh/chart: garage-bucket-pocket-id-assets-0.3.11
    app.kubernetes.io/instance: pocket-id-operator
    app.kubernetes.io/part-of: pocket-id-operator
    app.kubernetes.io/version: "v0.7.6"
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  from:
    - kind: GarageKey
      namespace: pocket-id-operator
    - kind: GarageBucket
      namespace: pocket-id-operator
  to:
    - kind: GarageCluster
      name: garage-cluster-a
