apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: pocket-id-assets-key
  namespace: pocket-id-operator
  labels:
    app.kubernetes.io/name: pocket-id-assets-key
    helm.sh/chart: garage-bucket-pocket-id-assets-0.3.7
    app.kubernetes.io/instance: pocket-id-operator
    app.kubernetes.io/part-of: pocket-id-operator
    app.kubernetes.io/version: "v0.7.4"
    app.kubernetes.io/managed-by: Helm
spec:
  name: pocket-id-assets-key
  clusterRef:
    name: garage-cluster-a
    namespace: garage-operator
  importKey:
    secretRef:
      name: pocket-id-assets-secret
    accessKeyIdKey: AWS_ACCESS_KEY_ID
    secretAccessKeyKey: AWS_SECRET_ACCESS_KEY
  bucketPermissions:
    - bucketRef:
        name: pocket-id-assets
      read: true
      write: true
      owner: true
