apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: synology
  namespace: pocket-id-operator
  labels:
    app.kubernetes.io/name: synology
    app.kubernetes.io/instance: pocket-id-operator
    app.kubernetes.io/part-of: pocket-id-operator
spec:
  name: "Synology"
  launchUrl: https://synology.alexlebens.dev/
  description: "Network attached storage providing NFS and iSCSI targets."
  callbackUrls:
    - https://synology.alexlebens.dev/
  pkceEnabled: false
  skipConsent: true
  allowedUserGroups:
    - name: platform-admin
      namespace: pocket-id-operator
  clientID: 3A4C9417-654B-4996-8924-5DD24E8549D8
  clientSecretRef:
    name: synology-oidc-secret
    key: clientSecret
  logo:
    logoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/synology.webp
    darkLogoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/synology-light.webp
