apiVersion: pocketid.internal/v1alpha1
kind: PocketIDInstance
metadata:
  name: pocket-id-instance
  namespace: pocket-id-operator
  labels:
    app.kubernetes.io/name: pocket-id
    helm.sh/chart: pocket-id-instance-0.14.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: pocket-id
    app.kubernetes.io/instance: pocket-id-operator
    app.kubernetes.io/component: instance
    app.kubernetes.io/version: "v0.14.2"
    pocketid.internal/instance: pocket-id-instance
spec:
  appUrl: https://auth.alexlebens.dev
  auditLogRetentionDays: 30
  databaseUrl:
    valueFrom:
      secretKeyRef:
        key: uri
        name: pocket-id-operator-postgresql-18-cluster-app
  encryptionKey:
    valueFrom:
      secretKeyRef:
        key: key
        name: pocket-id-encryption
  geoip:
    maxmindLicenseKey:
      valueFrom:
        secretKeyRef:
          key: license-key
          name: pocket-id-maxmind
  image: ghcr.io/pocket-id/pocket-id:v2.14.0-distroless@sha256:e0f83a42a78d0759b6d2d8c7380ef0fa8a4c95dfa01ad88740a073ae9cc4ba94
  logging:
    json: true
    level: info
  metrics:
    enabled: true
  podTemplate:
    spec:
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 30
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 30
  route:
    enabled: false
    parentRefs:
      - name: traefik-gateway
        namespace: traefik
  s3:
    accessKeyId:
      valueFrom:
        secretKeyRef:
          key: access-key-id
          name: pocket-id-assets-key
    bucket: pocket-id-assets
    endpoint: http://garage-cluster-a.garage-operator.svc.cluster.local:3900
    forcePathStyle: true
    region: garage
    secretAccessKey:
      valueFrom:
        secretKeyRef:
          key: secret-access-key
          name: pocket-id-assets-key
  timezone: America/Chicago
  trustedProxies:
    cidrs:
      - 10.244.0.0/16
    enabled: true
  ui:
    accentColor: '#FD5E53'
    appName: AlexAuth
    sessionDuration: 43200
  userManagement:
    allowOwnAccountEdit: true
    allowUserSignups: disabled
    emailsVerified: true
  versionCheckDisabled: true
