apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUser
metadata:
  name: andrewlebens
  namespace: pocket-id-operator
  labels:
    app.kubernetes.io/name: pocket-id
    helm.sh/chart: pocket-id-instance-0.14.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: pocket-id
    app.kubernetes.io/instance: pocket-id-operator
    app.kubernetes.io/component: user
    app.kubernetes.io/version: "v0.14.0"
spec:
  instanceSelector:
    matchLabels:
      pocketid.internal/instance: pocket-id-instance
  locale: en
  userID: 046779f0-f2a5-4f46-9c42-fbc002333e64
  userInfoSecretRef:
    name: pocket-id-andrewlebens-user-info
