apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-cl01tl-pocket-id-operator-http-2xx
  namespace: pocket-id-operator
  labels:
    app.kubernetes.io/name: blackbox-cl01tl-pocket-id-operator-http-2xx
    app.kubernetes.io/instance: pocket-id-operator
    app.kubernetes.io/part-of: pocket-id-operator
spec:
  prober:
    url: kube-prometheus-stack-prometheus-blackbox-exporter.kube-prometheus-stack.svc.cluster.local:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - http://pocket-id-instance.pocket-id-operator:1411
