apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    helm.sh/chart: pocket-id-operator-0.13.0
    app.kubernetes.io/name: pocket-id-operator
    app.kubernetes.io/instance: pocket-id-operator
    app.kubernetes.io/version: "v0.13.0"
    app.kubernetes.io/managed-by: Helm
  name: pocket-id-operator-leader-election-role
  namespace: pocket-id-operator
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
