apiVersion: v1
kind: ServiceAccount
metadata:
  name: pocket-id-operator-pocket-id-assets-rclone
  labels:
    app.kubernetes.io/instance: pocket-id-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pocket-id-assets-rclone
    app.kubernetes.io/version: v1.75.0
    helm.sh/chart: rclone-pocket-id-assets-remote-1.1.0
  namespace: pocket-id-operator
