apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-karakeep-secret
  namespace: rclone
  labels:
    app.kubernetes.io/name: garage-karakeep-secret
    app.kubernetes.io/instance: rclone
    app.kubernetes.io/part-of: rclone
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: /garage/home-infra/karakeep-assets
        property: ACCESS_KEY_ID
    - secretKey: ACCESS_REGION
      remoteRef:
        key: /garage/home-infra/karakeep-assets
        property: ACCESS_REGION
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: /garage/home-infra/karakeep-assets
        property: ACCESS_SECRET_KEY
    - secretKey: SRC_ENDPOINT
      remoteRef:
        key: /garage/config
        property: ENDPOINT_LOCAL
    - secretKey: DEST_ENDPOINT
      remoteRef:
        key: /garage/config
        property: ENDPOINT_REMOTE
