secrets-store-csi-driver:
  linux:
    image:
      repository: registry.k8s.io/csi-secrets-store/driver
      tag: v1.6.1@sha256:b48d7d13dd06f0c7fdb2ec03683387e229d80d327172ecb0e21948b811540c6e
    crds:
      image:
        repository: registry.k8s.io/csi-secrets-store/driver-crds
        tag: v1.6.1@sha256:cdacfdbe8966aa77c080b850b52a86880363119530f7aa6b4f05b8ffe19c2ec3
    driver:
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
    registrarImage:
      repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
      tag: v2.17.0@sha256:f9de845b170155199f2a2a3f9531cf13d78e31235e9db6b6582a8b0db0a50dad
    registrar:
      resources:
        requests:
          cpu: 1m
          memory: 10Mi
    livenessProbeImage:
      repository: registry.k8s.io/sig-storage/livenessprobe
      tag: v2.19.0@sha256:06da0d5b8908072f2e4522692aee8dc119fba7247a9658497e1153992cd777e9
    livenessProbe:
      resources:
        requests:
          cpu: 1m
          memory: 10Mi
