---
services:
    tailscale-komodo-periphery:
        image: ghcr.io/tailscale/tailscale:v1.96.5@sha256:dbeff02d2337344b351afac203427218c4d0a06c43fc10a865184063498472a6
        container_name: tailscale-komodo-periphery
        cap_add:
            - net_admin
            - sys_module
        environment:
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_ENABLE_METRICS=true
            - TS_HOSTNAME=komodo-periphery-ps10rp
        env_file:
            - .ts-env
        network_mode: service:komodo-periphery
        restart: always
        volumes:
            - tailscale:/var/lib/tailscale
        devices:
            - /dev/net/tun:/dev/net/tun

    komodo-periphery:
        image: ghcr.io/moghtech/komodo-periphery:2.1.2@sha256:8ac9f2ef9c1461b95c862d445da00253005e7094d1e30f5b7b04b8d60ca7a3d6
        container_name: komodo-periphery
        init: true
        env_file:
            - .komodo-env
        environment:
            - TZ=America/Chicago
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /proc:/proc
            - /mnt/data/komodo:/etc/komodo
            - keys:/config/keys

volumes:
    tailscale:
    keys:
