---
services:
  tailscale-komodo-periphery:
    image: ghcr.io/tailscale/tailscale:v1.102.2@sha256:321ce041508c19079b57a28b6666c8d81ab0b08accc0a2585b3ab663d557ac24
    container_name: tailscale-komodo-periphery
    cap_add:
      - net_admin
      - sys_module
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ENABLE_METRICS=true
      - TS_HOSTNAME=komodo-periphery-ps10rp
    env_file:
      - .ts-env
    network_mode: service:komodo-periphery
    restart: always
    volumes:
      - tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun

  komodo-periphery:
    image: ghcr.io/moghtech/komodo-periphery:2.3.2@sha256:639e019751642518a0fbdc2720e5f39789e76aa495a499852b9585ffacf71149
    container_name: komodo-periphery
    init: true
    env_file:
      - .komodo-env
    environment:
      - TZ=America/Chicago
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - /mnt/data/komodo:/etc/komodo
      - keys:/config/keys

volumes:
  tailscale:
  keys:
