apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-csi-operator-image-set-configmap
  namespace: rook-ceph
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: v1.21.0
    app.kubernetes.io/part-of: rook-ceph-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/created-by: helm
    helm.sh/chart: "rook-ceph-1.21.0"
data:
  provisioner: ""
  attacher: ""
  resizer: ""
  snapshotter: ""
  registrar: ""
  plugin: "quay.io/cephcsi/cephcsi:v3.17.1"
  addons: ""
