{
 "title": "Ceph",
 "tags": [
  "system",
  "storage"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cluster State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ceph health status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_health_status" }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes[5m]))"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes[5m]))"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_cluster_total_bytes" }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ceph_cluster_total_bytes-ceph_cluster_total_used_bytes)/ceph_cluster_total_bytes"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_pool_objects)" }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    { "expr": "sum(ceph_osd_op_w_in_bytes)" }
   ]
  },
  {
   "title": "Bytes Read",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    { "expr": "sum(ceph_osd_op_r_out_bytes)" }
   ]
  },
  {
   "title": "Alerts starting with Ceph",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",alertname=~\"^Ceph.+\"}) OR vector(0)"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(irate(ceph_osd_op_w[5m]))" }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(irate(ceph_osd_op_r[5m]))" }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_cluster_total_used_bytes" }
   ]
  },
  {
   "title": "Difference",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "expr": "sum(ceph_pool_objects)" }
   ]
  },
  {
   "title": "Mon Session Num",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_mon_num_sessions)" }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_mon_quorum_status) or vector(0)"
    }
   ]
  },
  {
   "title": "OSD State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OSDs OUT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up) - count(ceph_osd_in)"
    }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up == 0.0) OR vector(0)"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_osd_up)" }
   ]
  },
  {
   "title": "OSDs IN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_osd_in)" }
   ]
  },
  {
   "title": "Avg PGs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_osd_numpg)" }
   ]
  },
  {
   "title": "Avg Apply Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(ceph_osd_apply_latency_ms)" }
   ]
  },
  {
   "title": "Avg Commit Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms)"
    }
   ]
  },
  {
   "title": "Avg Op Write Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_w_latency_sum[5m]) / rate(ceph_osd_op_w_latency_count[5m]) >= 0)"
    }
   ]
  },
  {
   "title": "Avg Op Read Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_r_latency_sum[5m])/rate(ceph_osd_op_r_latency_count[5m]) >= 0)"
    }
   ]
  },
  {
   "title": "Cluster Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ceph_cluster_total_bytes{}-ceph_cluster_total_used_bytes{}",
       "legendFormat": "Available"
      },
      { "expr": "ceph_cluster_total_bytes{}", "legendFormat": "Total Capacity" }
     ]
    },
    {
     "title": "IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "sum(irate(ceph_osd_op_w[5m]))", "legendFormat": "Write" },
      { "expr": "sum(irate(ceph_osd_op_r[5m]))", "legendFormat": "Read" }
     ]
    },
    {
     "title": "Cluster Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(irate(ceph_osd_op_w_in_bytes{}[5m]))",
       "legendFormat": "Write"
      },
      {
       "expr": "sum(irate(ceph_osd_op_r_out_bytes{}[5m]))",
       "legendFormat": "Read"
      }
     ]
    },
    {
     "title": "Pool Used Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(ceph_pool_bytes_used{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Pool RAW Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(ceph_pool_avail_raw{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
       "legendFormat": "{{name}} Avail"
      },
      {
       "expr": "(ceph_pool_stored_raw{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
       "legendFormat": "{{name}} Stored"
      }
     ]
    },
    {
     "title": "OSD Type Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(ceph_bluestore_kv_commit_lat_count{})",
       "legendFormat": "BlueStore"
      }
     ]
    },
    {
     "title": "Objects Per Pool",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(ceph_pool_objects{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Pool Quota Bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(ceph_pool_quota_bytes{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Pool Objects Quota",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(ceph_pool_quota_objects{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Alerts starting with Ceph",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 548 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ALERTS{alertstate=\"firing\",alertname=~\"^Ceph.+\"}"
      }
     ]
    },
    {
     "title": "Top Sluggish OSDs",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 548 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,sort_desc(ceph_osd_apply_latency_ms{} + ceph_osd_commit_latency_ms{}))",
       "legendFormat": "_auto"
      }
     ]
    },
    {
     "title": "Down OSDs",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 548 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "ceph_osd_up{} == 0" }
     ]
    }
   ]
  },
  {
   "title": "Node Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Node Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 555 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Active_anon_bytes{}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(node_memory_Active_anon_bytes{})",
       "legendFormat": "Cluster Memory Usage"
      }
     ]
    },
    {
     "title": "Node CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 555 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by(instance)(irate(node_cpu_seconds_total{job='node',mode!=\"idle\"}[$__interval])) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node Out",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 564 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (instance)(irate(node_disk_read_bytes_total{}[$__interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node In",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 573 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (instance)(irate(node_disk_written_bytes_total{}[$__interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Free Space in root filesystem",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 582 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_filesystem_free_bytes{ mountpoint=\"/\", device != \"rootfs\"})*100 / (node_filesystem_size_bytes{ mountpoint=\"/\", device != \"rootfs\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Objects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "OSD Type Count",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 786 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "sum(ceph_pool_objects)", "legendFormat": "Total" }
     ]
    },
    {
     "title": "PGs State",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 6, "y": 786 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "sum(ceph_pg_active{})", "legendFormat": "Active" },
      { "expr": "sum(ceph_pg_clean{})", "legendFormat": "Clean" },
      { "expr": "sum(ceph_pg_peering{})", "legendFormat": "Peering" },
      { "expr": "sum(ceph_pg_degraded{})", "legendFormat": "Degraded" },
      { "expr": "sum(ceph_pg_stale{})", "legendFormat": "Stale" },
      { "expr": "sum(ceph_unclean_pgs{})", "legendFormat": "Unclean" },
      { "expr": "sum(ceph_pg_undersized{})", "legendFormat": "Undersized" },
      { "expr": "sum(ceph_pg_incomplete{})", "legendFormat": "Incomplete" },
      { "expr": "sum(ceph_pg_forced_backfill{})", "legendFormat": "Forced Backfill" },
      { "expr": "sum(ceph_pg_forced_recovery{})", "legendFormat": "Forced Recovery" },
      { "expr": "sum(ceph_pg_creating{})", "legendFormat": "Creating" },
      { "expr": "sum(ceph_pg_wait_backfill{})", "legendFormat": "Wait Backfill" },
      { "expr": "sum(ceph_pg_deep{})", "legendFormat": "Deep" },
      { "expr": "sum(ceph_pg_scrubbing{})", "legendFormat": "Scrubbing" },
      { "expr": "sum(ceph_pg_recovering{})", "legendFormat": "Recovering" },
      { "expr": "sum(ceph_pg_repair{})", "legendFormat": "Repair" },
      { "expr": "sum(ceph_pg_down{})", "legendFormat": "Down" },
      { "expr": "sum(ceph_pg_peered{})", "legendFormat": "Peered" },
      { "expr": "sum(ceph_pg_backfill{})", "legendFormat": "Backfill" },
      { "expr": "sum(ceph_pg_remapped{})", "legendFormat": "Remapped" },
      {
       "expr": "sum(ceph_pg_backfill_toofull{})",
       "legendFormat": "Backfill Toofull"
      }
     ]
    },
    {
     "title": "Stuck PGs",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 786 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "sum(ceph_pg_degraded{})", "legendFormat": "Degraded" },
      { "expr": "sum(ceph_pg_stale{})", "legendFormat": "Stale" },
      { "expr": "sum(ceph_pg_undersized{})", "legendFormat": "Undersized" }
     ]
    },
    {
     "title": "Recovery Operations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 792 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(ceph_osd_recovery_ops{}[$__interval]))",
       "legendFormat": "OPS"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "OSD Apply Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 886 },
     "targets": [
      { "expr": "ceph_osd_apply_latency_ms{}" }
     ]
    },
    {
     "title": "OSD Commit Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 886 },
     "targets": [
      { "expr": "ceph_osd_commit_latency_ms{}" }
     ]
    },
    {
     "title": "OSD Read Op Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 894 },
     "targets": [
      {
       "expr": "rate(ceph_osd_op_r_latency_sum{}[5m]) / rate(ceph_osd_op_r_latency_count{}[5m]) >= 0"
      }
     ]
    },
    {
     "title": "OSD Write Op Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 894 },
     "targets": [
      {
       "expr": "rate(ceph_osd_op_w_latency_sum{}[5m]) / rate(ceph_osd_op_w_latency_count{}[5m]) >= 0"
      }
     ]
    },
    {
     "title": "Recovery Operations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 902 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(rate(ceph_osd_op_r_latency_sum{}[5m]) / rate(ceph_osd_op_r_latency_count{}[5m]) >= 0)",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(rate(ceph_osd_op_w_latency_sum{}[5m]) / rate(ceph_osd_op_w_latency_count{}[5m]) >= 0)",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "AVG OSD Apply + Commit Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 902 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(ceph_osd_apply_latency_ms{})",
       "legendFormat": "apply"
      },
      {
       "expr": "avg(ceph_osd_commit_latency_ms{})",
       "legendFormat": "commit"
      }
     ]
    }
   ]
  },
  {
   "title": "Ceph Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ceph OSD Versions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_osd_metadata{})",
       "legendFormat": "{{cep_version}}"
      }
     ]
    },
    {
     "title": "Ceph Mon Versions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_mon_metadata{})",
       "legendFormat": "{{ceph_version}}"
      }
     ]
    },
    {
     "title": "Ceph MDS Versions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_mds_metadata{})",
       "legendFormat": "{{ceph_version}}"
      }
     ]
    },
    {
     "title": "Ceph RGW Versions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_rgw_metadata{})",
       "legendFormat": "{{ceph_version}}"
      }
     ]
    }
   ]
  }
 ]
}