apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-ps09rp-rook-ceph-http-2xx
  namespace: rook-ceph
  labels:
    app.kubernetes.io/name: blackbox-ps09rp-rook-ceph-http-2xx
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/part-of: rook-ceph
spec:
  prober:
    url: ps09rp.alexlebens.net:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - https://ceph.alexlebens.net
