{
 "title": "AirGradient",
 "tags": [
  "iot",
  "air quality"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "id", "label": "Device", "query": { "query": "label_values(pm02,id)" } },
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(atmp{id=\"$id\"}[$__interval])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(atmp{id=\"$id\"}[$__interval])",
     "legendFormat": "{{sensor_location}}"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(rhum{id=\"$id\"}[$__interval])",
     "legendFormat": "{{sensor_location}}"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(rhum{id=\"$id\"}[$__interval])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CO2 PPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "rco2{id=\"$id\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CO2 PPM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rco2{id=\"$id\"}",
     "legendFormat": "{{sensor_location}}"
    }
   ]
  },
  {
   "title": "Particulate Matter",
   "type": "gauge",
   "description": "PM2.5 describes fine inhalable particles, with diameters that are generally 2.5 micrometers and smaller.",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pm02{id=\"$id\"}",
     "legendFormat": "{{sensor_location}}"
    }
   ]
  },
  {
   "title": "Particulate Matter",
   "type": "timeseries",
   "description": "PM2.5 describes fine inhalable particles, with diameters that are generally 2.5 micrometers and smaller.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "pm02{id=\"$id\"}",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}