apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-ps09rp-yamtrack-http-2xx
  namespace: yamtrack
  labels:
    app.kubernetes.io/name: blackbox-ps09rp-yamtrack-http-2xx
    app.kubernetes.io/instance: yamtrack
    app.kubernetes.io/part-of: yamtrack
spec:
  prober:
    url: ps09rp.alexlebens.net:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - https://yamtrack.alexlebens.net
