apiVersion: v1
kind: ServiceAccount
metadata:
  name: yamtrack
  labels:
    app.kubernetes.io/instance: yamtrack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: yamtrack
    helm.sh/chart: yamtrack-5.0.0
  namespace: yamtrack
