apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-key-secret
  namespace: prowlarr
  labels:
    app.kubernetes.io/name: prowlarr-key-secret
    app.kubernetes.io/instance: prowlarr
    app.kubernetes.io/part-of: prowlarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: key
      remoteRef:
        key: /cl01tl/prowlarr/key
        property: key
