apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-ps08rp-prowlarr-http-2xx
  namespace: prowlarr
  labels:
    app.kubernetes.io/name: blackbox-ps08rp-prowlarr-http-2xx
    app.kubernetes.io/instance: prowlarr
    app.kubernetes.io/part-of: prowlarr
spec:
  prober:
    url: ps08rp.alexlebens.net:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - https://prowlarr.alexlebens.net
