apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "custom.cloudflareSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "custom.cloudflareSecretName" . }}
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: {{ include "custom.cloudflareSecretKey" . }}
      remoteRef:
        key: /cloudflare/alexlebens.net/cl01tl-issuer-certificate
        property: token
