apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-data-backup-secret-remote
  namespace: vaultwarden
  labels:
    helm.sh/chart: volsync-target-data-1.1.0
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/part-of: vaultwarden
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vaultwarden-data-backup-secret-remote
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    template:
      mergePolicy: Merge
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "s3:{{ .ENDPOINT }}/{{ .BUCKET }}/cl01tl/vaultwarden/vaultwarden-data"
  data:
    - secretKey: ENDPOINT
      remoteRef:
        key: /garage/config
        property: ENDPOINT_REMOTE
    - secretKey: BUCKET
      remoteRef:
        key: /garage/home-infra/volsync-backups
        property: BUCKET
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: /garage/home-infra/volsync-backups
        property: RESTIC_PASSWORD_REMOTE
    - secretKey: AWS_DEFAULT_REGION
      remoteRef:
        key: /garage/home-infra/volsync-backups
        property: ACCESS_REGION
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /garage/home-infra/volsync-backups
        property: ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /garage/home-infra/volsync-backups
        property: ACCESS_SECRET_KEY
