apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: vaultwarden-postgresql-18-recovery
  namespace: vaultwarden
  labels:
    app.kubernetes.io/name: vaultwarden-postgresql-18-recovery
    helm.sh/chart: postgres-18-cluster-8.2.3
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/part-of: vaultwarden
    app.kubernetes.io/version: "v1.30.0"
    app.kubernetes.io/managed-by: Helm
spec:
  configuration:
    destinationPath: s3://postgres-backups/cl01tl/vaultwarden/vaultwarden-postgresql-18-cluster
    endpointURL: http://garage-main.garage:3900
    wal:
      compression: snappy
      maxParallel: 1
    data:
      compression: snappy
      jobs: 1
    s3Credentials:
      accessKeyId:
        name: vaultwarden-postgresql-18-recovery-secret
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: vaultwarden-postgresql-18-recovery-secret
        key: ACCESS_SECRET_KEY
      region:
        name: vaultwarden-postgresql-18-recovery-secret
        key: ACCESS_REGION
