sparkyfitness:
  config:
    timezone: America/Chicago
    allowPrivateNetworkCors: true
    extraTrustedOrigins: https://sparkyfitness.alexlebens.net
    oidc:
      enabled: true
      providerSlug: sparky-fitness
      providerName: Authentik
      issuerUrl: https://authentik.alexlebens.net/application/o/sparky-fitness
      logoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons@main/webp/authentik.webp
      secrets:
        existingSecret: sparkyfitness-oidc-secret
  httpRoute:
    enabled: true
    hostname: sparkyfitness.alexlebens.net
    parentRef:
      name: traefik-gateway
      namespace: traefik
  server:
    image:
      repository: ghcr.io/codewithcj/sparkyfitness-server
      tag: v0.16.5.8@sha256:55e5444a74dde388fa7e54121185c41b2130ffd9d12ad38e9e31765019a5c44b
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: null
        memory: null
    secrets:
      generate: false
      existingSecret: sparkyfitness-key-secret
    appDatabase:
      existingSecret: sparkyfitness-postgresql-18-cluster-app
    persistence:
      backup:
        size: 5Gi
        accessMode: ReadWriteOnce
        storageClass: ceph-block
      uploads:
        size: 10Gi
        accessMode: ReadWriteOnce
        storageClass: ceph-block
  frontend:
    image:
      repository: ghcr.io/codewithcj/sparkyfitness-frontend
      tag: v0.16.5.8@sha256:aaf810547097007f6d0b3c90af65f8ce89d9b899a6e3035299caffef830736dc
    resources:
      requests:
        cpu: 10m
        memory: 40Mi
      limits:
        cpu: null
        memory: null
  postgresql:
    enabled: false
  externalDatabase:
    host: sparkyfitness-postgresql-18-cluster-rw
    port: 5432
    database: app
    auth:
      existingSecret: sparkyfitness-postgresql-18-cluster-superuser
postgres-18-cluster:
  mode: recovery
  cluster:
    enableSuperuserAccess: true
    initdb:
      postInitTemplateSQL:
        - CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
        - CREATE EXTENSION IF NOT EXISTS "pgcrypto";
        - CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";
        - GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO "app" WITH GRANT OPTION;
  recovery:
    method: objectStore
    objectStore:
      index: 1
  backup:
    objectStore:
      - name: garage-local
        index: 1
        destinationBucket: postgres-backups
        externalSecretCredentialPath: /garage/home-infra/postgres-backups
        isWALArchiver: true
    scheduledBackups:
      - name: live-backup
        suspend: false
        immediate: true
        schedule: "0 0 16 * * *"
        backupName: garage-local
volsync-target-backup:
  pvcTarget: sparkyfitness-server-backup
  local:
    enabled: true
    schedule: 26 11 * * *
  remote:
    enabled: true
    schedule: 26 12 * * *
  external:
    enabled: true
    schedule: 26 13 * * *
