apiVersion: v2
name: searxng
version: 1.0.0
description: Searxng
keywords:
  - searxng
  - search
home: https://docs.alexlebens.dev/applications/searxng/
sources:
  - https://github.com/searxng/searxng
  - https://hub.docker.com/r/searxng/searxng
  - https://hub.docker.com/r/valkey/valkey
  - https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/volsync-target
maintainers:
  - name: alexlebens
dependencies:
  - name: app-template
    alias: searxng
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 4.6.2
  - name: volsync-target
    alias: volsync-target-data
    version: 1.1.1
    repository: oci://harbor.alexlebens.net/helm-charts
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/searxng.png
appVersion: 1.0.0
