searxng:
  controllers:
    api:
      type: deployment
      replicas: 1
      strategy: Recreate
      serviceAccount:
        name: searxng
      containers:
        main:
          image:
            repository: searxng/searxng
            tag: latest@sha256:ba3fbb767c9dcc29509fcbef00268a3a5d3535ed57e19a7582a56058f8b2c5c4
          env:
            - name: SEARXNG_BASE_URL
              value: http://searxng-api.searxng:8080
            - name: SEARXNG_QUERY_URL
              value: http://searxng-api.searxng:8080/search?q=<query>
            - name: SEARXNG_HOSTNAME
              value: searxng-api.searxng
            - name: ENABLE_RAG_WEB_SEARCH
              value: true
            - name: RAG_WEB_SEARCH_ENGINE
              value: searxng
            - name: RAG_WEB_SEARCH_RESULT_COUNT
              value: 3
            - name: RAG_WEB_SEARCH_CONCURRENT_REQUESTS
              value: 10
          resources:
            requests:
              cpu: 1m
              memory: 120Mi
    browser:
      type: deployment
      replicas: 1
      strategy: Recreate
      containers:
        main:
          image:
            repository: searxng/searxng
            tag: latest@sha256:ba3fbb767c9dcc29509fcbef00268a3a5d3535ed57e19a7582a56058f8b2c5c4
          env:
            - name: SEARXNG_BASE_URL
              value: https://searxng.alexlebens.net/
            - name: SEARXNG_QUERY_URL
              value: https://searxng.alexlebens.net/search?q=<query>
            - name: SEARXNG_HOSTNAME
              value: searxng.alexlebens.net
            - name: SEARXNG_VALKEY_URL
              value: valkey://localhost:6379/0
            - name: GRANIAN_HOST
              value: 0.0.0.0
            - name: GRANIAN_PORT
              value: 8080
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
        valkey:
          image:
            repository: valkey/valkey
            tag: 9.0.3-alpine@sha256:e1095c6c76ee982cb2d1e07edbb7fb2a53606630a1d810d5a47c9f646b708bf5
  serviceAccount:
    searxng:
      enabled: true
  service:
    api:
      controller: api
      ports:
        mail:
          port: 8080
          targetPort: 8080
    browser:
      controller: browser
      ports:
        mail:
          port: 80
          targetPort: 8080
  serviceMonitor:
    main:
      selector:
        matchLabels:
          app.kubernetes.io/name: searxng-browser
          app.kubernetes.io/instance: searxng-browser
      serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
      endpoints:
        - port: mail
          interval: 30s
          scrapeTimeout: 15s
          path: /metrics
          basicAuth:
            password:
              name: searxng-browser-metrics-credentials
              key: metrics-password
            username:
              name: searxng-browser-metrics-credentials
              key: metrics-username
  route:
    main:
      kind: HTTPRoute
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway
          namespace: traefik
      hostnames:
        - searxng.alexlebens.net
      rules:
        - backendRefs:
            - name: searxng-browser
              port: 80
          matches:
            - path:
                type: PathPrefix
                value: /
  persistence:
    config:
      type: custom
      volumeSpec:
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: searxng-api-config
      advancedMounts:
        api:
          main:
            - path: /etc/searxng/
              readOnly: true
              mountPropagation: None
    api-data:
      forceRename: searxng-api-data
      storageClass: ceph-block
      accessMode: ReadWriteOnce
      size: 5Gi
      advancedMounts:
        api:
          main:
            - path: /etc/searxng
              readOnly: false
    browser-data:
      forceRename: searxng-browser-data
      storageClass: ceph-block
      accessMode: ReadWriteOnce
      size: 5Gi
      advancedMounts:
        browser:
          main:
            - path: /etc/searxng
              readOnly: false
    valkey-data:
      storageClass: ceph-block
      accessMode: ReadWriteOnce
      size: 5Gi
      advancedMounts:
        browser:
          valkey:
            - path: /data
              readOnly: false
volsync-target-data:
  pvcTarget: searxng-browser-data
  local:
    enabled: true
    schedule: 16 11 * * *
  remote:
    enabled: true
    schedule: 16 12 * * *
  external:
    enabled: true
    schedule: 16 12 * * *
