apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-oidc-secret
  namespace: outline
  labels:
    app.kubernetes.io/name: outline-oidc-secret
    app.kubernetes.io/instance: outline
    app.kubernetes.io/part-of: outline
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: clientId
      remoteRef:
        key: /cl01tl/pocket-id/oidc/outline
        property: clientId
    - secretKey: clientSecret
      remoteRef:
        key: /cl01tl/pocket-id/oidc/outline
        property: clientSecret
