apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-oidc-authentik
  namespace: outline
  labels:
    app.kubernetes.io/name: outline-oidc-authentik
    app.kubernetes.io/instance: outline
    app.kubernetes.io/part-of: outline
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: client
      remoteRef:
        key: /cl01tl/authentik/oidc/outline
        property: client
    - secretKey: secret
      remoteRef:
        key: /cl01tl/authentik/oidc/outline
        property: secret
