apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-assets-secret-backup-secondary
  namespace: outline
  labels:
    app.kubernetes.io/name: outline-assets-secret-backup-secondary
    helm.sh/chart: garage-bucket-outline-assets-0.3.12
    app.kubernetes.io/instance: outline
    app.kubernetes.io/part-of: outline
    app.kubernetes.io/version: "v0.7.6"
    app.kubernetes.io/managed-by: Helm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /backblaze/home-infra/outline-assets
        property: ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /backblaze/home-infra/outline-assets
        property: ACCESS_SECRET_KEY
    - secretKey: AWS_REGION
      remoteRef:
        key: /backblaze/home-infra/outline-assets
        property: ACCESS_REGION
