apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-key
  namespace: outline
  labels:
    app.kubernetes.io/name: outline-key
    app.kubernetes.io/instance: outline
    app.kubernetes.io/part-of: outline
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: secret-key
      remoteRef:
        key: /cl01tl/outline/key
        property: secret-key
    - secretKey: utils-key
      remoteRef:
        key: /cl01tl/outline/key
        property: utils-key
