apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: outline-cloudflared
  labels:
    app.kubernetes.io/instance: outline
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/version: 2026.5.1
    helm.sh/chart: cloudflared-3.3.2
  namespace: outline
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - outline
  selector:
    matchLabels:
      app.kubernetes.io/instance: outline
      app.kubernetes.io/name: cloudflared
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
      scrapeTimeout: 10s
