apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trek-key
  namespace: trek
  labels:
    app.kubernetes.io/name: trek-key
    app.kubernetes.io/instance: trek
    app.kubernetes.io/part-of: trek
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: encryption-key
      remoteRef:
        key: /cl01tl/trek/key
        property: encryption-key
