apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trek-cloudflared-secret
  namespace: trek
  labels:
    app.kubernetes.io/name: trek-cloudflared-secret
    helm.sh/chart: cloudflared-4.2.2
    app.kubernetes.io/version: "4.2.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: trek
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: cf-tunnel-token
      remoteRef:
        key: /cloudflare/tunnels/trek
        property: token
