apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trek-oidc-secret
  namespace: trek
  labels:
    app.kubernetes.io/name: trek-oidc-secret
    app.kubernetes.io/instance: trek
    app.kubernetes.io/part-of: trek
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: clientId
      remoteRef:
        key: /cl01tl/pocket-id/oidc/trek
        property: clientId
    - secretKey: clientSecret
      remoteRef:
        key: /cl01tl/pocket-id/oidc/trek
        property: clientSecret
