apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: trek-uploads-backup-source-remote
  namespace: trek
  labels:
    helm.sh/chart: volsync-target-uploads-2.2.1
    app.kubernetes.io/instance: trek
    app.kubernetes.io/part-of: trek
    app.kubernetes.io/version: "2.2.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trek-uploads-backup
spec:
  sourcePVC: trek-uploads
  trigger:
    schedule: 0 10 * * 0
  restic:
    pruneIntervalDays: 7
    repository: trek-uploads-backup-secret-remote
    retain:
      daily: 0
      hourly: 0
      monthly: 0
      weekly: 12
      yearly: 0
    moverSecurityContext:
      runAsGroup: 1000
      runAsUser: 1000
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-blockpool-snapshot
    cacheCapacity: 1Gi
