{
 "title": "Gatus",
 "tags": [
  "service",
  "endpoint",
  "uptime"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Success rate",
   "type": "stat",
   "description": "Number of successful results compared to the total number of results during the current interval",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(endpoint) (sum by(key) (rate(gatus_results_total{success=\"true\"}[5m]))) / sum by(endpoint) (sum by(key) (rate(gatus_results_total[5m])))",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "gatus_results_duration_seconds", "legendFormat": "{{key}}" }
   ]
  },
  {
   "title": "Success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(key) (rate(gatus_results_total{success=\"true\"}[5m])) / sum by(key) (rate(gatus_results_total[5m]))",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Total results per minute",
   "type": "timeseries",
   "description": "Number of results per minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total[5m])*60) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Successful results per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total{success=\"true\"}[5m])*60) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Unsuccessful results per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total{success=\"false\"}[5m])*60) by (key)",
     "legendFormat": "{{key}} "
    }
   ]
  }
 ]
}