apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "custom.defaultOidcSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "custom.defaultOidcSecret" . }}
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: clientId
      remoteRef:
        key: /cl01tl/pocket-id/oidc/immich
        property: clientId
    - secretKey: clientSecret
      remoteRef:
        key: /cl01tl/pocket-id/oidc/immich
        property: clientSecret

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-memories
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: immich-memories
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: IMMICH_API_KEY_USER1
      remoteRef:
        key: /cl01tl/immich/api-key
        property: memories
    - secretKey: NTFY_PASSWORD_USER1
      remoteRef:
        key: /cl01tl/ntfy/users/cl01tl
        property: password
