{
 "title": "Democratic CSI (Synology iSCSI)",
 "tags": [
  "system",
  "storage",
  "iscsi"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "storageclass",
    "label": "StorageClass",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info{storageclass=~\"synology-iscsi.*\"}, storageclass)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info{storageclass=~\"$storageclass\"}, namespace)"
    }
   },
   {
    "name": "pvc",
    "label": "PVC",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info{storageclass=~\"$storageclass\", namespace=~\"$namespace\"}, persistentvolumeclaim)"
    }
   }
  ]
 },
 "panels": [
  { "title": "iSCSI Volume Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active iSCSI Volumes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"} * on(persistentvolumeclaim, namespace) group_left(storageclass) (kube_persistentvolumeclaim_info{storageclass=~\"$storageclass\"}))",
     "legendFormat": "Active iSCSI Volumes"
    }
   ]
  },
  {
   "title": "Total Provisioned Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"} * on(persistentvolumeclaim, namespace) group_left(storageclass) (kube_persistentvolumeclaim_info{storageclass=~\"$storageclass\"}))",
     "legendFormat": "Total Capacity"
    }
   ]
  },
  {
   "title": "Total Used Space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"} * on(persistentvolumeclaim, namespace) group_left(storageclass) (kube_persistentvolumeclaim_info{storageclass=~\"$storageclass\"}))",
     "legendFormat": "Used Space"
    }
   ]
  },
  {
   "title": "Overall Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"} * on(persistentvolumeclaim, namespace) group_left(storageclass) (kube_persistentvolumeclaim_info{storageclass=~\"$storageclass\"})) / sum(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"} * on(persistentvolumeclaim, namespace) group_left(storageclass) (kube_persistentvolumeclaim_info{storageclass=~\"$storageclass\"}))",
     "legendFormat": "Overall Utilization"
    }
   ]
  },
  {
   "title": "iSCSI Volume Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"} * on(persistentvolumeclaim, namespace) group_left(storageclass) (kube_persistentvolumeclaim_info{storageclass=~\"$storageclass\"})"
    },
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"} * on(persistentvolumeclaim, namespace) group_left(storageclass) (kube_persistentvolumeclaim_info{storageclass=~\"$storageclass\"})"
    },
    {
     "expr": "kubelet_volume_stats_available_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"} * on(persistentvolumeclaim, namespace) group_left(storageclass) (kube_persistentvolumeclaim_info{storageclass=~\"$storageclass\"})"
    },
    {
     "expr": "100 * (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"}) * on(persistentvolumeclaim, namespace) group_left(storageclass) (kube_persistentvolumeclaim_info{storageclass=~\"$storageclass\"})"
    },
    {
     "expr": "kubelet_volume_stats_inodes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"} * on(persistentvolumeclaim, namespace) group_left(storageclass) (kube_persistentvolumeclaim_info{storageclass=~\"$storageclass\"})"
    },
    {
     "expr": "kubelet_volume_stats_inodes_used{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"} * on(persistentvolumeclaim, namespace) group_left(storageclass) (kube_persistentvolumeclaim_info{storageclass=~\"$storageclass\"})"
    },
    {
     "expr": "100 * (kubelet_volume_stats_inodes_used{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"} / kubelet_volume_stats_inodes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"}) * on(persistentvolumeclaim, namespace) group_left(storageclass) (kube_persistentvolumeclaim_info{storageclass=~\"$storageclass\"})"
    }
   ]
  },
  {
   "title": "Historical Space & Inode Trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "iSCSI Volume Space Used vs Capacity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"} * on(persistentvolumeclaim, namespace) group_left(storageclass) (kube_persistentvolumeclaim_info{storageclass=~\"$storageclass\"})",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}} (Used)"
    },
    {
     "expr": "kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"} * on(persistentvolumeclaim, namespace) group_left(storageclass) (kube_persistentvolumeclaim_info{storageclass=~\"$storageclass\"})",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}} (Capacity)"
    }
   ]
  },
  {
   "title": "iSCSI Volume Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"}) * on(persistentvolumeclaim, namespace) group_left(storageclass) (kube_persistentvolumeclaim_info{storageclass=~\"$storageclass\"})",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}