coredns:
  image:
    repository: registry.k8s.io/coredns/coredns
    tag: v1.14.3
    imagePullPolicy: Always
  replicaCount: 3
  resources:
    limits:
      cpu: null
      memory: null
    requests:
      cpu: 30m
      memory: 30Mi
  prometheus:
    service:
      enabled: true
    monitor:
      enabled: true
      namespace: kube-system
  service:
    clusterIP: 10.96.0.10
    clusterIPs:
      - 10.96.0.10
    name: kube-dns
  serviceAccount:
    create: true
    name: coredns
  priorityClassName: system-cluster-critical
  servers:
    - zones:
        - zone: .
          scheme: dns://
          use_tcp: true
      port: 53
      plugins:
        - name: errors
        - name: health
          configBlock: |-
            lameduck 5s
        - name: ready
        - name: kubernetes
          parameters: cluster.local in-addr.arpa ip6.arpa
          configBlock: |-
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        - name: prometheus
          parameters: :9153
        - name: forward
          parameters: . /etc/resolv.conf
        - name: cache
          parameters: 30
        - name: loop
        - name: reload
        - name: loadbalance
    - zones:
        - zone: alexlebens.net
          scheme: dns://
          use_tcp: true
      port: 53
      plugins:
        - name: errors
        - name: cache
          parameters: 30
        - name: prometheus
          parameters: :9153
        - name: forward
          parameters: . 10.111.232.172
    - zones:
        - zone: ts.net
          scheme: dns://
          use_tcp: true
      port: 53
      plugins:
        - name: errors
        - name: cache
          parameters: 30
        - name: prometheus
          parameters: :9153
        - name: forward
          parameters: . 10.97.20.219
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node.cloudprovider.kubernetes.io/uninitialized
      operator: Exists
      effect: NoSchedule
  deployment:
    name: coredns
