apiVersion: v2
name: movie-roulette
version: 1.0.0
description: Movie Roulette
keywords:
  - movie-roulette
  - jellyfin
home: https://wiki.alexlebens.dev/
sources:
  - https://github.com/sahara101/Movie-Roulette
  - https://github.com/sahara101/Movie-Roulette/pkgs/container/movie-roulette
  - https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template
maintainers:
  - name: alexlebens
dependencies:
  - name: app-template
    alias: movie-roulette
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 4.6.2
icon: https://raw.githubusercontent.com/sahara101/Movie-Roulette/refs/heads/main/static/icons/icon.png
# renovate: datasource=github-releases depName=sahara101/Movie-Roulette
appVersion: v5.4.0
