apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome-main
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: navidrome
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: navidrome
    helm.sh/chart: navidrome-5.0.1
  namespace: navidrome
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/name: navidrome
      app.kubernetes.io/instance: navidrome
  template:
    metadata:
      labels:
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: navidrome
        app.kubernetes.io/name: navidrome
    spec:
      enableServiceLinks: false
      serviceAccountName: navidrome
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - /bin/sh
            - -c
            - |
              mkdir -p /data/plugins
              install_plugin() {
                PLUGIN_NAME=$1
                VERSION=$2
                URL=$3
                if [ ! -f "/data/plugins/.${PLUGIN_NAME}.${VERSION}" ]; then
                  echo ">> Downloading ${PLUGIN_NAME} version ${VERSION}..."
                  rm -f /data/plugins/${PLUGIN_NAME}
                  rm -f /data/plugins/.${PLUGIN_NAME}.*
                  wget -qO /data/plugins/${PLUGIN_NAME} ${URL}
                  touch "/data/plugins/.${PLUGIN_NAME}.${VERSION}"
                else
                  echo ">> ${PLUGIN_NAME} version ${VERSION} is already installed, skipping ..."
                fi
              }
              # renovate: datasource=github-releases depName=NeptuneHub/AudioMuse-AI-NV-plugin
              install_plugin "audiomuseai.ndp" "v9" "https://github.com/NeptuneHub/AudioMuse-AI-NV-plugin/releases/download/v9/audiomuseai.ndp"

              # renovate: datasource=github-releases depName=J0R6IT0/navidrome-lyrics-plugin
              install_plugin "nd-lyrics.ndp" "v7.1.0" "https://github.com/J0R6IT0/navidrome-lyrics-plugin/releases/download/v7.1.0/nd-lyrics.ndp"

              # renovate: datasource=github-releases depName=andykelk/navidrome-ntfy-plugin
              install_plugin "navidrome-ntfy.ndp" "v1.1.0" "https://github.com/andykelk/navidrome-ntfy-plugin/releases/download/v1.1.0/navidrome-ntfy.ndp"
          image: busybox:1.38.0@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d
          name: download-plugins
          volumeMounts:
            - mountPath: /data
              name: data
      containers:
        - env:
            - name: ND_MUSICFOLDER
              value: /music
            - name: ND_DATAFOLDER
              value: /data
            - name: ND_CACHEFOLDER
              value: /cache
            - name: ND_BASEURL
              value: https://navidrome.alexlebens.net
            - name: ND_ENABLEINSIGHTSCOLLECTOR
              value: "false"
            - name: ND_PROMETHEUS_ENABLED
              value: "true"
            - name: ND_AUTOIMPORTPLAYLISTS
              value: "true"
            - name: ND_PLUGINS_ENABLED
              value: "true"
            - name: ND_PLUGINS_AUTORELOAD
              value: "true"
            - name: ND_LYRICSPRIORITY
              value: embedded,nd-lyrics
            - name: ND_AGENTS
              value: audiomuseai,lastfm,deezer
            - name: ND_DEVARTISTINFOTIMETOLIVE
              value: 1s
          image: ghcr.io/navidrome/navidrome:0.63.2@sha256:9012939114fbb1bb641b81cf96dec5ded15f0aafefe8d47a511d7cb919658e40
          name: main
          resources:
            limits:
              gpu.intel.com/i915: 1
            requests:
              cpu: 10m
              gpu.intel.com/i915: 1
              memory: 50Mi
          volumeMounts:
            - mountPath: /cache
              name: cache
            - mountPath: /data
              name: data
            - mountPath: /music
              name: music
              readOnly: true
            - mountPath: /music-grabber
              name: music-grabber
              readOnly: true
            - mountPath: /music-single
              name: music-single
              readOnly: true
            - mountPath: /music-youtube
              name: music-youtube
              readOnly: true
      volumes:
        - emptyDir: {}
          name: cache
        - name: data
          persistentVolumeClaim:
            claimName: navidrome-data
        - name: music
          persistentVolumeClaim:
            claimName: navidrome-music-nfs-storage
        - name: music-grabber
          persistentVolumeClaim:
            claimName: navidrome-music-grabber-nfs-storage
        - name: music-single
          persistentVolumeClaim:
            claimName: navidrome-music-single-nfs-storage
        - name: music-youtube
          persistentVolumeClaim:
            claimName: navidrome-music-youtube-nfs-storage
