apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome-audiomuse-worker
  labels:
    app.kubernetes.io/controller: audiomuse-worker
    app.kubernetes.io/instance: navidrome
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: navidrome
    helm.sh/chart: navidrome-5.1.0
  namespace: navidrome
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/controller: audiomuse-worker
      app.kubernetes.io/name: navidrome
      app.kubernetes.io/instance: navidrome
  template:
    metadata:
      labels:
        app.kubernetes.io/controller: audiomuse-worker
        app.kubernetes.io/instance: navidrome
        app.kubernetes.io/name: navidrome
    spec:
      enableServiceLinks: false
      serviceAccountName: navidrome
      automountServiceAccountToken: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - env:
            - name: AUDIOMUSE_ROLE
              value: worker
            - name: TZ
              value: America/Chicago
            - name: REDIS_URL
              value: redis://navidrome-valkey.navidrome:6379/0
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: navidrome-postgresql-18-cluster-app
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: navidrome-postgresql-18-cluster-app
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: dbname
                  name: navidrome-postgresql-18-cluster-app
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: navidrome-postgresql-18-cluster-app
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  key: port
                  name: navidrome-postgresql-18-cluster-app
          image: ghcr.io/neptunehub/audiomuse-ai:3.3.1@sha256:c89d17a3584a37a4da0cc0427fffc20a80680e78046d1ae6b0a27fa8af98fb90
          name: main
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
          volumeMounts:
            - mountPath: /music
              name: music
              readOnly: true
            - mountPath: /music-grabber
              name: music-grabber
              readOnly: true
            - mountPath: /music-single
              name: music-single
              readOnly: true
            - mountPath: /music-youtube
              name: music-youtube
              readOnly: true
      volumes:
        - name: music
          persistentVolumeClaim:
            claimName: navidrome-music-nfs-storage
        - name: music-grabber
          persistentVolumeClaim:
            claimName: navidrome-music-grabber-nfs-storage
        - name: music-single
          persistentVolumeClaim:
            claimName: navidrome-music-single-nfs-storage
        - name: music-youtube
          persistentVolumeClaim:
            claimName: navidrome-music-youtube-nfs-storage
