apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: navidrome-data-backup-source-external
  namespace: navidrome
  labels:
    helm.sh/chart: volsync-target-data-2.1.0
    app.kubernetes.io/instance: navidrome
    app.kubernetes.io/part-of: navidrome
    app.kubernetes.io/version: "2.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: navidrome-data-backup
spec:
  sourcePVC: navidrome-data
  trigger:
    schedule: 10 9 * * 3
  restic:
    pruneIntervalDays: 35
    repository: navidrome-data-backup-secret-external
    retain:
      daily: 0
      hourly: 0
      monthly: 0
      weekly: 12
      yearly: 0
    moverSecurityContext:
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      runAsGroup: 1000
      runAsUser: 1000
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-blockpool-snapshot
    cacheCapacity: 1Gi
