apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.backrest.persistence.storage.existingClaim }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.backrest.persistence.storage.existingClaim }}
    {{- include "custom.labels" . | nindent 4 }}
spec:
  volumeName: {{ .Values.backrest.persistence.storage.existingClaim }}
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.backrest.persistence.share.existingClaim }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.backrest.persistence.share.existingClaim }}
    {{- include "custom.labels" . | nindent 4 }}
spec:
  volumeName: {{ .Values.backrest.persistence.share.existingClaim }}
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
