apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: backrest
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: backrest
    {{- include "custom.labels" . | nindent 4 }}
spec:
  name: "Backrest"
  launchUrl: https://backrest.alexlebens.net
  description: "A web-accessible backup solution built on top of restic."
  callbackUrls:
    - https://backrest.alexlebens.net/oauth2/callback
  pkceEnabled: true
  skipConsent: true
  allowedUserGroups:
    - name: platform-admin
      namespace: pocket-id-operator
  clientID: 92B85CB6-7104-4271-9F02-C44A538C3F88
  clientSecretRef:
    name: backrest-oauth-proxy
    key: OAUTH2_PROXY_CLIENT_SECRET
  logo:
    logoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/png/backrest.png
    darkLogoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/png/backrest-light.png
