kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: webscrapbook-data
  labels:
    app.kubernetes.io/instance: webscrapbook
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: webscrapbook
    helm.sh/chart: webscrapbook-5.2.1
  namespace: webscrapbook
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi"
  storageClassName: "ceph-block"
