apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-ps09rp-webscrapbook-http-2xx
  namespace: webscrapbook
  labels:
    app.kubernetes.io/name: blackbox-ps09rp-webscrapbook-http-2xx
    app.kubernetes.io/instance: webscrapbook
    app.kubernetes.io/part-of: webscrapbook
spec:
  prober:
    url: ps09rp.alexlebens.dev:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - https://webscrapbook.alexlebens.dev
