apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: dawarich-storage-backup-source-external
  namespace: dawarich
  labels:
    helm.sh/chart: volsync-target-storage-1.0.0
    app.kubernetes.io/instance: dawarich
    app.kubernetes.io/part-of: dawarich
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dawarich-storage-backup
spec:
  sourcePVC: dawarich-storage
  trigger:
    schedule: 6 10 * * *
  restic:
    pruneIntervalDays: 7
    repository: dawarich-storage-backup-secret-external
    retain:
      daily: 7
      hourly: 0
      monthly: 3
      weekly: 4
      yearly: 1
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-blockpool-snapshot
    cacheCapacity: 1Gi
