apiVersion: v1
kind: Service
metadata:
  name: dawarich
  labels:
    app.kubernetes.io/instance: dawarich
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dawarich
    app.kubernetes.io/service: dawarich
    helm.sh/chart: dawarich-4.6.2
  namespace: dawarich
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 9394
      targetPort: 9394
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: dawarich
    app.kubernetes.io/name: dawarich
