apiVersion: v1
kind: Pod
metadata:
  name: open-archiver-meilisearch-test-connection
  labels:
    app.kubernetes.io/name: meilisearch
    helm.sh/chart: meilisearch-0.39.0
    app.kubernetes.io/instance: open-archiver
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['--spider', '--timeout=5', 'open-archiver-meilisearch:7700']
  restartPolicy: Never
