postiz:
  controllers:
    main:
      type: deployment
      strategy: Recreate
      containers:
        main:
          image:
            repository: ghcr.io/gitroomhq/postiz-app
            tag: v2.23.0@sha256:785f97312f66a347fb96cdccc4ded5a33ced69a672c89a9adc8054e7d6a21dc5
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: postiz-config
                  key: JWT_SECRET
            - name: MAIN_URL
              value: https://postiz.alexlebens.dev
            - name: FRONTEND_URL
              value: https://postiz.alexlebens.dev
            - name: NEXT_PUBLIC_BACKEND_URL
              value: https://postiz.alexlebens.dev/api
            - name: BACKEND_INTERNAL_URL
              value: http://localhost:3000
            - name: TEMPORAL_ADDRESS
              value: postiz-temporal-frontend:7233
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postiz-postgresql-18-cluster-app
                  key: uri
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: postiz-valkey-config
                  key: REDIS_URL
            - name: IS_GENERAL
              value: "true"
            - name: DISABLE_REGISTRATION
              value: "false"
            - name: RUN_CRON
              value: "true"
            - name: STORAGE_PROVIDER
              value: local
            - name: UPLOAD_DIRECTORY
              value: /uploads
            - name: NEXT_PUBLIC_UPLOAD_DIRECTORY
              value: /uploads
            - name: NEXT_PUBLIC_POSTIZ_OAUTH_DISPLAY_NAME
              value: AlexAuth
            - name: NEXT_PUBLIC_POSTIZ_OAUTH_LOGO_URL
              value: https://web-assets.alexlebens.dev/logo/logo-red.png
            - name: POSTIZ_GENERIC_OAUTH
              value: "true"
            - name: POSTIZ_OAUTH_URL
              value: https://pocket-id.alexlebens.dev
            - name: POSTIZ_OAUTH_AUTH_URL
              value: https://pocket-id.alexlebens.dev/authorize
            - name: POSTIZ_OAUTH_TOKEN_URL
              value: https://pocket-id.alexlebens.dev/api/oidc/token
            - name: POSTIZ_OAUTH_USERINFO_URL
              value: https://pocket-id.alexlebens.dev/api/oidc/userinfo
            - name: POSTIZ_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: postiz-oidc-secret
                  key: clientId
            - name: POSTIZ_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: postiz-oidc-secret
                  key: clientSecret
          resources:
            requests:
              cpu: 100m
              memory: 1000Mi
          probes:
            startup:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /
                  port: 5000
                initialDelaySeconds: 10
                periodSeconds: 10
                failureThreshold: 30
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /
                  port: 5000
                periodSeconds: 30
                timeoutSeconds: 5
                failureThreshold: 3
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /
                  port: 5000
                periodSeconds: 10
                timeoutSeconds: 5
                failureThreshold: 3
  service:
    main:
      ports:
        http:
          port: 80
          targetPort: 5000
  persistence:
    config:
      forceRename: postiz-config
      storageClass: ceph-block
      accessMode: ReadWriteOnce
      size: 2Gi
      advancedMounts:
        main:
          main:
            - path: /config
    uploads:
      forceRename: postiz-uploads
      storageClass: ceph-block
      accessMode: ReadWriteOnce
      size: 10Gi
      advancedMounts:
        main:
          main:
            - path: /uploads
temporal:
  server:
    metrics:
      serviceMonitor:
        enabled: true
    config:
      persistence:
        datastores:
          default:
            sql:
              pluginName: postgres12
              driverName: postgres12
              databaseName: temporal
              connectAddr: postiz-postgresql-18-cluster-rw.postiz:5432
              connectProtocol: "tcp"
              user: postgres
              existingSecret: postiz-postgresql-18-cluster-superuser
              secretKey: password
              tls:
                enabled: false
          visibility:
            sql:
              pluginName: postgres12
              driverName: postgres12
              databaseName: temporal_visibility
              connectAddr: postiz-postgresql-18-cluster-rw.postiz:5432
              connectProtocol: "tcp"
              user: postgres
              existingSecret: postiz-postgresql-18-cluster-superuser
              secretKey: password
              tls:
                enabled: false
      namespaces:
        create: true
        namespace:
          - name: default
            retention: 30d
    frontend:
      metrics:
        serviceMonitor:
          enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
    history:
      metrics:
        serviceMonitor:
          enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 200Mi
    matching:
      metrics:
        serviceMonitor:
          enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 200Mi
    worker:
      metrics:
        serviceMonitor:
          enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
  admintools:
    resources:
      requests:
        cpu: 10m
        memory: 10Mi
  web:
    image:
      repository: temporalio/ui
      tag: 2.53.3@sha256:eef301146e60fad34b47adaecfae4149016e34b2d44ba94fca5fd8e5441f182a
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
cloudflared:
  probe:
    enabled: true
    targetUrl: https://postiz.alexlebens.dev
valkey:
  valkey:
    auth:
      enabled: true
      usersExistingSecret: postiz-valkey-config
      aclUsers:
        default:
          permissions: "~* &* +@all"
postgres-18-cluster:
  mode: recovery
  cluster:
    enableSuperuserAccess: true
  recovery:
    objectStore:
      index: 1
  backup:
    objectStore:
      index: 1
    scheduledBackups:
      suspend: false
      schedule: "0 20 15 * * *"
  databases:
    - name: temporal
      ensure: present
      owner: app
    - name: temporal_visibility
      ensure: present
      owner: app
volsync-target-config:
  pvcTarget: postiz-config
  local:
    enabled: true
    schedule: 0 8 * * *
  remote:
    enabled: true
    schedule: 0 10 * * 4
  external:
    enabled: true
    schedule: 0 9 * * 4
volsync-target-upload:
  pvcTarget: postiz-uploads
  local:
    enabled: true
    schedule: 5 8 * * *
  remote:
    enabled: true
    schedule: 5 10 * * 4
  external:
    enabled: true
    schedule: 5 9 * * 4
