apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: digital-ocean-s3-exporter-credentials
  namespace: s3-exporter
  labels:
    app.kubernetes.io/name: digital-ocean-s3-exporter-credentials
    app.kubernetes.io/instance: s3-exporter
    app.kubernetes.io/part-of: s3-exporter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /digital-ocean/home-infra/s3-exporter
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /digital-ocean/home-infra/s3-exporter
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_REGION
      remoteRef:
        key: /digital-ocean/home-infra/s3-exporter
        property: AWS_REGION
