{
 "title": "S3 Storage",
 "tags": [
  "platform",
  "storage",
  "s3"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   { "name": "s3name", "label": "Endpoint", "query": "label_values(s3name)" },
   {
    "name": "bucketname",
    "label": "Bucket",
    "query": {
     "query": "label_values({s3name=\"$s3name\"},bucketname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Endpoint Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(s3_endpoint_up{s3name=\"$s3name\"}[1d])"
    }
   ]
  },
  { "title": "Bucket", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Storage Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(last_over_time(s3_bucket_size{s3name=\"$s3name\", bucketname=\"$bucketname\"}[1d]))"
    }
   ]
  },
  {
   "title": "Storage Usage ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(s3_bucket_size{s3name=\"$s3name\", bucketname=\"$bucketname\"})",
     "legendFormat": "{{ bucketname }}"
    }
   ]
  },
  {
   "title": "Object Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(s3_bucket_object_number{s3name=\"$s3name\", bucketname=\"$bucketname\"})",
     "legendFormat": "{{ bucketname }}"
    }
   ]
  },
  {
   "title": "Object Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(last_over_time(s3_bucket_object_number{s3name=\"$s3name\", bucketname=\"$bucketname\"}[1d]))"
    }
   ]
  },
  { "title": "Endpoint Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Storage Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(s3_total_size{s3name=\"$s3name\"}[1d])"
    }
   ]
  },
  {
   "title": "Storage Usage ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(bucketname) (s3_bucket_size{s3name=\"$s3name\"})",
     "legendFormat": "{{ bucketname }}"
    }
   ]
  },
  {
   "title": "Object Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(s3_total_object_number{s3name=\"$s3name\"}[1d])"
    }
   ]
  },
  {
   "title": "Object Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(bucketname) (s3_bucket_object_number{s3name=\"$s3name\"})",
     "legendFormat": "{{ bucketname }}"
    }
   ]
  }
 ]
}