seerr-chart:
  config:
    persistence:
      size: 5Gi
      accessModes:
        - ReadWriteOnce
      storageClass: ceph-block
  route:
    main:
      enabled: true
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway
          namespace: traefik
      hostnames:
        - seerr.alexlebens.net
  resources:
    requests:
      cpu: 10m
      memory: 500Mi
volsync-target-config:
  pvcTarget: seerr-seerr-chart-config
  local:
    enabled: true
    schedule: 20 8 * * *
  remote:
    enabled: true
    schedule: 20 10 * * 5
  external:
    enabled: true
    schedule: 20 9 * * 5
