seerr-chart:
  image:
    registry: ghcr.io
    repository: seerr-team/seerr
    tag: v3.0.1
  probes:
    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 5
    readinessProbe:
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 5
  config:
    persistence:
      size: 5Gi
      accessModes:
        - ReadWriteOnce
      storageClass: ceph-block
  ingress:
    enabled: false
  route:
    main:
      enabled: true
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway
          namespace: traefik
      hostnames:
        - seerr.alexlebens.net
      matches:
        - path:
            type: PathPrefix
            value: /
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
volsync-target-config:
  pvcTarget: seerr-seerr-chart-config
  local:
    enabled: true
    schedule: 20 11 * * *
  remote:
    enabled: false
  external:
    enabled: true
    schedule: 20 12 * * *
