apiVersion: v2
name: shelly-plug
version: 1.0.0
description: Shelly Plug
keywords:
  - shelly-plug
  - metrics
home: https://docs.alexlebens.dev/Applications/shelly-plug/
sources:
  - https://github.com/geerlingguy/shelly-plug-prometheus
  - https://hub.docker.com/r/alpine/git
  - https://hub.docker.com/_/php
  - https://github.com/bjw-s-labs/helm-charts/tree/main/charts/other/app-template/values.yaml
  - https://gitea.alexlebens.dev/alexlebens/helm-charts/src/branch/main/charts/common-helpers
maintainers:
  - name: alexlebens
dependencies:
  - name: app-template
    alias: shelly-plug
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 5.1.0
  - name: common-helpers
    repository: oci://harbor.alexlebens.dev/helm-charts
    version: 0.4.1
icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/shelly.png
appVersion: 1.0.0
