apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: cloudflare-ddns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cloudflare-ddns
    helm.sh/chart: cloudflare-ddns-dev-5.2.1
  namespace: cloudflare-ddns
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/name: cloudflare-ddns
      app.kubernetes.io/instance: cloudflare-ddns
  template:
    metadata:
      labels:
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: cloudflare-ddns
        app.kubernetes.io/name: cloudflare-ddns
    spec:
      enableServiceLinks: false
      serviceAccountName: cloudflare-ddns
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - env:
            - name: IP6_PROVIDER
              value: none
          envFrom:
            - secretRef:
                name: cloudflare-ddns-dev
          image: favonia/cloudflare-ddns:1.17.1@sha256:5e61736b982b87d84a1120b4767c4deff0f2cc55ca3ee9dcb1dc58623039b5cb
          name: main
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
