apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflare-ddns
  labels:
    app.kubernetes.io/instance: cloudflare-ddns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cloudflare-ddns
    helm.sh/chart: cloudflare-ddns-net-5.1.0
  namespace: cloudflare-ddns
