donetick:
  controllers:
    main:
      type: deployment
      strategy: Recreate
      pod:
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
          seccompProfile:
            type: RuntimeDefault
      containers:
        main:
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          image:
            repository: donetick/donetick
            tag: v0.1.80@sha256:eb94251e1a22d1613b2cc05546509461e708f30c6ae02e0907c4a6d44ceaa18c
          env:
            - name: TZ
              value: America/Chicago
            - name: DT_ENV
              value: selfhosted
            - name: DT_SERVER_PORT
              value: "2021"
            - name: DT_SERVER_PUBLIC_HOST
              value: https://donetick.alexlebens.dev
            - name: DT_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: donetick-key
                  key: jwt-secret
            - name: DT_DATABASE_TYPE
              value: postgres
            - name: DT_DATABASE_MIGRATION
              value: "true"
            - name: DT_DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: donetick-postgresql-18-cluster-app
                  key: host
            - name: DT_DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: donetick-postgresql-18-cluster-app
                  key: port
            - name: DT_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: donetick-postgresql-18-cluster-app
                  key: user
            - name: DT_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: donetick-postgresql-18-cluster-app
                  key: password
            - name: DT_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: donetick-postgresql-18-cluster-app
                  key: dbname
            - name: DT_STORAGE_STORAGE_TYPE
              value: s3
            - name: DT_STORAGE_BUCKET_NAME
              value: donetick-assets
            - name: DT_STORAGE_ENDPOINT
              value: http://cluster-b.garage-b:3900
            - name: DT_STORAGE_PATH_STYLE
              value: "true"
            - name: DT_STORAGE_REGION
              valueFrom:
                secretKeyRef:
                  name: donetick-assets-secret
                  key: region
            - name: DT_STORAGE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: donetick-assets-secret
                  key: access-key-id
            - name: DT_STORAGE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: donetick-assets-secret
                  key: secret-access-key
            - name: DT_EMAIL_PROVIDER
              value: smtp
            - name: DT_EMAIL_HOST
              value: postfix.postfix.svc.cluster.local
            - name: DT_EMAIL_PORT
              value: "587"
            - name: DT_EMAIL_EMAIL
              value: donetick@alexlebens.dev
            - name: DT_EMAIL_USER
              value: donetick@alexlebens.dev
            - name: DT_DISABLE_PASSWORD_AUTH
              value: true
            - name: DT_OAUTH2_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: donetick-oidc-secret
                  key: clientId
            - name: DT_OAUTH2_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: donetick-oidc-secret
                  key: clientSecret
            - name: DT_OAUTH2_NAME
              value: "AlexAuth"
            - name: DT_OAUTH2_AUTH_URL
              value: https://auth.alexlebens.dev/authorize
            - name: DT_OAUTH2_TOKEN_URL
              value: https://auth.alexlebens.dev/api/oidc/token
            - name: DT_OAUTH2_USER_INFO_URL
              value: https://auth.alexlebens.dev/api/oidc/userinfo
            - name: DT_OAUTH2_REDIRECT_URL
              value: https://donetick.alexlebens.dev/auth/oauth2
            - name: DT_OAUTH2_SCOPES
              value: openid,profile,email,groups
            - name: DT_OAUTH2_ADMIN_GROUPS
              value: admin
            - name: DT_OAUTH2_MANAGER_GROUPS
              value: admin
          resources:
            requests:
              cpu: 5m
              memory: 30Mi
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /api/v1/health
                  port: 2021
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /api/v1/health
                  port: 2021
  service:
    main:
      forceRename: donetick
      ports:
        http:
          port: 80
          targetPort: 2021
  route:
    main:
      kind: HTTPRoute
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Tasks"
        gethomepage.dev/description: "Donetick"
        gethomepage.dev/group: "Knowledge"
        gethomepage.dev/icon: "sh-donetick.webp"
        gethomepage.dev/siteMonitor: "http://donetick.donetick:80/api/v1/health"
        gethomepage.dev/statusStyle: "dot"
        gethomepage.dev/weight: "350"
        gethomepage.dev/podSelector: ""
      parentRefs:
        - name: traefik-gateway
          namespace: traefik
      hostnames:
        - donetick.alexlebens.dev
      rules:
        - backendRefs:
            - name: donetick
              port: 80
          matches:
            - path:
                type: PathPrefix
                value: /

pocket-id-client:
  mode: oidc
  client:
    displayName: "Donetick"
    description: "Open-source task & chore management."
    pkceEnabled: false
    callbackUrls:
      - https://donetick.alexlebens.dev/auth/oauth2
      - donetick://auth/oauth2

cloudflared:
  probe:
    enabled: true
    targetUrl: https://donetick.alexlebens.dev

postgres-18-cluster:
  mode: recovery
  recovery:
    objectStore:
      index: 1
  backup:
    objectStore:
      index: 1
    scheduledBackups:
      suspend: false
      schedule: "0 10 5 * * *"

s3-bucket:
  enabled: true
  bucketName: donetick-assets
  target: b
  cors:
    enabled: true
    allowedOrigins:
      - "https://donetick.alexlebens.dev"
    allowedMethods:
      - GET
      - PUT
      - POST
      - DELETE
      - HEAD
  backups:
    a:
      enabled: true
      cronJob:
        schedule: "0 0 * * *"
      destination:
        bucketName: donetick-assets
    c:
      enabled: true
      cronJob:
        schedule: "0 0 * * *"
      destination:
        bucketName: donetick-assets
    d:
      enabled: true
      cronJob:
        schedule: "0 0 * * *"
      destination:
        bucketName: donetick-assets-05a5ba180718cd4b

common-helpers:
  probe:
    internal: http://donetick.donetick:80
    external: https://donetick.alexlebens.dev
