apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: medialyze-oauth-proxy
  namespace: medialyze
  labels:
    app.kubernetes.io/name: medialyze-oauth-proxy
    app.kubernetes.io/instance: medialyze
    app.kubernetes.io/part-of: medialyze
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: OAUTH2_PROXY_CLIENT_ID
      remoteRef:
        key: /cl01tl/pocket-id/oidc/medialyze
        property: clientId
    - secretKey: OAUTH2_PROXY_CLIENT_SECRET
      remoteRef:
        key: /cl01tl/pocket-id/oidc/medialyze
        property: clientSecret
    - secretKey: OAUTH2_PROXY_COOKIE_SECRET
      remoteRef:
        key: /cl01tl/pocket-id/oidc/medialyze
        property: cookie
    - secretKey: OAUTH2_PROXY_OIDC_ISSUER_URL
      remoteRef:
        key: /cl01tl/pocket-id/config
        property: issuer-url
