kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: medialyze-data
  labels:
    app.kubernetes.io/instance: medialyze
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: medialyze
    helm.sh/chart: medialyze-4.6.2
  annotations:
    helm.sh/resource-policy: keep
  namespace: medialyze
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "ceph-block"
