apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: medialyze-data-backup-source-remote
  namespace: medialyze
  labels:
    helm.sh/chart: volsync-target-data-2.0.0
    app.kubernetes.io/instance: medialyze
    app.kubernetes.io/part-of: medialyze
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: medialyze-data-backup
spec:
  sourcePVC: medialyze-data
  trigger:
    schedule: 0 10 * * 3
  restic:
    pruneIntervalDays: 7
    repository: medialyze-data-backup-secret-remote
    retain:
      daily: 0
      hourly: 0
      monthly: 0
      weekly: 12
      yearly: 0
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-blockpool-snapshot
    cacheCapacity: 1Gi
