apiVersion: v1
kind: ServiceAccount
metadata:
  name: medialyze
  labels:
    app.kubernetes.io/instance: medialyze
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: medialyze
    helm.sh/chart: medialyze-5.0.1
  namespace: medialyze
