backrest:
  controllers:
    main:
      type: deployment
      strategy: Recreate
      containers:
        main:
          image:
            repository: ghcr.io/garethgeorge/backrest
            tag: v1.14.1@sha256:b852979754281026230cc69fb11428e6d57c9a97784ab4a444ffc7934c53a215
          env:
            - name: TZ
              value: America/Chicago
            - name: BACKREST_DATA
              value: /data
            - name: BACKREST_CONFIG
              value: /config/config.json
            - name: XDG_CACHE_HOME
              value: /cache
            - name: TMPDIR
              value: /tmp
          resources:
            requests:
              cpu: 1m
              memory: 40Mi
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                tcpSocket:
                  port: 9898
            readiness:
              enabled: true
              custom: true
              spec:
                tcpSocket:
                  port: 9898
        oauth:
          image:
            repository: quay.io/oauth2-proxy/oauth2-proxy
            tag: v7.15.4@sha256:b1b2021fe8f4004573e8d690dec6c7bb29cc44364572cf8510a05bf3a0ae2ded
          envFrom:
            - secretRef:
                name: backrest-oauth-proxy
          env:
            - name: OAUTH2_PROXY_HTTP_ADDRESS
              value: 0.0.0.0:4180
            - name: OAUTH2_PROXY_METRICS_ADDRESS
              value: 0.0.0.0:44180
            - name: OAUTH2_PROXY_UPSTREAMS
              value: http://localhost:9898
            - name: OAUTH2_PROXY_PROVIDER
              value: oidc
            - name: OAUTH2_PROXY_CODE_CHALLENGE_METHOD
              value: "S256"
            - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
              value: "true"
            - name: OAUTH2_PROXY_EMAIL_DOMAINS
              value: "*"
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /ping
                  port: 4180
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /ready
                  port: 4180
  service:
    main:
      ports:
        http:
          port: 80
          targetPort: 9898
        oauth:
          port: 4180
        oauth-metrics:
          port: 44180
  serviceMonitor:
    main:
      selector:
        matchLabels:
          app.kubernetes.io/name: backrest
          app.kubernetes.io/instance: backrest
      serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
      endpoints:
        - port: http
          interval: 300s
          scrapeTimeout: 15s
        - port: oauth-metrics
  route:
    main:
      kind: HTTPRoute
      parentRefs:
        - name: traefik-gateway
          namespace: traefik
      hostnames:
        - backrest.alexlebens.dev
      rules:
        - backendRefs:
            - name: backrest
              port: 4180
  persistence:
    data:
      forceRename: backrest-data
      storageClass: ceph-block
      accessMode: ReadWriteOnce
      size: 10Gi
      advancedMounts:
        main:
          main:
            - path: /data
    config:
      forceRename: backrest-config
      storageClass: ceph-block
      accessMode: ReadWriteOnce
      size: 1Gi
      advancedMounts:
        main:
          main:
            - path: /config
    cache:
      type: emptyDir
      advancedMounts:
        main:
          main:
            - path: /cache
    tmp:
      type: emptyDir
      advancedMounts:
        main:
          main:
            - path: /tmp
    storage:
      existingClaim: backrest-nfs-storage
      advancedMounts:
        main:
          main:
            - path: /mnt/storage
              readOnly: true
    share:
      existingClaim: backrest-nfs-share
      advancedMounts:
        main:
          main:
            - path: /mnt/share
              readOnly: true
volsync-target-data:
  pvcTarget: backrest-data
  local:
    enabled: true
    schedule: 15 8 * * *
  remote:
    enabled: true
    schedule: 15 10 * * 0
  external:
    enabled: true
    schedule: 15 9 * * 0
volsync-target-config:
  pvcTarget: backrest-config
  local:
    enabled: true
    schedule: 20 8 * * *
  remote:
    enabled: true
    schedule: 20 10 * * 0
  external:
    enabled: true
    schedule: 20 9 * * 0
