backrest:
  controllers:
    main:
      type: deployment
      replicas: 1
      strategy: Recreate
      containers:
        main:
          image:
            repository: ghcr.io/garethgeorge/backrest
            tag: v1.12.1@sha256:f4d34bd6fa985d13bdb6c01c5d8727e07708899afa9567d800808357d77b9fb0
          env:
            - name: TZ
              value: America/Chicago
            - name: BACKREST_DATA
              value: /data
            - name: BACKREST_CONFIG
              value: /config/config.json
            - name: XDG_CACHE_HOME
              value: /cache
            - name: TMPDIR
              value: /tmp
          resources:
            requests:
              cpu: 1m
              memory: 30Mi
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
          targetPort: 9898
          protocol: TCP
  serviceMonitor:
    main:
      selector:
        matchLabels:
          app.kubernetes.io/name: backrest
          app.kubernetes.io/instance: backrest
      serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
      endpoints:
        - port: http
          scheme: http
          path: /metrics
          interval: 300s
          scrapeTimeout: 15s
  route:
    main:
      kind: HTTPRoute
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway
          namespace: traefik
      hostnames:
        - backrest.alexlebens.net
      rules:
        - backendRefs:
            - name: backrest
              port: 80
          matches:
            - path:
                type: PathPrefix
                value: /
  persistence:
    data:
      forceRename: backrest-data
      storageClass: ceph-block
      accessMode: ReadWriteOnce
      size: 10Gi
      advancedMounts:
        main:
          main:
            - path: /data
              readOnly: false
    config:
      forceRename: backrest-config
      storageClass: ceph-block
      accessMode: ReadWriteOnce
      size: 1Gi
      advancedMounts:
        main:
          main:
            - path: /config
              readOnly: false
    cache:
      type: emptyDir
      advancedMounts:
        main:
          main:
            - path: /cache
              readOnly: false
    tmp:
      type: emptyDir
      advancedMounts:
        main:
          main:
            - path: /tmp
              readOnly: false
    storage:
      existingClaim: backrest-nfs-storage
      advancedMounts:
        main:
          main:
            - path: /mnt/storage
              readOnly: true
    share:
      existingClaim: backrest-nfs-share
      advancedMounts:
        main:
          main:
            - path: /mnt/share
              readOnly: true
volsync-target-data:
  pvcTarget: backrest-data
  local:
    enabled: true
    schedule: 6 8 * * *
  remote:
    enabled: true
    schedule: 6 9 * * *
  external:
    enabled: true
    schedule: 6 10 * * *
volsync-target-config:
  pvcTarget: backrest-config
  local:
    enabled: true
    schedule: 8 8 * * *
  remote:
    enabled: true
    schedule: 8 9 * * *
  external:
    enabled: true
    schedule: 8 10 * * *
