apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-oidc-authentik
  namespace: ollama
  labels:
    app.kubernetes.io/name: open-webui-oidc-authentik
    app.kubernetes.io/instance: ollama
    app.kubernetes.io/part-of: ollama
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: client
      remoteRef:
        key: /cl01tl/authentik/oidc/open-webui
        property: client
    - secretKey: secret
      remoteRef:
        key: /cl01tl/authentik/oidc/open-webui
        property: secret
