apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-oidc-secret
  namespace: ollama
  labels:
    app.kubernetes.io/name: open-webui-oidc-secret
    app.kubernetes.io/instance: ollama
    app.kubernetes.io/part-of: ollama
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: clientId
      remoteRef:
        key: /cl01tl/pocket-id/oidc/open-webui
        property: clientId
    - secretKey: clientSecret
      remoteRef:
        key: /cl01tl/pocket-id/oidc/open-webui
        property: clientSecret
