apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: open-webui
  namespace: ollama
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/instance: ollama
    app.kubernetes.io/part-of: ollama
spec:
  name: "Open WebUI (Ollama)"
  launchUrl: https://ollama-web.alexlebens.dev
  description: "User-friendly WebUI for interacting with Ollama models."
  callbackUrls:
    - https://ollama-web.alexlebens.dev/oauth/oidc/callback
  pkceEnabled: false
  skipConsent: true
  allowedUserGroups:
    - name: admin
      namespace: pocket-id-operator
    - name: user
      namespace: pocket-id-operator
  clientID: 939D6D1E-AF97-458B-B850-38D3CA20F343
  clientSecretRef:
    name: open-webui-oidc-secret
    key: clientSecret
  logo:
    logoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/open-webui.webp
    darkLogoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/open-webui.webp
