apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dependency-track-key-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: dependency-track-key-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: secret.key
      remoteRef:
        key: /cl01tl/dependency-track/key
        property: key

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dependency-track-oidc-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: dependency-track-oidc-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: client
      remoteRef:
        key: /authentik/oidc/dependency-track
        property: client
    - secretKey: secret
      remoteRef:
        key: /authentik/oidc/dependency-track
        property: secret
