apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-httproute-reader
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "kube-prometheus-stack.fullname" . }}-httproute-reader
    {{- include "custom.labels" . | nindent 4 }}
rules:
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes"]
    verbs: ["get", "list", "watch"]
