apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: prometheus
    {{- include "custom.labels" . | nindent 4 }}
spec:
  name: "Prometheus"
  launchUrl: https://prometheus{{ include "custom.domain" . }}
  description: "A systems and service monitoring system using standard metrics formats."
  callbackUrls:
    - https://prometheus{{ include "custom.domain" . }}/oauth2/callback
  pkceEnabled: true
  skipConsent: true
  allowedUserGroups:
    - name: platform-admin
      namespace: pocket-id-operator
  clientID: 82DD7A6F-288E-4684-BA11-17A727930943
  clientSecretRef:
    name: prometheus-oauth-proxy
    key: OAUTH2_PROXY_CLIENT_SECRET
  logo:
    logoUrl: {{ include "custom.iconUrl" . }}prometheus.webp

---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: alertmanager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: alertmanager
    {{- include "custom.labels" . | nindent 4 }}
spec:
  name: "Alertmanager"
  launchUrl: https://alertmanager{{ include "custom.domain" . }}
  description: "Generate alerts based on rules and metrics from Prometheus."
  callbackUrls:
    - https://alertmanager{{ include "custom.domain" . }}/oauth2/callback
  pkceEnabled: true
  skipConsent: true
  allowedUserGroups:
    - name: platform-admin
      namespace: pocket-id-operator
  clientID: 3F3FC9E6-4202-4624-9717-85BB9382B927
  clientSecretRef:
    name: alertmanager-oauth-proxy
    key: OAUTH2_PROXY_CLIENT_SECRET
  logo:
    logoUrl: {{ include "custom.iconUrl" . }}prometheus.webp
