{{- range $prober := .Values.blackboxProbes.probers }}
{{- if $prober.targets2xx }}
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-{{ $prober.name }}-http-2xx
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: blackbox-{{ $prober.name }}-http-2xx
    {{- include "custom.labels" $ | nindent 4 }}
spec:
  prober:
    url: {{ $prober.url }}
  module: http_2xx
  targets:
    staticConfig:
      static:
{{- range $prober.targets2xx }}
        - {{ . }}
{{- end }}
{{- end }}
{{- end }}
