apiVersion: v2
name: cilium
version: 1.0.0
description: Cilium
keywords:
  - cilium
  - operator
  - network
home: https://docs.alexlebens.dev/applications/cilium/
sources:
  - https://github.com/cilium/cilium
  - https://github.com/cilium/cilium/tree/main/install/kubernetes/cilium
maintainers:
  - name: alexlebens
dependencies:
  - name: cilium
    version: 1.19.3
    repository: https://helm.cilium.io/
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/cilium.png
# renovate: datasource=github-releases depName=cilium/cilium
appVersion: 1.19.3
