apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: harbor-secret
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: /cl01tl/harbor/config
        property: admin-password
    - secretKey: secretKey
      remoteRef:
        key: /cl01tl/harbor/key
        property: secret-key
    - secretKey: CSRF_KEY
      remoteRef:
        key: /cl01tl/harbor/key
        property: csrf-key
    - secretKey: secret
      remoteRef:
        key: /cl01tl/harbor/core
        property: secret
    - secretKey: tls.crt
      remoteRef:
        key: /cl01tl/harbor/core
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: /cl01tl/harbor/core
        property: tls.key
    - secretKey: JOBSERVICE_SECRET
      remoteRef:
        key: /cl01tl/harbor/jobservice
        property: secret
    - secretKey: REGISTRY_HTTP_SECRET
      remoteRef:
        key: /cl01tl/harbor/registry
        property: http-secret
    - secretKey: REGISTRY_HTPASSWD
      remoteRef:
        key: /cl01tl/harbor/registry
        property: ht-passwd
    - secretKey: REGISTRY_CREDENTIAL_PASSWORD
      remoteRef:
        key: /cl01tl/harbor/registry
        property: credential-password
    - secretKey: REGISTRY_PASSWD
      remoteRef:
        key: /cl01tl/harbor/registry
        property: credential-password
