libation:
  controllers:
    main:
      type: cronjob
      cronjob:
        suspend: false
        timeZone: America/Chicago
        schedule: 0 0 1 1 *
        backoffLimit: 3
        parallelism: 1
      containers:
        main:
          image:
            repository: rmcrackan/libation
            tag: 13.3.3@sha256:fbeb84916c81b654412801367b7e96796ffdba83d987a1ed5fed9896cf7cabee
          env:
            - name: SLEEP_TIME
              value: "-1"
            - name: LIBATION_BOOKS_DIR
              value: /data
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
    debug:
      type: deployment
      replicas: 0
      strategy: Recreate
      containers:
        main:
          image:
            repository: ubuntu
            tag: resolute-20260401@sha256:a072b64036a738e55bff8f9a9682cbb893bf20c213772effc1de8dee8df1cea9
          command:
            - "sleep"
            - "infinity"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
  persistence:
    config:
      forceRename: libation
      storageClass: ceph-block
      accessMode: ReadWriteOnce
      size: 500Mi
      advancedMounts:
        main:
          main:
            - path: /config
              readOnly: false
        debug:
          main:
            - path: /config
              readOnly: false
    audiobooks:
      existingClaim: libation-nfs-storage
      advancedMounts:
        main:
          main:
            - path: /data
              readOnly: false
        debug:
          main:
            - path: /data
              readOnly: false
volsync-target-config:
  pvcTarget: libation
  local:
    enabled: true
    schedule: 32 8 * * *
  remote:
    enabled: true
    schedule: 32 9 * * *
  external:
    enabled: true
    schedule: 32 10 * * *
