#!/usr/bin/env bash
set -euo pipefail

# Parse optional command-line flags / env vars
EVENT_NAME="${EVENT_NAME:-${GITHUB_EVENT_NAME:-workflow_dispatch}}"
ACTOR="${ACTOR:-${GITHUB_ACTOR:-gitea-bot}}"
SHA="${SHA:-${GITHUB_SHA:-HEAD}}"
REF_NAME="${REF_NAME:-${GITHUB_REF_NAME:-main}}"
IS_AUTOMERGE="${IS_AUTOMERGE:-false}"
CHANGED_CHARTS="${CHANGED_CHARTS:-}"
GITHUB_OUTPUT="${GITHUB_OUTPUT:-}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --event-name)
      EVENT_NAME="$2"
      shift 2
      ;;
    --actor)
      ACTOR="$2"
      shift 2
      ;;
    --sha)
      SHA="$2"
      shift 2
      ;;
    --ref-name)
      REF_NAME="$2"
      shift 2
      ;;
    --is-automerge)
      IS_AUTOMERGE="$2"
      shift 2
      ;;
    --changed-charts)
      CHANGED_CHARTS="$2"
      shift 2
      ;;
    -h|--help)
      echo "Usage: $0 [--event-name <name>] [--actor <user>] [--sha <sha>] [--ref-name <branch>] [--is-automerge <true|false>] [--changed-charts <list>]"
      echo "Generates PR title, commit message, and body markdown for manifest rendering workflows."
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

SHA_SHORT="${SHA:0:7}"

if [[ "${IS_AUTOMERGE}" == "true" ]]; then
  TITLE="Automated Manifest Update - Automerge"
  COMMIT_MSG="chore: Update manifests after automerge"
else
  TITLE="Automated Manifest Update"
  COMMIT_MSG="chore: Update manifests after change"
fi

BODY=$(cat << EOF
This PR contains newly rendered Kubernetes manifests automatically generated by the CI workflow.

### Details
- **Trigger**: \`${EVENT_NAME}\` by \`@${ACTOR}\`
- **Commit**: \`${SHA_SHORT}\` (on \`${REF_NAME}\`)
- **Charts Updated**: \`${CHANGED_CHARTS}\`
EOF
)

if [[ "${IS_AUTOMERGE}" == "true" ]]; then
  BODY="${BODY}

_This PR is expected to be automerged._"
fi

NOW_UTC="$(date -u +'%Y-%m-%d %H:%M UTC')"
UPDATE_COMMENT=$(cat << EOF
### Update Details (${NOW_UTC})
- **Trigger**: \`${EVENT_NAME}\` by \`@${ACTOR}\`
- **Commit**: \`${SHA_SHORT}\` (on \`${REF_NAME}\`)
- **Charts Updated**: \`${CHANGED_CHARTS}\`
EOF
)

echo ">> Generated PR Title: ${TITLE}"
echo ">> Generated Commit Message: ${COMMIT_MSG}"
echo ">> Generated PR Body:"
echo "${BODY}"
echo ""
echo ">> Generated Update Comment:"
echo "${UPDATE_COMMENT}"
echo ""

if [[ -n "${GITHUB_OUTPUT}" ]]; then
  echo "title=${TITLE}" >> "${GITHUB_OUTPUT}"
  echo "commit-msg=${COMMIT_MSG}" >> "${GITHUB_OUTPUT}"
  echo "body<<EOF" >> "${GITHUB_OUTPUT}"
  echo "${BODY}" >> "${GITHUB_OUTPUT}"
  echo "EOF" >> "${GITHUB_OUTPUT}"
  echo "update-comment<<EOF" >> "${GITHUB_OUTPUT}"
  echo "${UPDATE_COMMENT}" >> "${GITHUB_OUTPUT}"
  echo "EOF" >> "${GITHUB_OUTPUT}"
fi
