apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.navidrome.persistence.music.existingClaim }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.navidrome.persistence.music.existingClaim }}
    {{- include "custom.labels" . | nindent 4 }}
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume2/Storage/Music
    server: synology-bond{{ include "custom.domain" . }}
  mountOptions:
    - vers=4
    - minorversion=1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ index .Values.navidrome.persistence "music-youtube" "existingClaim" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ index .Values.navidrome.persistence "music-youtube" "existingClaim" }}
    {{- include "custom.labels" . | nindent 4 }}
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume2/Storage/Music Youtube/
    server: synology-bond{{ include "custom.domain" . }}
  mountOptions:
    - vers=4
    - minorversion=1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ index .Values.navidrome.persistence "music-grabber" "existingClaim" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ index .Values.navidrome.persistence "music-grabber" "existingClaim" }}
    {{- include "custom.labels" . | nindent 4 }}
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume2/Storage/Music Grabber/
    server: synology-bond{{ include "custom.domain" . }}
  mountOptions:
    - vers=4
    - minorversion=1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ index .Values.navidrome.persistence "music-single" "existingClaim" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ index .Values.navidrome.persistence "music-single" "existingClaim" }}
    {{- include "custom.labels" . | nindent 4 }}
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume2/Storage/Music Singles/
    server: synology-bond{{ include "custom.domain" . }}
  mountOptions:
    - vers=4
    - minorversion=1
