---
name: garage
services:
  garage:
    image: dxflrs/garage:v2.3.0@sha256:866bd13ed2038ba7e7190e840482bc27234c4afaf77be8cfa439ae088c1e4690
    container_name: garage
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
      - /volume2/Garage/meta:/var/lib/garage/meta
      - /volume2/Garage/data:/var/lib/garage/data
    environment:
      - TZ=America/Chicago
      - RUST_LOG=info
    env_file:
      - path: .env
        required: false
    ports:
      - '0.0.0.0:3900:3900'
      - '0.0.0.0:3901:3901'
      - '0.0.0.0:3902:3902'
      - '0.0.0.0:3903:3903'
    restart: always
    cap_drop:
      - all
    security_opt:
      - apparmor:unconfined
