{
 "title": "Navidrome",
 "tags": [
  "apps",
  "music"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Songs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "🎧" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "db_model_totals{job=\"$job\",model=\"media\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Albums",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "💽" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "db_model_totals{job=\"$job\",model=\"album\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Artists",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "🦄" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "db_model_totals{job=\"$job\", model=\"artist\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "🦊" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "db_model_totals{job=\"$job\", model=\"user\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "General Information",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "navidrome_info{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Media",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Songs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "db_model_totals{job=\"$job\",model=\"media\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Albums",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "db_model_totals{job=\"$job\",model=\"album\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Artists",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "db_model_totals{job=\"$job\",model=\"artist\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests by client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(client) (rate(http_request_count{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Time since last successful scan",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - media_scan_last{job=\"$job\", success=\"true\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed scans for period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(media_scans{job=\"$job\", success=\"false\"}[$__range])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Go-specific",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(\nprocess_cpu_seconds_total{job=\"$job\"}[1m]\n)) by (instance)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"$job\"}) by (instance)",
     "legendFormat": "RES@{{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 28 },
   "targets": [
    {
     "expr": "sum(go_threads{job=\"$job\"}) by (instance)",
     "legendFormat": "os threads@{{instance}}"
    },
    {
     "expr": "sum(go_goroutines{job=\"$job\"}) by (instance)",
     "legendFormat": "goroutines@{{instance}}"
    }
   ]
  },
  {
   "title": "Open descriptors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 33 },
   "targets": [
    {
     "expr": "sum(process_open_fds{job=\"$job\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC total seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{job=~\"navidrome.*\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC calls",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_count{job=~\"navidrome.*\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Go Information",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 38 },
   "targets": [
    {
     "expr": "go_info{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}