apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-immich-sync
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-immich-sync
    {{- include "custom.labels" . | nindent 4 }}
data:
  sync.py: |-
{{ .Files.Get "scripts/sync.py" | indent 4 }}
