apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "custom.storageMiaNfsName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "custom.storageMiaNfsName" . }}
    {{- include "custom.labels" . | nindent 4 }}
spec:
  volumeName: {{ include "custom.storageMiaNfsName" . }}
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "custom.storageRijksmuseumNfsName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "custom.storageRijksmuseumNfsName" . }}
    {{- include "custom.labels" . | nindent 4 }}
spec:
  volumeName: {{ include "custom.storageRijksmuseumNfsName" . }}
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
