apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ index .Values.foldergram.persistence "pictures-mia" "existingClaim" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ index .Values.foldergram.persistence "pictures-mia" "existingClaim" }}
    {{- include "custom.labels" . | nindent 4 }}
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: '/volume2/Storage/Pictures/Collections/Minneapolis Institute of Art'
    server: synology-bond{{ include "custom.domain" . }}
  mountOptions:
    - vers=4
    - minorversion=1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ index .Values.foldergram.persistence "pictures-rijksmuseum" "existingClaim" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ index .Values.foldergram.persistence "pictures-rijksmuseum" "existingClaim" }}
    {{- include "custom.labels" . | nindent 4 }}
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: '/volume2/Storage/Pictures/Collections/Rijksmuseum'
    server: synology-bond{{ include "custom.domain" . }}
  mountOptions:
    - vers=4
    - minorversion=1
