apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: subwave-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: subwave-secret
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: ADMIN_USER
      remoteRef:
        key: /cl01tl/subwave/config
        property: ADMIN_USER
    - secretKey: ADMIN_PASS
      remoteRef:
        key: /cl01tl/subwave/config
        property: ADMIN_PASS
    - secretKey: NAVIDROME_USER
      remoteRef:
        key: /cl01tl/navidrome/users/admin
        property: user
    - secretKey: NAVIDROME_PASS
      remoteRef:
        key: /cl01tl/navidrome/users/admin
        property: password
