apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trek-key
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: trek-key
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: encryption-key
      remoteRef:
        key: /cl01tl/trek/key
        property: encryption-key

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trek-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: trek-config
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: admin-email
      remoteRef:
        key: /cl01tl/trek/config
        property: admin-email
    - secretKey: admin-password
      remoteRef:
        key: /cl01tl/trek/config
        property: admin-password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trek-oidc-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: trek-oidc-secret
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: clientId
      remoteRef:
        key: /cl01tl/pocket-id/oidc/trek
        property: clientId
    - secretKey: clientSecret
      remoteRef:
        key: /cl01tl/pocket-id/oidc/trek
        property: clientSecret
