cloudnative-pg:
  replicaCount: 2
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
  monitoring:
    podMonitorEnabled: true
plugin-barman-cloud:
  replicaCount: 1
  crds:
    create: true
  resources:
    requests:
      cpu: 1m
      memory: 20Mi
