cloudnative-pg:
  resources:
    requests:
      cpu: 5m
      memory: 130Mi
  monitoring:
    podMonitorEnabled: true

plugin-barman-cloud:
  crds:
    create: true
  resources:
    requests:
      cpu: 1m
      memory: 30Mi

s3-bucket:
  enabled: true
  bucketName: postgres-backups
  target: a
  backups:
    c:
      enabled: true
      schedule: "0 0 * * *"
      destination:
        bucketName: postgres-backups
    d:
      enabled: true
      schedule: "0 0 * * *"
      destination:
        bucketName: postgres-backups-775957147abfbc73
