{
 "title": "CoreDNS",
 "tags": [
  "system",
  "dns"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_Prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(coredns_dns_requests_total, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests (by instance)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coredns_build_info{instance=\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Failed Reloads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_reload_failed_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Upstream Rejected Queries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 7, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_max_concurrent_rejects_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Upstream Health Check Fails",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_healthcheck_broken_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Panics",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_panics_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Local",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests (total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{instance=~\"$instance\"}[5m])) by (server)",
     "legendFormat": "{{server}}"
    },
    {
     "expr": "sum(rate(coredns_cache_requests_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "cache"
    }
   ]
  },
  {
   "title": "Requests (by type)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{instance=~\"$instance\"}[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Responses (latency, internet zone)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\", zone=\".\"}[5m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\", zone=\".\"}[5m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\", zone=\".\"}[5m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Requests (by zone)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{instance=~\"$instance\"}[5m])) by (zone)",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "Health: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "repeat": "instance",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cache (hitrate)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_cache_hits_total{instance=~\"$instance\", type=\"success\"}[5m])) / sum(rate(coredns_cache_requests_total{instance=~\"$instance\"}[5m]))",
       "legendFormat": "hits: success"
      },
      {
       "expr": "sum(rate(coredns_cache_hits_total{instance=~\"$instance\", type=\"denial\"}[5m])) / sum(rate(coredns_cache_requests_total{instance=~\"$instance\"}[5m]))",
       "legendFormat": "hits: denial"
      },
      {
       "expr": "(sum(rate(coredns_cache_requests_total{instance=~\"$instance\"}[5m])) - sum(rate(coredns_cache_hits_total{instance=~\"$instance\", type=\"success\"}[5m]))) / sum(rate(coredns_cache_requests_total{instance=~\"$instance\"}[5m]))",
       "legendFormat": "misses"
      },
      {
       "expr": "sum(rate(coredns_dnssec_cache_hits_total{instance=~\"$instance\"}[5m])) / sum(rate(coredns_cache_requests_total{instance=~\"$instance\"}[5m]))",
       "legendFormat": "hits: DNSSEC"
      },
      {
       "expr": "(sum(rate(coredns_cache_requests_total{instance=~\"$instance\"}[5m])) - sum(rate(coredns_dnssec_cache_hits_total{instance=~\"$instance\"}[5m]))) / sum(rate(coredns_cache_requests_total{instance=~\"$instance\"}[5m]))",
       "legendFormat": "misses: DNSSEC"
      }
     ]
    },
    {
     "title": "Requests (DNSSEC by zone)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_do_requests_total{instance=~\"$instance\"}[5m])) by (zone)",
       "legendFormat": "{{zone}}"
      }
     ]
    },
    {
     "title": "Responses (by code)",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(rate(coredns_dns_responses_total{instance=~\"$instance\"}[5m])) by (rcode)",
       "legendFormat": "{{rcode}}"
      }
     ]
    },
    {
     "title": "Requests (size, internet zone)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\", zone=\".\"}[5m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\", zone=\".\"}[5m])) by (le))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\", zone=\".\"}[5m])) by (le))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Responses (size, internet zone)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\", zone=\".\"}[5m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\", zone=\".\"}[5m])) by (le))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\", zone=\".\"}[5m])) by (le))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Cache (size)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(coredns_cache_entries{instance=~\"$instance\"}) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(coredns_dnssec_cache_entries{instance=~\"$instance\"})",
       "legendFormat": "DNSSEC"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests (total)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_requests_total{instance=~\"$instance\"}[5m]))",
       "legendFormat": "upstream"
      }
     ]
    },
    {
     "title": "Cache (hitrate)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_conn_cache_hits_total{instance=~\"$instance\"}[5m])) / sum(rate(coredns_forward_requests_total{instance=~\"$instance\"}[5m]))",
       "legendFormat": "hits"
      },
      {
       "expr": "(sum(rate(coredns_forward_requests_total{instance=~\"$instance\"}[5m])) - sum(rate(coredns_forward_conn_cache_hits_total{instance=~\"$instance\"}[5m]))) / sum(rate(coredns_forward_requests_total{instance=~\"$instance\"}[5m]))",
       "legendFormat": "misses"
      }
     ]
    },
    {
     "title": "Responses (latency)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(coredns_forward_request_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(coredns_forward_request_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (le))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(coredns_forward_request_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (le))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Requests (by upstream)",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_requests_total{instance=~\"$instance\"}[5m])) by (to)",
       "legendFormat": "{{to}}"
      }
     ]
    },
    {
     "title": "Responses (by code)",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(rate(coredns_forward_responses_total{instance=~\"$instance\"}[5m])) by (rcode)",
       "legendFormat": "{{rcode}}"
      }
     ]
    }
   ]
  }
 ]
}