apiVersion: v2
name: version-checker
version: 1.0.0
description: Version Checker
keywords:
  - version-checker
  - update-tracker
  - metrics
home: https://docs.alexlebens.dev/applications/version-checker/
sources:
  - https://github.com/jetstack/version-checker
  - https://quay.io/repository/jetstack/version-checker?tab=tags
  - https://github.com/jetstack/version-checker/tree/main/deploy/charts/version-checker
maintainers:
  - name: alexlebens
dependencies:
  - name: version-checker
    repository: https://charts.jetstack.io
    version: v0.10.0
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/omnitools.png
# renovate: datasource=github-releases depName=jetstack/version-checker
appVersion: v0.10.0
