version-checker:
  image:
    repository: quay.io/jetstack/version-checker
    tag: v0.11.0@sha256:eae9a374d22f8bf73311ac7d1f37fc4e78822d196117a0a42d5e9ba6cd749d01
  selfhosted:
    - name: Harbor
      host: http://harbor-registry.harbor:5000
    - name: Gitea
      host: http://gitea-http.gitea:3000
  resources:
    requests:
      cpu: 50m
      memory: 250Mi
  prometheus:
    enabled: true
    serviceAccountName: version-checker-prometheus
