version-checker:
  image:
    repository: quay.io/jetstack/version-checker
    tag: v0.10.0@sha256:ea7a85422684479d0e51a41efc8edb12bed8f43aa89ab59dfea45aa92b2e8c8d
  selfhosted:
    - name: Harbor
      host: http://harbor-registry.harbor:5000
    - name: Gitea
      host: http://gitea-http.gitea:3000
  resources:
    requests:
      cpu: 1m
      memory: 400Mi
  prometheus:
    enabled: true
    serviceAccountName: version-checker-prometheus
