cloudflare-ddns:
  controllers:
    main:
      type: deployment
      replicas: 1
      pod:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      containers:
        main:
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          image:
            repository: favonia/cloudflare-ddns
            tag: 1.15.0@sha256:61013368c8f95981c0bb8bf56d962078d8b4e95724a554fa2dabb20d6e478097
          envFrom:
            - secretRef:
                name: cloudflare-ddns
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
