yubal:
  controllers:
    main:
      type: deployment
      strategy: Recreate
      pod:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
      containers:
        main:
          image:
            repository: ghcr.io/guillevc/yubal
            tag: 0.10.0@sha256:1447663d19eb69e4c6c6d274e979a99c4013a7d0a7666ca1bf2127612cd639eb
          env:
            - name: YUBAL_TZ
              value: America/Chicago
            - name: YUBAL_HOST
              value: 0.0.0.0
            - name: YUBAL_PORT
              value: 8000
            - name: YUBAL_LOG_LEVEL
              value: INFO
          resources:
            requests:
              cpu: 10m
              memory: 200Mi
        oauth:
          image:
            repository: quay.io/oauth2-proxy/oauth2-proxy
            tag: v7.15.4@sha256:b1b2021fe8f4004573e8d690dec6c7bb29cc44364572cf8510a05bf3a0ae2ded
          envFrom:
            - secretRef:
                name: yubal-oauth-proxy
          env:
            - name: OAUTH2_PROXY_HTTP_ADDRESS
              value: 0.0.0.0:4180
            - name: OAUTH2_PROXY_METRICS_ADDRESS
              value: 0.0.0.0:44180
            - name: OAUTH2_PROXY_UPSTREAMS
              value: http://localhost:8000
            - name: OAUTH2_PROXY_PROVIDER
              value: oidc
            - name: OAUTH2_PROXY_CODE_CHALLENGE_METHOD
              value: "S256"
            - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
              value: "true"
            - name: OAUTH2_PROXY_EMAIL_DOMAINS
              value: "*"
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /ping
                  port: 4180
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /ready
                  port: 4180
  service:
    main:
      ports:
        http:
          port: 80
          targetPort: 8000
        oauth:
          port: 4180
        oauth-metrics:
          port: 44180
  serviceMonitor:
    main:
      selector:
        matchLabels:
          app.kubernetes.io/name: yubal
          app.kubernetes.io/instance: yubal
      serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
      endpoints:
        - port: oauth-metrics
  route:
    main:
      kind: HTTPRoute
      parentRefs:
        - name: traefik-gateway
          namespace: traefik
      hostnames:
        - yubal.alexlebens.net
      rules:
        - backendRefs:
            - name: yubal
              port: 4180
  persistence:
    config:
      forceRename: yubal
      storageClass: ceph-block
      accessMode: ReadWriteOnce
      size: 1Gi
      advancedMounts:
        main:
          main:
            - path: /app/config
    music:
      existingClaim: yubal-nfs-storage
      advancedMounts:
        main:
          main:
            - path: /app/data
volsync-target-config:
  pvcTarget: yubal
  local:
    enabled: true
    schedule: 15 8 * * *
  remote:
    enabled: true
    schedule: 15 10 * * 6
  external:
    enabled: true
    schedule: 15 9 * * 6
