yubal:
  controllers:
    main:
      type: deployment
      replicas: 1
      strategy: Recreate
      pod:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
      containers:
        main:
          image:
            repository: ghcr.io/guillevc/yubal
            tag: 0.7.2@sha256:906b7c90b738e77ad140178f6a5145f98c12af36e8321d427148c092836c37be
          env:
            - name: YUBAL_TZ
              value: America/Chicago
            - name: YUBAL_HOST
              value: 0.0.0.0
            - name: YUBAL_PORT
              value: 8000
            - name: YUBAL_LOG_LEVEL
              value: INFO
          resources:
            requests:
              cpu: 10m
              memory: 200Mi
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
          targetPort: 8000
  route:
    main:
      kind: HTTPRoute
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway
          namespace: traefik
      hostnames:
        - yubal.alexlebens.net
      rules:
        - backendRefs:
            - name: yubal
              port: 80
          matches:
            - path:
                type: PathPrefix
                value: /
  persistence:
    config:
      forceRename: yubal
      storageClass: ceph-block
      accessMode: ReadWriteOnce
      size: 1Gi
      advancedMounts:
        main:
          main:
            - path: /app/config
              readOnly: false
    music:
      existingClaim: yubal-nfs-storage
      advancedMounts:
        main:
          main:
            - path: /app/data
              readOnly: false
volsync-target-config:
  pvcTarget: yubal
  local:
    enabled: true
    schedule: 34 11 * * *
  remote:
    enabled: true
    schedule: 34 12 * * *
  external:
    enabled: true
    schedule: 34 14 * * *
