apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: libation-backup-source-external
  namespace: libation
  labels:
    helm.sh/chart: volsync-target-config-2.1.0
    app.kubernetes.io/instance: libation
    app.kubernetes.io/part-of: libation
    app.kubernetes.io/version: "2.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: libation-backup
spec:
  sourcePVC: libation
  trigger:
    schedule: 32 9 * * 2
  restic:
    pruneIntervalDays: 35
    repository: libation-backup-secret-external
    retain:
      daily: 0
      hourly: 0
      monthly: 0
      weekly: 12
      yearly: 0
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-blockpool-snapshot
    cacheCapacity: 1Gi
