apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: diun-dockerhub
  namespace: diun
  labels:
    app.kubernetes.io/name: diun-dockerhub
    app.kubernetes.io/instance: diun
    app.kubernetes.io/part-of: diun
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: DIUN_REGOPTS_0_USERNAME
      remoteRef:
        key: /dockerhub/tokens/diun
        property: username
    - secretKey: DIUN_REGOPTS_0_PASSWORD
      remoteRef:
        key: /dockerhub/tokens/diun
        property: token
