apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: diun-ntfy
  namespace: diun
  labels:
    app.kubernetes.io/name: diun-ntfy
    app.kubernetes.io/instance: diun
    app.kubernetes.io/part-of: diun
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: DIUN_NOTIF_NTFY_ENDPOINT
      remoteRef:
        key: /cl01tl/ntfy/config
        property: internal-endpoint
    - secretKey: DIUN_NOTIF_NTFY_TOPIC
      remoteRef:
        key: /cl01tl/ntfy/topics
        property: diun
    - secretKey: DIUN_NOTIF_NTFY_TOKEN
      remoteRef:
        key: /cl01tl/ntfy/users/cl01tl
        property: token
