apiVersion: v2
name: dependency-track
version: 1.0.0
description: Dependency Track
keywords:
  - dependency-track
  - vulnerability-scanner
home: https://docs.alexlebens.dev/applications/dependency-track/
sources:
  - https://github.com/DependencyTrack/dependency-track
  - https://hub.docker.com/r/dependencytrack/apiserver
  - https://hub.docker.com/r/dependencytrack/frontend
  - https://github.com/DependencyTrack/helm-charts/tree/main/charts/dependency-track
maintainers:
  - name: alexlebens
dependencies:
  - name: dependency-track
    version: 0.44.0
    repository: https://dependencytrack.github.io/helm-charts
  - name: postgres-cluster
    alias: postgres-18-cluster
    version: 7.11.2
    repository: oci://harbor.alexlebens.net/helm-charts
icon: https://avatars.githubusercontent.com/u/40258585
# renovate: datasource=github-releases depName=dependency-track
appVersion: 4.14.1
