apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freshrss-cloudflared-secret
  namespace: freshrss
  labels:
    app.kubernetes.io/name: freshrss-cloudflared-secret
    helm.sh/chart: cloudflared-4.1.0
    app.kubernetes.io/version: "4.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: freshrss
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: cf-tunnel-token
      remoteRef:
        key: /cloudflare/tunnels/freshrss
        property: token
