apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freshrss-install-config
  namespace: freshrss
  labels:
    app.kubernetes.io/name: freshrss-install-config
    app.kubernetes.io/instance: freshrss
    app.kubernetes.io/part-of: freshrss
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: ADMIN_EMAIL
      remoteRef:
        key: /cl01tl/freshrss/config
        property: admin-email
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: /cl01tl/freshrss/config
        property: admin-password
    - secretKey: ADMIN_API_PASSWORD
      remoteRef:
        key: /cl01tl/freshrss/config
        property: admin-api-password
