apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: freshrss-data-backup-source-remote
  namespace: freshrss
  labels:
    helm.sh/chart: volsync-target-data-2.1.0
    app.kubernetes.io/instance: freshrss
    app.kubernetes.io/part-of: freshrss
    app.kubernetes.io/version: "2.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: freshrss-data-backup
spec:
  sourcePVC: freshrss-data
  trigger:
    schedule: 5 10 * * 1
  restic:
    pruneIntervalDays: 7
    repository: freshrss-data-backup-secret-remote
    retain:
      daily: 0
      hourly: 0
      monthly: 0
      weekly: 12
      yearly: 0
    moverSecurityContext:
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      runAsGroup: 568
      runAsUser: 568
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-blockpool-snapshot
    cacheCapacity: 1Gi
