apiVersion: v1
kind: ServiceAccount
metadata:
  name: freshrss
  labels:
    app.kubernetes.io/instance: freshrss
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: freshrss
    helm.sh/chart: freshrss-5.0.0
  namespace: freshrss
