apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: litellm-secrets
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: master-key
      remoteRef:
        key: /cl01tl/ollama/litellm
        property: master-key
