music-grabber:
  controllers:
    main:
      type: deployment
      strategy: Recreate
      pod:
        securityContext:
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
      containers:
        main:
          image:
            repository: g33kphr33k/musicgrabber
            tag: 4.0.2@sha256:9e280b70d6a0b324dbf4cfe59e482b8f0693bdf7171f55b551c78d02c8f9cb53
          env:
            - name: MUSIC_DIR
              value: /mnt/store/Music Grabber/
            - name: ENABLE_MUSICBRAINZ
              value: true
            - name: ORGANISE_BY_ARTIST
              value: true
            - name: NAVIDROME_URL
              value: http://navidrome-main.navidrome:80
            - name: NAVIDROME_USER
              valueFrom:
                secretKeyRef:
                  name: music-grabber-config
                  key: navidrome-user
            - name: NAVIDROME_PASS
              valueFrom:
                secretKeyRef:
                  name: music-grabber-config
                  key: navidrome-password
            - name: SLSKD_URL
              value: http://slskd.slskd:5030
            - name: SLSKD_USER
              valueFrom:
                secretKeyRef:
                  name: music-grabber-config
                  key: slskd-user
            - name: SLSKD_PASS
              valueFrom:
                secretKeyRef:
                  name: music-grabber-config
                  key: slskd-password
            - name: SLSKD_DOWNLOADS_PATH
              value: /mnt/store/slskd/Downloads
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 10m
              memory: 50Mi
        oauth:
          image:
            repository: quay.io/oauth2-proxy/oauth2-proxy
            tag: v7.15.4@sha256:b1b2021fe8f4004573e8d690dec6c7bb29cc44364572cf8510a05bf3a0ae2ded
          envFrom:
            - secretRef:
                name: music-grabber-oauth-proxy
          env:
            - name: OAUTH2_PROXY_HTTP_ADDRESS
              value: 0.0.0.0:4180
            - name: OAUTH2_PROXY_METRICS_ADDRESS
              value: 0.0.0.0:44180
            - name: OAUTH2_PROXY_UPSTREAMS
              value: http://localhost:8080
            - name: OAUTH2_PROXY_PROVIDER
              value: oidc
            - name: OAUTH2_PROXY_CODE_CHALLENGE_METHOD
              value: "S256"
            - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
              value: "true"
            - name: OAUTH2_PROXY_SET_XAUTHREQUEST
              value: "true"
            - name: OAUTH2_PROXY_PASS_USER_HEADERS
              value: "true"
            - name: OAUTH2_PROXY_EMAIL_DOMAINS
              value: "*"
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /ping
                  port: 4180
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /ready
                  port: 4180
  service:
    main:
      ports:
        http:
          port: 80
          targetPort: 8080
        oauth:
          port: 4180
        oauth-metrics:
          port: 44180
  serviceMonitor:
    main:
      selector:
        matchLabels:
          app.kubernetes.io/name: music-grabber
          app.kubernetes.io/instance: music-grabber
      serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}'
      endpoints:
        - port: oauth-metrics
  route:
    main:
      kind: HTTPRoute
      parentRefs:
        - name: traefik-gateway
          namespace: traefik
      hostnames:
        - music-grabber.alexlebens.net
      rules:
        - backendRefs:
            - name: music-grabber
              port: 80
  persistence:
    data:
      forceRename: music-grabber-data
      storageClass: ceph-block
      accessMode: ReadWriteOnce
      size: 1Gi
      advancedMounts:
        main:
          main:
            - path: /data
    music:
      existingClaim: music-grabber-nfs-storage
      advancedMounts:
        main:
          main:
            - path: /mnt/store/
volsync-target-data:
  pvcTarget: music-grabber-data
  local:
    enabled: true
    schedule: 5 8 * * *
  remote:
    enabled: true
    schedule: 5 10 * * 3
  external:
    enabled: true
    schedule: 5 9 * * 3
