apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: actual-budget
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: actual-budget
    {{- include "custom.labels" $ | nindent 4 }}
spec:
  name: "Actual Budget"
  callbackUrls:
    - https://actual.alexlebens.net/openid/callback
  pkceEnabled: true
  skipConsent: true
  allowedUserGroups:
    - name: users
      namespace: pocket-id-operator
  secret:
    name: actual-budget-oidc-external-secret
    keys:
      clientID: clientId
      clientSecret: clientSecret
  logo:
    logoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/png/actual-budget.png
    darkLogoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/png/actual-budget.png
