{
 "title": "Anubis - Gitea",
 "tags": [
  "service",
  "proxy",
  "gitea"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(anubis_policy_results,namespace)"
    }
   },
   {
    "name": "action",
    "label": "action",
    "query": {
     "query": "label_values(anubis_policy_results{namespace=~\"$namespace\"},action)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests handled",
   "type": "stat",
   "description": "Total number of requests handled on the selected interval",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(anubis_policy_results{namespace=~\"$namespace\"}[$__range])) without (container,endpoint,pod,instance,job,namespace,action,rule)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Challenges Issued",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(anubis_challenges_issued{namespace=~\"$namespace\"}[$__range])) without (container,endpoint,pod,instance,job,namespace)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Verdicts",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(anubis_policy_results{namespace=~\"$namespace\"}[$__range])) without (container,endpoint,pod,instance,job,namespace,rule)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Verdicts over Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(anubis_policy_results{namespace=~\"$namespace\"}[$__rate_interval])) without (container,endpoint,pod,instance,job,namespace, rule)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Request rates (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(anubis_policy_results{namespace=~\"$namespace\"}[$__rate_interval])) without (container,endpoint,pod,instance,job,namespace,rule)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Challenges Issued",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(anubis_challenges_issued{namespace=~\"$namespace\"}[$__rate_interval])) without (container,endpoint,pod,instance,job,namespace)",
     "legendFormat": "{{embedded}}"
    }
   ]
  },
  {
   "title": "old",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request rates old",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(anubis_policy_results{}[$__rate_interval])) by (action)",
       "legendFormat": "{{action}}"
      },
      {
       "expr": "sum(rate(anubis_policy_results{instance=~\"$instance\"}[1h]))",
       "legendFormat": "1-hour average (total)"
      },
      {
       "expr": "sum(rate(anubis_policy_results{instance=~\"$instance\"}[24h]))",
       "legendFormat": "24-hour average (total)"
      },
      {
       "expr": "sum(rate(anubis_policy_results{instance=~\"$instance\",job=\"anubis\"}[1h] offset 24h))",
       "legendFormat": "Yesterday's 1-hour average (total)"
      },
      {
       "expr": "sum(rate(anubis_proxied_requests_total{instance=~\"$instance\",job=\"anubis\"}[$__rate_interval]))",
       "legendFormat": "Allowed"
      }
     ]
    },
    {
     "title": "Challenge results",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 17, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(anubis_challenges_validated{}[$__range])",
       "legendFormat": "Validated"
      },
      {
       "expr": "increase(anubis_failed_validations{}[$__range])",
       "legendFormat": "Failed"
      },
      {
       "expr": "sum by(job, instance) (increase(anubis_challenges_issued{}[$__range])) -  increase(anubis_challenges_validated{}[$__range]) - increase(anubis_failed_validations{}[$__range])",
       "legendFormat": "No response"
      }
     ]
    }
   ]
  },
  { "title": "Policy Actions $action", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "action" },
  {
   "title": "Request rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(anubis_policy_results{namespace=~\"$namespace\",action=~\"$action\"}[$__rate_interval])) without (container,endpoint,pod,instance,job,namespace, action)",
     "legendFormat": "{{rule}}"
    }
   ]
  }
 ]
}