{
 "title": "Gitea",
 "tags": [
  "platform",
  "code"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Gitea Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", namespace=~\"gitea\"},namespace)"
    }
   },
   {
    "name": "volume",
    "label": "Gitea PVC Name",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes{job=\"kubelet\", namespace=\"$namespace\"},persistentvolumeclaim)"
    }
   },
   { "name": "resolution", "query": "1m, 5m,15m,30,1h,2h,1d" }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PVC Storage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(instance, node) (kubelet_volume_stats_capacity_bytes{job=\"kubelet\", namespace=\"$namespace\", persistentvolumeclaim=\"$volume\"}) - sum without(instance, node) (kubelet_volume_stats_available_bytes{job=\"kubelet\", namespace=\"$namespace\", persistentvolumeclaim=\"$volume\"})",
     "legendFormat": "Used Space"
    },
    {
     "expr": "sum without(instance, node) (kubelet_volume_stats_available_bytes{job=\"kubelet\", namespace=\"$namespace\", persistentvolumeclaim=\"$volume\"})",
     "legendFormat": "Free Space"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Organizations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(gitea_organizations)" }
   ]
  },
  {
   "title": "Teams",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(gitea_teams)" }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(gitea_users)" }
   ]
  },
  {
   "title": "Milestones",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(gitea_milestones)" }
   ]
  },
  {
   "title": "Stars",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(gitea_stars)" }
   ]
  },
  {
   "title": "Watches",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(gitea_watches)" }
   ]
  },
  {
   "title": "Repositories",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(gitea_repositories)" }
   ]
  },
  {
   "title": "Releases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(gitea_releases)" }
   ]
  },
  {
   "title": "Issues Open",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(gitea_issues_open[10m]))"
    }
   ]
  },
  {
   "title": "Issues Closed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(gitea_issues_closed)" }
   ]
  },
  {
   "title": "Labels",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(gitea_labels)" }
   ]
  },
  {
   "title": "Comments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(gitea_comments)" }
   ]
  },
  {
   "title": "Issues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Issues by Repository",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 15 },
   "targets": [
    { "expr": "gitea_issues_by_repository", "legendFormat": "{{repository}}" }
   ]
  },
  {
   "title": "Issues by Label",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 10, "y": 15 },
   "targets": [
    { "expr": "gitea_issues_by_label", "legendFormat": "{{label}}" }
   ]
  }
 ]
}