apiVersion: apps/v1
kind: Deployment
metadata:
  name: isponsorblocktv
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: isponsorblocktv
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: isponsorblocktv
    helm.sh/chart: isponsorblocktv-4.6.2
  namespace: isponsorblocktv
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/name: isponsorblocktv
      app.kubernetes.io/instance: isponsorblocktv
  template:
    metadata:
      annotations:
        checksum/secrets: 52c2d3d6ede4f29240a1e0b99194b49369a163b0b24f28d9c14e0d8aa584d6a8
      labels:
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: isponsorblocktv
        app.kubernetes.io/name: isponsorblocktv
    spec:
      enableServiceLinks: false
      serviceAccountName: isponsorblocktv
      automountServiceAccountToken: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - image: ghcr.io/dmunozv04/isponsorblocktv:v2.7.0@sha256:ff292ed53c9208ebfa7da3be7084bd863339d545a799bfefed5092396f5e8b4b
          name: main
          resources:
            requests:
              cpu: 1m
              memory: 20Mi
          volumeMounts:
            - mountPath: /app/data/config.json
              mountPropagation: None
              name: config
              readOnly: true
              subPath: config.json
      volumes:
        - csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: isponsorblocktv-config
          name: config
