apiVersion: v1
kind: ServiceAccount
metadata:
  name: isponsorblocktv
  labels:
    app.kubernetes.io/instance: isponsorblocktv
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: isponsorblocktv
    helm.sh/chart: isponsorblocktv-4.6.2
  namespace: isponsorblocktv
secrets:
  - name: isponsorblocktv-isponsorblocktv-sa-token
