whodb:
  controllers:
    main:
      type: deployment
      replicas: 1
      containers:
        main:
          image:
            repository: clidey/whodb
            tag: 0.123.0@sha256:0f75d6bd4fb933c97f37a9f5400fdecc02bb0c43399ffcb492f8b57baa2a4a03
          env:
            - name: WHODB_OLLAMA_HOST
              value: ollama-router.ollama
            - name: WHODB_OLLAMA_PORT
              value: 11434
          resources:
            requests:
              cpu: 1m
              memory: 20Mi
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
          targetPort: 8080
  route:
    main:
      kind: HTTPRoute
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway
          namespace: traefik
      hostnames:
        - whodb.alexlebens.net
      rules:
        - backendRefs:
            - name: whodb
              port: 80
          matches:
            - path:
                type: PathPrefix
                value: /
