whodb:
  controllers:
    main:
      type: deployment
      replicas: 1
      containers:
        main:
          image:
            repository: clidey/whodb
            tag: 0.117.0@sha256:b2001893c9e50bc6585ee6b790e5101d14b0adbc9f48df2fe93807ee1c65755d
          env:
            - name: WHODB_OLLAMA_HOST
              value: ollama-server-2.ollama
            - name: WHODB_OLLAMA_PORT
              value: 11434
          resources:
            requests:
              cpu: 1m
              memory: 20Mi
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
          targetPort: 8080
  route:
    main:
      kind: HTTPRoute
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway
          namespace: traefik
      hostnames:
        - whodb.alexlebens.net
      rules:
        - backendRefs:
            - name: whodb
              port: 80
          matches:
            - path:
                type: PathPrefix
                value: /
