whodb:
  controllers:
    main:
      type: deployment
      replicas: 1
      containers:
        main:
          image:
            repository: clidey/whodb
            tag: 0.111.0@sha256:f6b71e6905d9d4b0cac28920e795092ddebd560582140f27f5f4278a9a332ea0
          env:
            - name: WHODB_OLLAMA_HOST
              value: ollama-server-2.ollama
            - name: WHODB_OLLAMA_PORT
              value: 11434
          resources:
            requests:
              cpu: 1m
              memory: 20Mi
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
          targetPort: 8080
  route:
    main:
      kind: HTTPRoute
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway
          namespace: traefik
      hostnames:
        - whodb.alexlebens.net
      rules:
        - backendRefs:
            - name: whodb
              port: 80
          matches:
            - path:
                type: PathPrefix
                value: /
