apiVersion: v1
kind: Endpoints
metadata:
  name: shelly-plug-sp-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: shelly-plug-sp-server
    {{- include "custom.labels" . | nindent 4 }}
subsets:
  - addresses:
      - ip: 10.230.0.100
    ports:
      - name: http
        port: 80

---
apiVersion: v1
kind: Endpoints
metadata:
  name: shelly-plug-sp-desktop
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: shelly-plug-sp-desktop
    {{- include "custom.labels" . | nindent 4 }}
subsets:
  - addresses:
      - ip: 10.230.0.101
    ports:
      - name: http
        port: 80
