apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shelly-plug-config-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: shelly-plug-config-secret
    {{- include "custom.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  data:
    - secretKey: SHELLY_HTTP_USERNAME
      remoteRef:
        key: /it05sp/auth
        property: username
    - secretKey: SHELLY_HTTP_PASSWORD
      remoteRef:
        key: /it05sp/auth
        property: password
