apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sp-server
  namespace: {{ .Release.Namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/target: "traefik-cl01tl{{ include "custom.domain" . }}"
  labels:
    app.kubernetes.io/name: sp-server
    {{- include "custom.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`sp-server{{ include "custom.domain" . }}`)"
      kind: Rule
      services:
        - name: shelly-plug-sp-server
          port: 80
  tls: {}

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sp-desktop
  namespace: {{ .Release.Namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/target: "traefik-cl01tl{{ include "custom.domain" . }}"
  labels:
    app.kubernetes.io/name: sp-desktop
    {{- include "custom.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`sp-desktop{{ include "custom.domain" . }}`)"
      kind: Rule
      services:
        - name: shelly-plug-sp-desktop
          port: 80
  tls: {}
