apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: houndarr
  namespace: houndarr
  labels:
    app.kubernetes.io/name: houndarr
    app.kubernetes.io/instance: houndarr
    app.kubernetes.io/part-of: houndarr
spec:
  name: "Houndarr"
  launchUrl: https://houndarr.alexlebens.dev
  description: "Media searches & discovery."
  callbackUrls:
    - https://houndarr.alexlebens.dev/oauth2/callback
  pkceEnabled: true
  skipConsent: true
  allowedUserGroups:
    - name: admin
      namespace: pocket-id-operator
  clientID: 64B382F9-82A1-427E-9800-47C042BA1F68
  clientSecretRef:
    name: houndarr-oauth-proxy
    key: OAUTH2_PROXY_CLIENT_SECRET
  logo:
    logoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/houndarr.webp
    darkLogoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/houndarr.webp
