apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: houndarr-data-backup-source-remote
  namespace: houndarr
  labels:
    helm.sh/chart: volsync-target-data-1.1.0
    app.kubernetes.io/instance: houndarr
    app.kubernetes.io/part-of: houndarr
    app.kubernetes.io/version: "1.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: houndarr-data-backup
spec:
  sourcePVC: houndarr-data
  trigger:
    schedule: 40 12 * * *
  restic:
    pruneIntervalDays: 7
    repository: houndarr-data-backup-secret-remote
    retain:
      daily: 7
      hourly: 0
      monthly: 3
      weekly: 4
      yearly: 1
    moverSecurityContext:
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      runAsGroup: 1000
      runAsUser: 1000
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: ceph-blockpool-snapshot
    cacheCapacity: 1Gi
