site-saralebens:
  global:
    fullnameOverride: site-saralebens
  controllers:
    main:
      type: deployment
      replicas: 3
      strategy: RollingUpdate
      containers:
        main:
          image:
            repository: harbor.alexlebens.net/images/site-saralebens
            tag: 1.1.0@sha256:118dd5c65edcc0c77b00bbb6d9c70aab307aa04ba211f3fd74435e9b06c38304
          resources:
            requests:
              cpu: 10m
              memory: 40Mi
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
          targetPort: 4321
