site-saralebens:
  global:
    fullnameOverride: site-saralebens
  controllers:
    main:
      type: deployment
      replicas: 3
      strategy: RollingUpdate
      containers:
        main:
          image:
            repository: harbor.alexlebens.net/images/site-saralebens
            tag: 1.2.0@sha256:645930bfb6f51d56525d4175379ff774d383da62cb893a1313e91ee5c81079b0
          resources:
            requests:
              cpu: 10m
              memory: 40Mi
  service:
    main:
      controller: main
      ports:
        http:
          port: 80
          targetPort: 4321
